- webofneeds/won-node/src/main/java/won/node/camel/processor/fixed/CreateNeedMessageProcessor.java
- webofneeds/won-node/src/main/java/won/node/camel/route/fixed/WonMessageRoutes.java
- webofneeds/won-owner-webapp/src/main/webapp/app/service/won-service.js
Webapp now reacts to server responses
> Fix owner webapp

- webofneeds/won-core/src/main/java/won/protocol/message/WonMessage.java
- webofneeds/won-core/src/main/java/won/protocol/message/WonMessageBuilder.java
- webofneeds/won-core/src/main/java/won/protocol/vocabulary/WONMSG.java
- webofneeds/won-node/src/main/java/won/node/camel/processor/fixed/FailureResponseFromSystemToNodeProcessor.java
- webofneeds/won-owner-webapp/src/main/webapp/app/private-link/private-link.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/won-service.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/won.js
Owner webapp now processes server responses internally. The GUI doesn't reflect them, yet.
> Server responses (half) integrated

- webofneeds/won-bot/src/main/java/won/bot/app/BotRunnerApp.java
- webofneeds/won-bot/src/main/java/won/bot/framework/events/action/impl/AbstractCreateNeedAction.java
- webofneeds/won-bot/src/main/java/won/bot/framework/events/action/impl/CreateEchoNeedWithFacetsAction.java
- webofneeds/won-bot/src/main/java/won/bot/framework/events/action/impl/CreateNeedWithFacetsAction.java
- webofneeds/won-bot/src/main/java/won/bot/framework/events/action/impl/LogErrorAction.java
- webofneeds/won-bot/src/main/java/won/bot/framework/events/action/impl/PublishEventAction.java
- webofneeds/won-bot/src/main/java/won/bot/framework/events/event/impl/FailureEvent.java
- webofneeds/won-bot/src/main/java/won/bot/framework/events/event/impl/SuccessEvent.java
- webofneeds/won-bot/src/main/java/won/bot/impl/failsim/BaseEventListenerContextDecorator.java
- webofneeds/won-bot/src/main/java/won/bot/impl/failsim/ConstantNewEventURIDecorator.java
- webofneeds/won-bot/src/main/java/won/bot/impl/failsim/ConstantNewNeedURIDecorator.java
- webofneeds/won-bot/src/main/java/won/bot/impl/failsim/SameNeedURIFailureBot.java
- webofneeds/won-core/src/main/java/won/protocol/service/impl/WonNodeInformationServiceDecorator.java
- webofneeds/won-core/src/main/java/won/protocol/util/WonRdfUtils.java
- webofneeds/won-node/src/main/java/won/node/camel/processor/AbstractCamelProcessor.java
- webofneeds/won-node/src/main/java/won/node/camel/processor/general/PersistingWonMessageProcessor.java
- webofneeds/won-owner-webapp/src/main/webapp/app/conversation/conversation.html
Added an implementation of a bot for testing various server-side checks (well-formedness, duplicate ids etc.).
> Feat failbot

- webofneeds/pom.xml
- webofneeds/won-matcher-solr/pom.xml
- webofneeds/won-owner-webapp/pom.xml
-necessary update to maven >=3.1.0 (it was necessary to exclude maven-solr-matcher from build)
> altered the build process to include jspm "automation"

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/app_jspm.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/extended-gallery.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/flexgrid.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/image-dropzone.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/landingpage/landingpage.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/landingpage/landingpage.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/login.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/topnav.js
- webofneeds/won-owner-webapp/src/main/webapp/app/configRouting.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/reducers.js
- webofneeds/won-owner-webapp/src/main/webapp/rework.html
- webofneeds/won-owner-webapp/src/main/webapp/style/_landingpage.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_login.scss
implemented login/logout and automatic recognition if a user is already logged in
> Feat login logout

- webofneeds/won-owner-webapp/src/main/java/won/owner/pojo/UserPojo.java
- webofneeds/won-owner-webapp/src/main/java/won/owner/web/validator/UserRegisterValidator.java
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/landingpage/landingpage.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/landingpage/landingpage.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/login.js
- webofneeds/won-owner-webapp/src/main/webapp/app/directives/compareTo.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/user-service.js
- webofneeds/won-owner-webapp/src/main/webapp/app/sign-in/sign-up.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_landingpage.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/won.scss
- webofneeds/won-owner-webapp/src/test/resources/scripts/create-match-retrieve.sh
- webofneeds/won-owner-webapp/src/test/resources/scripts/data.sh
changed backend register validation logic (password repeat will not be sent anymore, but we will check for sufficient password length for now)
> Refac backend user validation

- webofneeds/won-owner-webapp/src/main/webapp/app/components/landingpage/landingpage.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/landingpage/landingpage.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/login.js
- webofneeds/won-owner-webapp/src/main/webapp/app/directives/compareTo.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_landingpage.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/won.scss
-added register validation (angular form validation)
-added login validation (angular form validation)
-added password compare directive (compareTo)
-only enable form buttons when form is valid
-added generic disabled button style (lightgray bg + white fontcolor)
> Implemented Frontend Login/Register Form Validation

- webofneeds/won-owner-webapp/src/main/webapp/app/components/flexgrid.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/landingpage/landingpage.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/landingpage/landingpage.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/login.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/matches-list-item.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/overview-title-bar.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/settings-title-bar.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/topnav.js
- webofneeds/won-owner-webapp/src/main/webapp/app/configRouting.js
- webofneeds/won-owner-webapp/src/main/webapp/app/utils.js
- webofneeds/won-owner-webapp/src/main/webapp/rework.html
- webofneeds/won-owner-webapp/src/main/webapp/style/_landingpage.scss
Added links to landingpage when clicking signup buttons
+autoscroll to signup element (with focus on the email adress element)
+overlay to make it easier to see that the focus is on the register elements
Refactoring:
ng-class shorthand instead of one lined ifs
> Feat register enhancement

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-need-title-bar.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/login.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/logout.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/owner-title-bar.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/settings-title-bar.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/topnav.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/visitor-title-bar.js
Automatic redirect to:
-feed after login
-createNeed after register
-landingpage after logout
Fixed broken href="#" which resulted in link to landingpage when clicked
Set autofocus on email (for login overlay)
> added redirect to

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-need/create-need.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-need/create-need.js
- webofneeds/won-owner-webapp/src/main/webapp/app/configRouting.js
- webofneeds/won-owner-webapp/src/main/webapp/app/messaging-agent.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/drafts-reducer.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/message-reducers.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/reducers.js
- webofneeds/won-owner-webapp/src/main/webapp/app/won-message-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/jspm_config.js
- webofneeds/won-owner-webapp/src/main/webapp/package.json
Merged Devel into this branch, ready to be pulled into devel without merge problems
> Messaging agent

- webofneeds/pom.xml
> changed maven-frontend-plugin version 

- webofneeds/won-owner-webapp/src/main/webapp/app/app_jspm.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-visitor-msgs/post-visitor-msgs.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-visitor-msgs/post-visitor-msgs.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-visitor/post-visitor.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/visitor-title-bar.js
- webofneeds/won-owner-webapp/src/main/webapp/app/configRouting.js
- webofneeds/won-owner-webapp/src/main/webapp/rework.html
plz merge before working on post-visitor
> Moved post-visitor-msgs to seperate view.

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/app_jspm.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/feed-item.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/feed/feed.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/feed/feed.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/matches/matches.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/overview-matches/overview-matches.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/overview-posts/overview-posts.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/overview-posts/overview-posts.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-item-line.js
- webofneeds/won-owner-webapp/src/main/webapp/app/messaging-agent.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/event-reducer.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/reducers.js
match count gets displayed on post overview page
> Feat linkeddata 4

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/overview-posts/overview-posts.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/overview-posts/overview-posts.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/overview-title-bar.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-item-line.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/event-reducer.js
- webofneeds/won-owner-webapp/src/main/webapp/app/selectors.js
- webofneeds/won-owner-webapp/src/main/webapp/app/utils.js
- webofneeds/won-owner-webapp/src/main/webapp/jspm_config.js
- webofneeds/won-owner-webapp/src/main/webapp/package.json
I added a new script-dependency (reselect), so don't forget to run `mvn install` on the owner-app
> Overview posts counters

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-item-line.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/visitor-title-bar.js
- webofneeds/won-owner-webapp/src/main/webapp/app/configRouting.js
- webofneeds/won-owner-webapp/src/main/webapp/rework.html
Just some links. Also: found some views we haven't implemented yet.
> Overview post links

- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-item-line.js
- webofneeds/won-owner-webapp/src/main/webapp/app/won-label-utils.js
This pull request is mutually exclusive to #397. It's a design decision which of these we want.
> User-friendly, relative timestamps

- webofneeds/pom.xml
- webofneeds/won-bot/src/main/java/won/bot/app/FeedbackTestingApp.java
- webofneeds/won-bot/src/main/java/won/bot/framework/events/action/impl/SendFeedbackForHintAction.java
- webofneeds/won-bot/src/main/java/won/bot/impl/LastSeenNeedsMatcherBot.java
- webofneeds/won-bot/src/main/java/won/bot/impl/RandomSimulatorBot.java
- webofneeds/won-bot/src/main/resources/spring/app/botRunner.xml
- webofneeds/won-bot/src/main/resources/spring/app/feedbackTesterApp.xml
- webofneeds/won-bot/src/main/resources/spring/bot/LastSeenNeedsMatcherBot.xml
- webofneeds/won-bot/src/main/resources/spring/component/needproducer/needproducer-mails-nonstop.xml
- webofneeds/won-bot/src/main/resources/spring/component/needproducer/needproducer-mails.xml
- webofneeds/won-bot/src/main/resources/spring/component/needproducer/needproducer-trig.xml
- webofneeds/won-bot/src/main/resources/spring/component/needproducer/needproducer-turtle.xml
- webofneeds/won-core/src/main/java/won/protocol/jms/NeedBasedCamelConfiguratorImpl.java
- webofneeds/won-core/src/main/java/won/protocol/message/WonMessageBuilder.java
- webofneeds/won-core/src/main/java/won/protocol/message/WonMessageType.java
- webofneeds/won-core/src/main/java/won/protocol/rest/LinkedDataRestClient.java
- webofneeds/won-core/src/main/java/won/protocol/util/linkeddata/CachingLinkedDataSource.java
- webofneeds/won-core/src/main/java/won/protocol/vocabulary/WON.java
- webofneeds/won-core/src/main/java/won/protocol/vocabulary/WONMSG.java
- webofneeds/won-core/src/main/resources/validation/02_prop/invalid_type.rq
- webofneeds/won-cryptography/src/main/java/won/protocol/message/processor/impl/KeyForNewNeedAddingProcessor.java
- webofneeds/won-matcher-solr/pom.xml
- webofneeds/won-matcher/src/main/java/won/matcher/protocol/impl/MatcherProtocolCommunicationServiceImpl.java
- webofneeds/won-matcher/src/main/java/won/matcher/protocol/impl/MatcherProtocolNeedServiceClientJMSBased.java
- webofneeds/won-node/src/main/java/won/node/camel/processor/fixed/HintFeedbackMessageFromOwnerProcessor.java
- webofneeds/won-node/src/main/java/won/node/camel/processor/fixed/SendMessageFromOwnerProcessor.java
- webofneeds/won-node/src/main/java/won/node/service/impl/DataAccessServiceImpl.java
- webofneeds/won-node/src/main/java/won/node/service/impl/LinkedDataServiceImpl.java
- webofneeds/won-owner-webapp/src/main/webapp/jspm_config.js
added handling of feedback messages on WoN node
added bots for testing using the FeedbackTestingApp
> Feat integrate feedback

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/account-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/load-action.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/matches-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js
plz leave the branch open afterwards. :)
> Split up actions.js

- webofneeds/won-owner-webapp/src/main/webapp/app/components/dynamic-textfield.js
- webofneeds/won-owner-webapp/src/main/webapp/gulpfile.js
- webofneeds/won-owner-webapp/src/main/webapp/package.json
- webofneeds/won-owner-webapp/src/main/webapp/rework.html
> Fix inputfield in ff

- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/won.js
Builds on `Fix duplicatepredicates` (though there's actually no need for that, in hindsight)
> Fix chatmsgsorting

- webofneeds/won-node/src/main/java/won/node/camel/processor/fixed/CloseMessageFromOwnerProcessor.java
- webofneeds/won-node/src/main/java/won/node/service/DataAccessService.java
- webofneeds/won-node/src/main/java/won/node/service/impl/DataAccessServiceImpl.java
close message is no longer sent to remote need if the connection is in state SUGGESTED
closes #471
> Fix close suggested

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/feedback-grid.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/won.js
- webofneeds/won-owner-webapp/src/main/webapp/app/won-message-utils.js
> add correct rating format for rate messages

- webofneeds/won-owner-webapp/src/main/webapp/app/components/dynamic-textfield.js
> Changed DynTextfield to always use the text from the DOM.

- webofneeds/won-docker/README.md
- webofneeds/won-docker/deploy_dev.sh
- webofneeds/won-docker/deploy_int.sh
- webofneeds/won-docker/deploy_master_run.sh
- webofneeds/won-docker/gencert/openssl-dev-int.conf
- webofneeds/won-docker/gencert/openssl-dev.conf
- webofneeds/won-docker/gencert/openssl-int.conf
- webofneeds/won-docker/nginx/nginx-dev.conf
- webofneeds/won-docker/nginx/nginx-int.conf
int and dev wonnode and owner are now using a nginx proxy 
int: https://satsrv06/
dev: https://satsrv07/
> Nginx for int and dev

- webofneeds/won-owner-webapp/src/main/webapp/app/components/matches-list-item.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/matches.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/overview-matches/overview-matches.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/overview-matches/overview-matches.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/overview-title-bar.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post/post.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post/post.js
- webofneeds/won-owner-webapp/src/main/webapp/app/configRouting.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_overview-matches.scss
> Refac matchescomponent

- webofneeds/won-docker/nginx/nginx-dev.conf
- webofneeds/won-docker/nginx/nginx-int.conf
- webofneeds/won-docker/nginx/nginx.conf
> fix nginx session related issues, fix #523

- webofneeds/won-docker/deploy_dev.sh
- webofneeds/won-docker/deploy_int.sh
- webofneeds/won-docker/deploy_master_run.sh
> fix links in email, use public owner address

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/load-action.js
- webofneeds/won-owner-webapp/src/main/webapp/app/configRouting.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer.js
A first step towards #575, that at least makes sure you don't get redirected away from the feed if you reload.
> Dispatching the username and email early

- webofneeds/won-owner-webapp/src/main/webapp/app/components/open-request.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js
- webofneeds/won-owner-webapp/src/main/webapp/app/selectors.js
- webofneeds/won-owner-webapp/src/main/webapp/app/utils.js
> Fix requestmessage #550

- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-need/create-need.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-need/create-need.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/login.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/posttype-select.js
> Fix encoding #600

- webofneeds/won-core/src/main/java/won/protocol/message/processor/impl/UriConsistencyCheckingWonMessageProcessor.java
> exempted HINT messages from sender NodeURI checks

- webofneeds/won-owner-webapp/src/main/webapp/app/components/dynamic-textfield.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js
Before, the submit in onKeydown would trigger really early, occassionally cutting off the last character if you were typing fast.
> Submit will happen in onInput instead of onKeyDown.

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/account-actions.js
> added a clearer error message on login action

- webofneeds/won-docker/deploy_int.sh
- webofneeds/won-docker/deploy_live_build.sh
> Integration test

- webofneeds/won-docker/deploy_live_run.sh
> fix live deployment

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/load-action.js
- webofneeds/won-owner-webapp/src/main/webapp/app/configRedux.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/user-reducer.js
- webofneeds/won-owner-webapp/src/main/webapp/app/won-message-utils.js
> Incrementally dispatching during page-load, when signed-in.

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/login.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/user-reducer.js
> remove loginError message when changing fields

- webofneeds/won-owner-webapp/src/main/webapp/app/components/feed-item.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-item-line.js
> Fix feed item clickable #650

- webofneeds/won-owner-webapp/src/main/webapp/app/configRouting.js
fixes #626 
fixes #571 
as of now you are only allowed to access the landingpage if you are not logged in, if you are logged in you will be redirected to the feed if you call the landingpage url
> updated accessControl

- webofneeds/won-owner-webapp/src/main/webapp/images/won-icons/ico16_indicator_error.svg
- webofneeds/won-owner-webapp/src/main/webapp/images/won-icons/ico16_indicator_info.svg
- webofneeds/won-owner-webapp/src/main/webapp/images/won-icons/ico16_indicator_warning.svg
@quasarchimaere for now, these icons should suffice. @m0ru maybe you want to rework them though
> added icons for toasts

- webofneeds/won-owner-webapp/src/main/webapp/app/components/overview-posts/overview-posts.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/overview-title-bar.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-item-line.js
(doesn't fix the more work-intensive #631 though, as there's higher-priority issues that we should focus on first)
> Fixed the counters @ overview-titlebar and post-overview

- webofneeds/won-matcher-service/src/main/java/won/matcher/service/common/service/sparql/SparqlService.java
- webofneeds/won-matcher-service/src/main/java/won/matcher/service/nodemanager/actor/WonNodeControllerActor.java
- webofneeds/won-matcher-service/src/main/java/won/matcher/service/nodemanager/service/HintDBService.java
> add in memory hint duplicate filter

- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/reducers.js
There's a filter in `reducers.js` now that takes care of this. If you introduce a new action adds connections to the state, make sure to add it to the `switch-case` there.
Theoretically we could lessen the performance footprint a bit, but I thought it might be premature optimization, given that the filter is only run for a few actions and -- unless it finds something -- only iterates over the few loaded connections once / it's cost is O( |connectionsLoaded| ) and there shouldn't be too many loaded.
Resolves #611
> Added a filter for connections between two owned needs to the reducer.

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/selectors.js
When you accept an incoming request, you should get redirected to the chat.
Resolves #630
> Fix acceptconnectionredirect #630

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-need/create-need.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-need/create-need.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/need-textfield.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-info.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/drafts-reducer.js
- webofneeds/won-owner-webapp/src/main/webapp/app/won-message-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/gulpfile.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_create-post.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_needtextfield.scss
Create Need updates that support the creation of a description and tags within the create-need interface
this is necessary to have the data available for user stories #590 and #687
> Feat description #590

- webofneeds/conf/matcher-solr/matcher-solr.properties
- webofneeds/won-core/src/main/java/won/protocol/util/WonRdfUtils.java
- webofneeds/won-docker/deploy_int.sh
- webofneeds/won-docker/deploy_live_run.sh
- webofneeds/won-docker/deploy_master.sh
- webofneeds/won-docker/solr/Dockerfile
- webofneeds/won-docker/solr/core/won/conf/schema.xml
- webofneeds/won-docker/solr/core/wontest/core.properties
- webofneeds/won-matcher-solr/src/main/java/won/matcher/solr/actor/AbstractSolrMatcherActor.java
- webofneeds/won-matcher-solr/src/main/java/won/matcher/solr/actor/SolrMonitoringMatcherActor.java
- webofneeds/won-matcher-solr/src/main/java/won/matcher/solr/config/SolrMatcherConfig.java
- webofneeds/won-matcher-solr/src/main/java/won/matcher/solr/hints/HintBuilder.java
- webofneeds/won-matcher-solr/src/main/java/won/matcher/solr/index/NeedIndexer.java
- webofneeds/won-matcher-solr/src/main/java/won/matcher/solr/query/BasicNeedQueryFactory.java
- webofneeds/won-matcher-solr/src/test/java/won/matcher/solr/SolrMatcherQueryTest.java
- webofneeds/won-matcher-solr/src/test/java/won/matcher/solr/SolrNeedIndexer.java
- webofneeds/won-matcher-solr/src/test/java/won/matcher/solr/evaluation/SolrMatcherEvaluation.java
- webofneeds/won-matcher-solr/src/test/java/won/matcher/solr/evaluation/SolrMatcherQueryExecutor.java
* and use a test core for usedForTestingNeeds
* needs created will now only be matched with one debug need (cause the debug bot does this), but not with all other debug needs available anymore
* how to test: create a some needs and check that each one them is matched with only 1 debug need (the one created for it) and any number of normal needs
> discard doNotMatch flagged needs in Solr matcher 

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/utils.js
> Fix connect #727

- webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js
> Paging in `won.fetch`

- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-need/create-need.html
- webofneeds/won-owner-webapp/src/main/webapp/style/_create-post.scss
Small Style Changes for create-need view
> small style changes for create-need view

- webofneeds/won-docker/deploy_live_build.sh
- webofneeds/won-docker/letsencrypt/Dockerfile
- webofneeds/won-docker/letsencrypt/certificate-request-and-renew.sh
- webofneeds/won-docker/letsencrypt/crontab-certificate-request-and-renew
- webofneeds/won-docker/letsencrypt/jessie-backports.list
- webofneeds/won-docker/nginx/nginx-http-only.conf
- webofneeds/won-docker/nginx/nginx.conf
> add letsencrypt certificate request and renewal

- webofneeds/won-docker/bigdata/Dockerfile
- webofneeds/won-docker/bots/Dockerfile
- webofneeds/won-docker/deploy_live_build.sh
- webofneeds/won-docker/letsencrypt/Dockerfile
- webofneeds/won-docker/letsencrypt/certificate-request-and-renew.sh
- webofneeds/won-docker/letsencrypt/crontab-certificate-request-and-renew
- webofneeds/won-docker/matcher-service/Dockerfile
- webofneeds/won-docker/matcher-solr/Dockerfile
- webofneeds/won-docker/nginx/nginx.conf
- webofneeds/won-docker/owner/Dockerfile
- webofneeds/won-docker/wonnode/Dockerfile
use the letsencrypt certificate in the wonnode too to avoid the bug described in fixes #774 
NOTE: code alreday deployed on live
> Letsencrypt fix

- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/debugbot/CreateDebugNeedWithFacetsAction.java
added the debugbot changes in order to only create debugneeds when the UsedForTesting flag is set when creating a need (in owner-webapp won.debugmode = true)
fixes #726 (debugbot changes)
> Feat#726 usedfortestingdebugbotchanges

- webofneeds/won-owner-webapp/src/main/webapp/app/components/landingpage/landingpage.js
- webofneeds/won-owner-webapp/src/main/webapp/app/won-label-utils.js
A native speaker told me, "I want to have something" somehow does not work. "I want something" is better.
> minor wording fix

- webofneeds/won-owner-webapp/src/main/webapp/app/components/landingpage/landingpage.html
- webofneeds/won-owner-webapp/src/main/webapp/index.jsp
> added imprint footer

- webofneeds/won-owner-webapp/src/main/webapp/app/components/matches.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post/post.html
> Fixed issue with unexpected immutable object.

- webofneeds/won-owner-webapp/src/main/webapp/app/app_jspm.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-selection.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/matches-flow-item.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/matches-grid-item.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/matches-list-item.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/matches.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/owner-title-bar.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post/post.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post/post.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_connection-selection-item-line.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_contextmenu.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_feedback-grid.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_matches-flow-item.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_matches-grid-item.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-owner.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_title-bar.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/won.scss
Fixes #818  -> changed to click events
Fixes #819 -> changed to click events
Fixes #644 -> test: there should not be a rearrange anymore since the height of the element is the same, and the hover effect has been changed to a click event (feedback-grid)
Fixes #609 ->see fix#644
Fixes #721 -> test: after creating a need a hover over the title-image should show the needtitlte
> Feat remove hover fixes #818 #819

- webofneeds/won-docker/image/bigdata/Dockerfile
fixes #859 
* already deployed on all environments (uploaded manually to docker hub and downloaded from there during deployment), just source code needs to be updated now
> fix bigdata startup problem

- webofneeds/won-owner-webapp/src/main/webapp/app/components/landingpage/landingpage.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/landingpage/landingpage.js
* removed misleading sarcastic faq item
* corrected email address
> improved landingpage

- webofneeds/won-docker/image/bigdata/Dockerfile
- webofneeds/won-owner-webapp/src/main/webapp/app/components/landingpage/landingpage.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/landingpage/landingpage.js
Pull Request as requested by @fkleedorfer
> Merge Changes from Master to Live

- webofneeds/won-docker/deploy/int_satsrv04/docker-compose.yml
- webofneeds/won-docker/deploy/int_satsrv05/docker-compose.yml
- webofneeds/won-docker/deploy/int_satsrv06/docker-compose.yml
- webofneeds/won-docker/deploy_int.sh
* test this just by deploying to integration-test and test if data is kept among 2 deployments
> mount database folders for int environment to keep data between deploy

- webofneeds/won-core/src/main/java/won/cryptography/ssl/AliasFromFingerprintGenerator.java
- webofneeds/won-core/src/main/java/won/protocol/repository/WonNodeRepository.java
- webofneeds/won-owner/src/main/java/won/owner/messaging/OwnerProtocolCommunicationServiceImpl.java
pushed that to integration-test, seems to work
> Fix owner registration

- webofneeds/won-core/src/main/java/won/protocol/util/WonRdfUtils.java
Added two Util methods to extract the need title and the description from a Dataset
> added two util methods

- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/mail/receive/CreateNeedFromMailAction.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/mail/receive/MailCommandAction.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/mail/receive/MailContentExtractor.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/mail/receive/MailParserAction.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/needlifecycle/AbstractCreateNeedAction.java
- webofneeds/won-bot/src/main/resources/spring/component/mail/mailContentExtractor.xml
fixes #879 
* make usedForTesting and DonotMatch configurable in mail bot
* make commands configurable
> Config debug needs

- webofneeds/conf/mail-bot.properties
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/mail/send/WonMimeMessageGenerator.java
- webofneeds/won-bot/src/main/resources/spring/bot/Mail2WonBot.xml
- webofneeds/won-docker/deploy/int_satsrv06/docker-compose.yml
- webofneeds/won-docker/deploy/master_satsrv06/docker-compose.yml
* set sent FROM address in mail bot and create properties 
=> can be reviewed & integrated
> Fix mailbot sent from

- webofneeds/won-owner-webapp/src/main/webapp/app/won-message-utils.js
Arguments weren't lining up, leading to an undefined value.
> Fix #813 Remote need data not loading

- webofneeds/won-bot/src/main/java/won/bot/framework/bot/base/BaseBot.java
- webofneeds/won-bot/src/main/java/won/bot/framework/bot/context/BotContext.java
- webofneeds/won-bot/src/main/java/won/bot/framework/bot/context/MemoryBotContext.java
- webofneeds/won-bot/src/main/java/won/bot/framework/bot/context/MongoBotContext.java
- webofneeds/won-bot/src/main/java/won/bot/framework/bot/context/MongoContextObjectList.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/EventBotActionUtils.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/debugbot/CreateDebugNeedWithFacetsAction.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/debugbot/MessageTimingManager.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/debugbot/SendChattyMessageAction.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/debugbot/SetChattinessAction.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/needlifecycle/CreateEchoNeedWithFacetsAction.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/wonmessage/ConnectWithAssociatedNeedAction.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/wonmessage/HintAssociatedNeedAction.java
- webofneeds/won-bot/src/test/java/won/bot/framework/bot/context/BotContextTests.java
- webofneeds/won-bot/src/test/resources/botContext.xml
* added ListMaps + Tests
* to be safe remove mailbot mongodb database on host satsrv06 (for int andf later for master) manually before deploying since some collections have changed: /usr/share/webofneeds/...
> Update Bot context mongodb implementation

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/app_jspm.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/chat-textfield.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/login.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/logout.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/overview-posts/overview-posts.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-item-line.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/topnav.js
- webofneeds/won-owner-webapp/src/main/webapp/app/configRouting.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/reducers.js
- webofneeds/won-owner-webapp/src/main/webapp/jspm_config.js
- webofneeds/won-owner-webapp/src/main/webapp/package.json
> Feat passwordmanager compatibility #814

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js
- webofneeds/won-owner-webapp/src/main/webapp/app/messaging-agent.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/connection-reducer.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/event-reducer.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/message-reducers.js
- webofneeds/won-owner-webapp/src/main/webapp/app/selectors.js
- webofneeds/won-owner-webapp/src/main/webapp/app/won-message-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/app/won-utils.js
Test-procedure: 
1. Create need and get connection
2. accept with message
3. instantly get redirected and see own accept-message in chat
4. reload
5. still see own accept-message in chat
Resolves #501
> Fix request accept message #501

- webofneeds/won-owner-webapp/src/main/webapp/app/app_jspm.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/feed-item.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/overview-posts/overview-posts.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/overview-posts/overview-posts.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-item-line.js
- webofneeds/won-owner-webapp/src/main/webapp/jspm_config.js
- webofneeds/won-owner-webapp/src/main/webapp/package.json
Posts should now correctly show up again in the feed and posts-overview tabs.
Problems were:
* Accessing an immutable obj as if it was plain js
* `this`-references pointing to `window` instead of the controller
* a duplicate field in a returned object
> Fix postoverview

- webofneeds/won-core/src/main/java/won/cryptography/service/CryptographyUtils.java
- webofneeds/won-core/src/main/java/won/cryptography/service/RegistrationRestClientHttps.java
- webofneeds/won-core/src/main/java/won/protocol/rest/LinkedDataRestBridge.java
- webofneeds/won-core/src/main/java/won/protocol/rest/LinkedDataRestClientHttps.java
> do not use sslContextCaching for https registration

- webofneeds/won-docker/deploy/live_satvm01/docker-compose.yml
- webofneeds/won-docker/deploy_live.sh
- webofneeds/won-docker/deploy_master.sh
> Docker tls

- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/matcher/RegisterMatcherAction.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/event/impl/matcher/MatcherRegisterFailedEvent.java
- webofneeds/won-bot/src/main/java/won/bot/impl/DebugBot.java
- webofneeds/won-bot/src/main/java/won/bot/impl/EchoBot.java
- webofneeds/won-bot/src/main/java/won/bot/impl/LastSeenNeedsMatcherBot.java
- webofneeds/won-bot/src/main/java/won/bot/impl/MatcherProtocolTestBot.java
- webofneeds/won-bot/src/main/resources/spring/bot/DebugBot.xml
- webofneeds/won-bot/src/main/resources/spring/bot/EchoBot.xml
- webofneeds/won-bot/src/main/resources/spring/bot/LastSeenNeedsMatcherBot.xml
- webofneeds/won-bot/src/main/resources/spring/bot/mailBasedSimpleReactiveBotMatcher.xml
- webofneeds/won-matcher/src/main/java/won/matcher/protocol/impl/MatcherProtocolMatcherServiceImplJMSBased.java
> fix debug bot node register exception

- webofneeds/won-owner-webapp/src/main/webapp/app/components/topnav.js
fixes WRONG#"945"WRONG, hides the login"drawer" when pressing signup within the login
fixes #937
> fixed defect #945

- webofneeds/won-owner-webapp/src/main/webapp/app/selectors.js
Apparently in #911 there was a typo. Merge that one first, and then this one on-top.
Resolves #958
> Fix for "Another "show more" bug => filter is null"

- webofneeds/won-owner-webapp/src/main/webapp/app/selectors.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js
> Fix unreachablecode #962

- webofneeds/won-owner-webapp/src/main/webapp/scripts/rdfstore-js/rdf_store.js
The missing posts issue should be resolved with this, possibly also other issues like #954 
How to test: 
Create > 4 needs, reload the webapp, multiple times. No needs should be missing any more.
fixes #942
> Fix missing posts #942

- webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js
There was another section, that firefox pointed out. This pull-request fixes that.
Resolves #962
> Fix unreachable code (part 2)

- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-info.js
- webofneeds/won-owner-webapp/src/main/webapp/app/leaflet-bundlable.js
- webofneeds/won-owner-webapp/src/main/webapp/app/won-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/jspm_config.js
- webofneeds/won-owner-webapp/src/main/webapp/package.json
Steps to test:
1. use firefox
1. create need
1. go to the post-info page
1. make sure the map isn't perfectly square but very wide compared to it's height
1. go to any other tab / back and reload the page there
1. go to the post-info page
1. before this bug you would see a gray are on the right side of the map. with this patch the marker should be in the center of the map and the entire map-background covered with map-tiles.
Resolves #953
> Fix mapgreyarea #953

- webofneeds/pom.xml
> fix websocket connection problems in proxy

- webofneeds/won-bot/pom.xml
- webofneeds/won-matcher-service/pom.xml
- webofneeds/won-matcher-solr/pom.xml
> fix Jena TDB NUllPointerException

- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/EventBotActionUtils.java
- webofneeds/won-node-webapp/src/main/resources/spring/node-context.xml
- webofneeds/won-node/src/main/resources/spring/component/broker/activemq.xml
fixed the property resolution - now setting properties via the environment for won-node-webapp is possible again
> Fix lost properties

- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-need/create-need.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/need-builder.js
- webofneeds/won-owner-webapp/src/main/webapp/jspm_config.js
Allows creating needs in the GUI, that use the new structure in the background. The need-type dropdown determines whether the is/seeks branches are present as follows:
* supply: is
* demand: seeks
* dotogether: both pointing to same node
* critique: both pointing to same node
> Need structure impl  need creation in gui

- webofneeds/won-owner-webapp/src/main/webapp/app/service/need-builder.js
> Added prefix for schema.org to fix rendering of geo-predicates.

- webofneeds/won-bot/pom.xml
- webofneeds/won-docker/pom.xml
- webofneeds/won-matcher-rescal/pom.xml
- webofneeds/won-matcher-service/pom.xml
- webofneeds/won-matcher-utils/pom.xml
- webofneeds/won-owner-webapp/pom.xml
- webofneeds/won-owner-webapp/src/main/webapp/gulpfile.js
- webofneeds/won-owner-webapp/src/main/webapp/index.html
Shrunk the owner warfile and added options for skipping lengthy operations. 
In addition to that, friendly messages were added to inform the user of the skip options.
> Feat smaller wars

- webofneeds/won-cryptography/src/main/java/won/cryptography/webid/springsecurity/ReverseProxyCompatibleX509AuthenticationFilter.java
Prior version could only parse the header as formatted by nginx, now also apache is supported.
> fixed parsing of X-Client-Certificate header

- webofneeds/won-bot/src/main/java/won/bot/framework/bot/base/FactoryBot.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/wonmessage/execCommand/ExecuteConnectionMessageCommandAction.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/behaviour/BotBehaviour.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/behaviour/BotBehaviourActivatedEvent.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/behaviour/BotBehaviourDeactivatedEvent.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/behaviour/BotBehaviourEvent.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/behaviour/BotBehaviourFailedEvent.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/behaviour/ConnectBehaviour.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/behaviour/ConnectBevahiour.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/behaviour/ConnectionMessageBehaviour.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/behaviour/CoordinationBehaviour.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/behaviour/FactoryBotHintBehaviour.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/behaviour/FactoryBotInitBehaviour.java
- webofneeds/won-core/src/main/java/won/protocol/util/NeedModelWrapper.java
implemented botbehaviour's
null check for parameterlists (needmodelwrapper)
> Botbehaviour

- webofneeds/won-owner-webapp/src/main/webapp/style/_matches-flow-item.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_matches-grid-item.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_overview-matches.scss
> Fix grid flow glitch #1076

- webofneeds/won-owner-webapp/src/main/webapp/app/components/feed-item.js
> Fix links in feed #1090

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/event-reducer.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer.js
- webofneeds/won-owner-webapp/src/main/webapp/app/selectors.js
- webofneeds/won-owner-webapp/src/main/webapp/app/utils.js
The message bot's connect message "Greetings! I am the DebugBot..." should now be visible in open chats and the incoming request tab *without* reloading the page (see #1091 for further details).
> Fix connect message #1091

- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-selection.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js
Chat should now correctly scroll down, when new chat messages arrive. Test this by e.g. tell the bot to send you a few messages via "send 3".
Resolves #1053
> Fix chat scrolling down #1053

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/connection-reducer.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/event-reducer.js
- webofneeds/won-owner-webapp/src/main/webapp/app/utils.js
> Fix request send status #1073

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-need/create-need.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/draft-builder.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/message-builder.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/need-builder.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/util-service.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/won.js
- webofneeds/won-owner-webapp/src/main/webapp/app/won-es6.js
- webofneeds/won-owner-webapp/src/main/webapp/app/won-message-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/gulpfile.js
* got the bundle down to 1.4MB from 4.7
* fixed a number of js bugs/uglinesses
* adapted won.js to export won
* fixed a number of missing variable declarations
> changed bundling to apply minification

- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js
> Hiding "show more" when connect-message is loaded.

- webofneeds/won-owner-webapp/src/main/webapp/app/components/landingpage/landingpage.js
> focuses email field when pressing the signup button on the landingpage

- documentation/protocol/message-references.md
- webofneeds/pom.xml
- webofneeds/won-core/pom.xml
- webofneeds/won-core/src/main/java/won/protocol/message/WonMessageUtils.java
- webofneeds/won-core/src/main/java/won/protocol/model/Connection.java
- webofneeds/won-core/src/main/java/won/protocol/model/ConnectionContainer.java
- webofneeds/won-core/src/main/java/won/protocol/model/EventContainer.java
- webofneeds/won-core/src/main/java/won/protocol/model/MessageEventPlaceholder.java
- webofneeds/won-core/src/main/java/won/protocol/model/parentaware/ParentAwareEventListenerIntegrator.java
- webofneeds/won-core/src/main/java/won/protocol/repository/MessageEventRepository.java
- webofneeds/won-core/src/main/java/won/protocol/util/NeedModelWrapper.java
- webofneeds/won-matcher-service/pom.xml
- webofneeds/won-matcher-service/src/main/java/won/matcher/service/crawler/actor/WorkerCrawlerActor.java
- webofneeds/won-matcher-solr/pom.xml
- webofneeds/won-node-webapp/pom.xml
- webofneeds/won-node/src/main/java/won/node/camel/processor/general/MessageReferencer.java
- webofneeds/won-node/src/main/java/won/node/camel/processor/general/ReferenceToUnreferencedMessageAddingProcessor.java
- webofneeds/won-node/src/main/java/won/node/camel/route/fixed/WonMessageRoutes.java
- webofneeds/won-node/src/main/resources/db/migration/V3_2__drop_unnecessary_table.sql
- webofneeds/won-node/src/main/resources/db/migration/V3_3__drop_unnecessary_table.sql
- webofneeds/won-node/src/main/resources/spring/component/camel/node-camel.xml
- webofneeds/won-owner-webapp/pom.xml
- webofneeds/won-owner/pom.xml
- webofneeds/won-owner/src/main/java/won/owner/model/User.java
- webofneeds/won-owner/src/main/resources/db/migration/V3_2__drop_unnecessary_table.sql
- webofneeds/won-owner/src/main/resources/db/migration/V3_3__drop_unnecessary_table.sql
improved and documented the message referencing rules
> Fix message references

- webofneeds/won-docker/image/nginx/nginx-int.conf
- webofneeds/won-docker/image/nginx/nginx-master.conf
- webofneeds/won-docker/image/nginx/nginx.conf
due to the recent spring update, the XSRF Token needs to be passed.
Fixes #1133
> Fix websocket behind nginx

- webofneeds/won-owner-webapp/src/main/webapp/app/components/accordion.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-selection-item.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-overview.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/feedback-grid.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/matches-grid-item.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/posttype-select.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/topnav.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/visitor-title-bar.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-messages.scss
fixes #1088 
list elements should have a consistent (hand) cursor now, to indicate that it is a clickable element
> added clickable handlers on some buttons that did not have it before

- webofneeds/won-owner-webapp/src/main/webapp/app/components/feed-item.js
fixes #1139
fixes the two broken links in the feed view
> fixed ui-sref

- webofneeds/won-owner/src/main/java/won/owner/messaging/OwnerProtocolCommunicationServiceImpl.java
Intended to make owner-node communication more resilient: If the node forgets about the owner, but the owner thinks it is registered, connecting on the JMS level fails.  With this PR, the owner tries to re-register when connecting fails.
Tried on integration-test by deleting the WoN nodes' trusted certificates, then restarting the nodes. Debug bot and owner webapp were able to re-register. 
Possibly fixes #1160 (but need to test by pushing to live)
> implemented re-registration upon connect failure

- webofneeds/won-matcher-service/src/main/resources/spring/component/matcher-service/transmission/matcher-security.xml
- webofneeds/won-node/src/main/java/won/node/camel/processor/fixed/CreateNeedMessageReactionProcessor.java
- webofneeds/won-owner-webapp/src/main/webapp/app/piwik.js
fixed a bug in the matcher config, allowing it to register with the node properly
also found a bug in the node that caused new need created notifications to be produced with incomplete data, preventing the solr matcher from producing matches
> Fix matcher cert alias

- webofneeds/won-core/src/main/java/won/cryptography/service/TrustStoreService.java
> added debug output to TrustStoreService

- documentation/piwik/README.md
- webofneeds/won-docker/deploy/live_satvm01/docker-compose.yml
- webofneeds/won-docker/image/nginx/nginx.conf
create and deploy docker piwik container (+ mysql)
this pull request does only work if deployed to live 
see: https://github.com/researchstudio-sat/webofneeds/tree/piwik-container/documentation/piwik
> Piwik container

- webofneeds/won-bot/src/main/java/won/bot/impl/LastSeenNeedsMatcherBot.java
- webofneeds/won-core/src/main/java/won/cryptography/service/RegistrationServerCertificateBased.java
- webofneeds/won-core/src/main/java/won/protocol/repository/OwnerApplicationRepository.java
- webofneeds/won-core/src/main/java/won/protocol/service/ApplicationManagementService.java
- webofneeds/won-node/src/main/java/won/node/camel/processor/fixed/OpenMessageFromNodeProcessor.java
- webofneeds/won-node/src/main/java/won/node/camel/processor/fixed/OpenMessageFromOwnerProcessor.java
- webofneeds/won-node/src/main/java/won/node/service/impl/OwnerManagementServiceImpl.java
- webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js
First fixing a race condition upon registering, then researching other strange behaviour, which seemed related. That turned out to be a bug in the handling of open messages.
> Fix db raceconditions

- webofneeds/won-docker/image/owner/ssl/server.xml
Also activates gzipping for the rdf mime-types.
> Added rdf mime-types to list of gzip-compressables.

- webofneeds/won-docker/image/owner/ssl/server.xml
- webofneeds/won-docker/image/wonnode/ssl/server.xml
Also turns on gzipping for the node, as recommended by @heikofriedrich [here](https://github.com/researchstudio-sat/webofneeds/issues/1198#issuecomment-329116686) :)
> Feat  gzip on node

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/create-need-action.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/cstm-router-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/toast-reducer.js
Redirect happens *before* need is added. Also the redirect tries to return to the previous view (if there is one and also depending on where the need was published).
> Feat  more responsive need create

- webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js
Simplified the query for needs in the owner webapp (client side)
> Fix needquery

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/topnav.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/toast-reducer.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/need-builder.js
fixes issue #1220 
fixes location need-builder typo
> Fix #1220 whatsaround disabled tracking

- webofneeds/won-owner-webapp/src/main/webapp/app/components/login-form.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/user-reducer.js
fixes #1239 (quick fix)
real fix of the cause has to follow in #1244
> Fix login reset

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/won.js
All messages exchanged in the connect/open back-and-forth should be shown in the chat to both sides.
Resolves #1241
> Fix reply message #1241

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/login-form.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/user-reducer.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/won.js
The issue that motivated the hack has been properly fixed by one of the FF/angular updates.
NOTE: merge after #1252.
Resolves  #1244
> Fix autofillhack #1244

- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js
- webofneeds/won-owner-webapp/src/main/webapp/jspm_config.js
- webofneeds/won-owner-webapp/src/main/webapp/package.json
- webofneeds/won-owner-webapp/src/main/webapp/style/_animate.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_create-post.scss
adds animations and more detail to the create-view
adds a new field for tag input (for users who dont know how to add tags via the description)
ability to remove details in order to remove the location/tags from the post (if the user chooses not to include them)
fixes #922 
fixes #1183
> Feat create post update

- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer.js
Now the remoteConnectionUri is stored on the sender side to close the connection on both sides.
> Fixes the closing connection bug - #1231

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/load-action.js
> load private id user data incrementally

- webofneeds/pom.xml
- webofneeds/won-owner-webapp/pom.xml
- webofneeds/won-owner-webapp/src/main/java/won/owner/web/WonOwnerMailSender.java
Prevents html injection through need titles, description, urls, messages.
fixes #1274
> Perform HTML escaping when generating mails

- webofneeds/won-owner-webapp/src/main/webapp/app/components/feedback-grid.js
Labels on feedback buttons (in the owner app -> matches -> grid view) now explain better what will happen if one clicks them
> Improve button labels

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/messaging-agent.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/toast-reducer.js
Solves #1305
Now the "ResponseToActivateMessage" is handled in case of a success and a failure
> Add handler for a "ResponseToActivateMessage"

- webofneeds/pom.xml
- webofneeds/won-core/pom.xml
- webofneeds/won-core/src/test/java/won/protocol/message/WonMessageValidatorTest.java
- webofneeds/won-core/src/test/java/won/protocol/util/NeedModelWarpperTest.java
- webofneeds/won-cryptography/src/test/java/won/cryptography/message/WonMessageSignerVerifierTest.java
- webofneeds/won-cryptography/src/test/java/won/cryptography/rdfsign/ModelConverterTest.java
- webofneeds/won-cryptography/src/test/java/won/cryptography/rdfsign/WonKeysReaderWriterTest.java
- webofneeds/won-cryptography/src/test/java/won/cryptography/rdfsign/WonSignerTest.java
- webofneeds/won-cryptography/src/test/java/won/cryptography/rdfsign/WonVerifierTest.java
it should be possible to build the whole project with "mvn install" instead of having to start with the skip-tests profile
> Fix buildwithtests

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js
Check the state of the need before sending hint.
issue #1271
(cherry picked from commit e394948)
> Avoid hint for inactive needs

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
> Fix closing need and connections #1303

- webofneeds/won-bot/src/main/java/won/bot/framework/bot/base/FactoryBot.java
- webofneeds/won-owner-webapp/src/main/webapp/app/components/square-image.js
fixes the broken view seen in the screen when a need with multiple titles is displayed
> Fix squareimage multiple title issue

- webofneeds/won-owner-webapp/src/main/webapp/app/components/overview-title-bar.js
issue #1324
Also used to test eclipse
> Refactor "Incoming Requests"

- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-need-title-bar.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/need-textfield.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_needtextfield.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_typeselect.scss
Minor changes to the wording of the owner webapp.
* change title of create view to `"Hello, everyone, ..."`
* change placeholder text in create view so it explains better what the create textview does
* change layout to make the textview bigger so it contains the longer placeholder nicely
Fixes #1340
> Fix gui wording

- webofneeds/won-core/src/main/java/won/protocol/rest/LinkedDataRestClient.java
- webofneeds/won-core/src/main/java/won/protocol/util/NeedModelWrapper.java
- webofneeds/won-matcher-service/src/main/java/won/matcher/service/crawler/actor/MasterCrawlerActor.java
- webofneeds/won-matcher-service/src/main/java/won/matcher/service/crawler/actor/WorkerCrawlerActor.java
- webofneeds/won-matcher-service/src/main/java/won/matcher/service/crawler/service/CrawlSparqlService.java
fixes some errors in the matcher crawling
> Fix matcher crawling

- webofneeds/won-owner-webapp/src/main/webapp/app/utils.js
- webofneeds/won-owner-webapp/src/main/webapp/jspm_config.js
- webofneeds/won-owner-webapp/src/main/webapp/package.json
issue #1345
If the openstreetmaps server is not reachable, or blocking a request,
the current location from the browser is taken to create a "what's
around" need and the boundingbox is computed with the "geopoint"
library, which is now included in the project.
> Improve geocoding and fix openstreetsmaps problem

- .gitignore
- webofneeds/won-docker/image/nginx/nginx-int.conf
- webofneeds/won-docker/image/nginx/nginx-master.conf
- webofneeds/won-docker/image/nginx/nginx.conf
- webofneeds/won-owner-webapp/pom.xml
- webofneeds/won-owner-webapp/src/main/java/won/owner/web/sitemap/SitemapController.java
- webofneeds/won-owner-webapp/src/main/java/won/owner/web/sitemap/SitemapService.java
- webofneeds/won-owner-webapp/src/main/resources/spring/owner-security.xml
- webofneeds/won-owner/pom.xml
Adds a Controller and Service to the owner-webapp that produces a
sitemap xml file upon each request to /owner/sitemap.xml. Also adds a
robots.txt file in-line for integration-test, master, and live
environments.
> Add simple sitemap.xml

- webofneeds/won-docker/image/nginx/nginx.conf
inline robots.txt for owner on port 80 was missing prior to this PR
> Add robots.txt on owner http

- webofneeds/won-node-webapp/src/main/resources/spring/node-context.xml
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/create-need-action.js
> Fix modifiedafterrequest

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/create-need-action.js
removed the bug as requested by @fkleedorfer
> fixes a bug that does not let the privateId be deleted from the params

- webofneeds/conf/node.properties
- webofneeds/won-core/src/main/java/won/protocol/repository/NeedRepository.java
- webofneeds/won-node/src/main/java/won/node/maintenance/NeedInactivityChecker.java
- webofneeds/won-node/src/main/resources/spring/component/maintenance/node-maintenance.xml
New config property defining an inactivity timeout after which needs are
closed, even if they have active connections
> Add need deactivation of connected abandoned needs

- webofneeds/won-core/src/main/java/won/protocol/message/WonMessageBuilder.java
- webofneeds/won-core/src/main/java/won/protocol/util/RdfUtils.java
- webofneeds/won-core/src/test/java/won/protocol/message/WonMessageBuilderTest.java
Allows for preparing a dataset in which graphs contain references to
each other, to be added as message content such that the references
remain intact.
> Add Dataset as message content

- webofneeds/won-owner-webapp/src/main/java/won/owner/web/rest/AgreementController.java
- webofneeds/won-owner-webapp/src/main/resources/spring/owner-security.xml
- webofneeds/won-owner/src/test/java/won/owner/repository/AgreementOwnerTest.java
- webofneeds/won-owner/src/test/resources/spring/owner-agreement-test.xml
- webofneeds/won-utils/won-utils-goals/src/main/java/won/protocol/highlevel/HighlevelProtocols.java
created rest service in owner to access high level agreement/proposal protocol functions.
merge owner high level protocol access back into proposal/agreement calculation code
@bshambaugh, you can merge this code if you need it
> Owner agreements

- webofneeds/won-core/src/main/java/won/protocol/util/NeedModelWrapper.java
- webofneeds/won-core/src/main/java/won/protocol/vocabulary/WON.java
- webofneeds/won-core/src/test/java/won/protocol/util/NeedModelWrapperTest.java
- webofneeds/won-core/src/test/resources/needmodel/need7.trig
- webofneeds/won-core/src/test/resources/needmodel/need8.trig
- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/feed-item.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/matches-flow-item.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/owner-title-bar.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-header.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-item-line.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/visitor-title-bar.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/need-builder.js
- webofneeds/won-owner-webapp/src/main/webapp/app/won-message-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/skin/current/config.json
- webofneeds/won-owner-webapp/src/main/webapp/skin/matchat/config.json
- webofneeds/won-owner-webapp/src/main/webapp/skin/uki/config.json
- webofneeds/won-vocab/src/main/resources/ontology/won_ontology_v1.0.ttl
New concept: matching context.
If a need has one or more matching contexts, it is only matched with other needs that have one of those contexts.
Adds a won:hasMatchingContext property to the need, a GUI to display/edit them, and utility methods to set/get them in the Java code. Matcher code to follow.
> Feat matching context

- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/signup/signup.html
- webofneeds/won-owner-webapp/src/main/webapp/style/_signup.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_slidein.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_text.scss
a bunch of small styling fixes.
ad testing: see commit msgs
> Fix smallskinningbugs

- webofneeds/won-matcher-service/src/main/java/won/matcher/service/nodemanager/actor/WonNodeControllerActor.java
dont start the crawling for already connected won nodes ervery time
> fix start crawling multiple times

- webofneeds/won-owner-webapp/src/main/webapp/style/_accordion.scss
> fixes "margin" skinning issues #1415

- webofneeds/pom.xml
Upgraded to a version that does not break the server but contains the
fix for https://issues.apache.org/jira/browse/AMQ-4366
How to test: 
First, without the fix, 
1. run node locally, 
2. start debug bot
3. stop debug bot
observe that the node crashes
Repeat with this PR -> should work now.
Fixes #1447
> Upgrade activemq version

- webofneeds/won-core/src/main/java/won/protocol/model/unread/UnreadMessageInfo.java
- webofneeds/won-core/src/main/java/won/protocol/model/unread/UnreadMessageInfoForConnection.java
- webofneeds/won-core/src/main/java/won/protocol/model/unread/UnreadMessageInfoForNeed.java
- webofneeds/won-core/src/main/java/won/protocol/repository/MessageEventRepository.java
- webofneeds/won-core/src/main/java/won/protocol/service/LinkedDataService.java
- webofneeds/won-core/src/main/java/won/protocol/service/impl/UnreadInformationService.java
- webofneeds/won-core/src/main/java/won/protocol/vocabulary/WON.java
- webofneeds/won-node-webapp/src/main/java/won/node/web/LinkedDataWebController.java
- webofneeds/won-node-webapp/src/main/resources/spring/node-context.xml
- webofneeds/won-node/src/main/java/won/node/service/impl/LinkedDataServiceImpl.java
- webofneeds/won-node/src/main/java/won/node/service/impl/URIService.java
- webofneeds/won-node/src/main/java/won/node/springsecurity/WonDefaultAccessControlRules.java
- webofneeds/won-node/src/main/resources/spring/core/node-core.xml
- webofneeds/won-owner-webapp/pom.xml
Adds a won node service  for obtaining information about unread messages
> Feat unread info

- webofneeds/won-docker/image/solr/core/won/conf/schema.xml
- webofneeds/won-matcher-solr/src/main/java/won/matcher/solr/query/DefaultMatcherQueryExecuter.java
- webofneeds/won-matcher-solr/src/main/java/won/matcher/solr/query/factory/BasicNeedQueryFactory.java
- webofneeds/won-matcher-solr/src/main/java/won/matcher/solr/query/factory/SolrQueryFactory.java
- webofneeds/won-matcher-solr/src/main/java/won/matcher/solr/query/factory/WhatsAroundQueryFactory.java
* do not use dummy query anymore for standard need queries to allow 0 results if query doesnt hit anything
* fix typo in solr field name of seeks.description and seeks.seeks.description
**NOTE:** if this pull request is deployed to live/uki the solr index has to be deleted there so that it can rebiuld
> Matching fix

- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/analyzation/AnalyzeAction.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/event/impl/analyzation/agreement/AgreementAcceptedEvent.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/event/impl/analyzation/agreement/AgreementCanceledEvent.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/event/impl/analyzation/agreement/AgreementErrorEvent.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/event/impl/analyzation/agreement/AgreementEvent.java
- webofneeds/won-core/src/main/java/won/protocol/util/WonRdfUtils.java
improved analyzeaction and updated agreementevent payload
> Feat analyzeaction agr prop

- webofneeds/won-core/src/main/java/won/protocol/util/RdfUtils.java
- webofneeds/won-core/src/main/java/won/protocol/util/SparqlSelectFunction.java
- webofneeds/won-owner-webapp/src/main/java/won/owner/web/rest/HighlevelProtocolsController.java
- webofneeds/won-utils/won-utils-conversation/src/main/java/won/protocol/highlevel/HighlevelProtocolAnalyzer.java
- webofneeds/won-utils/won-utils-conversation/src/main/java/won/protocol/highlevel/HighlevelProtocols.java
Bugfixes in jena transactions and extensions to highlevel protocol api
> Won utils conversation merge master

- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post/post.html
- webofneeds/won-owner-webapp/src/main/webapp/style/_chattextfield.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_connection-message.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-messages.scss
> Fix chat scaling #1452

- webofneeds/won-owner-webapp/src/main/webapp/app/components/feed-item-line.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/feed-item.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/feed/feed.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/feed/feed.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_feed-item.scss
adds animations when items get pushed in the state while the feed is visible (items appear/slide slowly, instead of just popping up)
> includes feed animations when items get added to the feed

- documentation/installation-cryptographic-keys-and-certificates.md
- documentation/troubleshooting.md
To test: check for clear explanations, complete information and lack of typos.
> Documentation - improve troubleshooting documentation

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-message.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/feed-item-line.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/feed-item.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/feed/feed.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/feed/feed.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_connection-message.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_feed-item.scss
marks messages that have been visible in the chat window as read (unread message counter decreases after a certain set time after initial visibility)
excluded ownMessages from being displayed as unread messages by default
> Feat setmessages read

- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/debugbot/DebugBotIncomingMessageToEventMappingAction.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/behaviour/CrawlConnectionDataBehaviour.java
- webofneeds/won-core/src/main/java/won/protocol/service/impl/WonNodeInformationServiceImpl.java
- webofneeds/won-core/src/main/java/won/protocol/util/linkeddata/CachingLinkedDataSource.java
- webofneeds/won-core/src/main/java/won/protocol/util/linkeddata/LinkedDataSourceBase.java
- webofneeds/won-core/src/main/java/won/protocol/util/linkeddata/WonLinkedDataUtils.java
- webofneeds/won-owner-webapp/src/main/java/won/owner/web/rest/AgreementProtocolController.java
- webofneeds/won-owner/src/main/java/won/owner/protocol/message/LinkedDataCacheInvalidator.java
- webofneeds/won-utils/won-utils-conversation/src/main/java/won/protocol/agreement/AgreementProtocolState.java
- webofneeds/won-utils/won-utils-conversation/src/main/java/won/protocol/util/WonConversationUtils.java
* Fixes the problem of exceptions when retrieving AgreementProtocol information in a conversation that was initiated by a hint; 
* makes debugbot and agreement data in GUI more responsive
> Improve debugbot agreementfunctions

- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-item-line.js
addition: add hover texts for some elements in the post-item-line
The Post Overview shows the number of conversations/chats that contain unread messages
> show the amount of chats that have unread messages

- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/debugbot/DebugBotIncomingMessageToEventMappingAction.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/debugbot/OpenConnectionDebugAction.java
- webofneeds/won-bot/src/main/java/won/bot/impl/DebugBot.java
- webofneeds/won-utils/won-utils-conversation/src/main/java/won/protocol/agreement/AgreementProtocolState.java
- webofneeds/won-utils/won-utils-conversation/src/main/java/won/protocol/agreement/effect/ProposalType.java
- webofneeds/won-utils/won-utils-conversation/src/main/java/won/protocol/agreement/effect/Proposes.java
- webofneeds/won-utils/won-utils-conversation/src/main/java/won/protocol/util/WonConversationUtils.java
* more intuitive commands concerning agreements
* additional commands interpreted when connecting (wait, deny, ignore)
> Improve debug bot

- webofneeds/won-owner-webapp/README.md
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-selection-item.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-selection.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/feedback-grid.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post/post.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/send-request.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_connection-selection-item-line.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_need-tab-bar.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-messages.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-owner.scss
fixes #1504 responsiveness breakpoint for mobile devices -> hides connectionList on small devices if a connection is open
moved "close connection" from connection-selection-item option to post-messages contextMenu
added a "Go To Post" button in the contextMenu of the post-messages window.
> Fix #1504 and contextmenu

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-overview.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/overview-incoming-requests/overview-incoming-requests.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/overview-incoming-requests/overview-incoming-requests.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/overview-title-bar.js
Merges the overview "Matches" and "Requests" tabs to a "Chats" tab to match the post detail view.
> Merge Overview Matches and Requests tabs

- webofneeds/won-owner-webapp/src/main/webapp/app/components/owner-title-bar.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_contextmenu.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-messages.scss
> Fix settings icon color

- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-indicators.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-selection-item.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-selection.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-state.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-overview.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/feed-item.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/feed/feed.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/landingpage/landingpage.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/open-request.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/overview-incoming-requests/overview-incoming-requests.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/overview-incoming-requests/overview-incoming-requests.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/overview-posts/overview-posts.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/overview-title-bar.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-item-line.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post/post.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post/post.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/send-request.js
- webofneeds/won-owner-webapp/src/main/webapp/app/utils.js
- webofneeds/won-owner-webapp/src/main/webapp/skin/current/config.css
- webofneeds/won-owner-webapp/src/main/webapp/skin/matchat/config.css
- webofneeds/won-owner-webapp/src/main/webapp/skin/uki/config.css
- webofneeds/won-owner-webapp/src/main/webapp/style/_connection-indicators.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_connection-selection-item-line.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_connections-overview.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_feed-item.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-item-line.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/won.scss
- use icons (conversations, requests, matches) in chats view
- when clicking on a connection type indicator on the own need (conversation/request/match), select a connection of that kind with unread messages, or the connection with the most recent activity
> Feat connindicators and clickhandler

- webofneeds/won-owner-webapp/src/main/webapp/app/components/matches.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/overview-incoming-requests/overview-incoming-requests.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-info.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post/post.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/send-request.js
- webofneeds/won-owner-webapp/src/main/webapp/app/configRouting.js
Changes visitor view - to test, check post visitor view and all places where won-send-requests is used.
> Feat update post visitor view

- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-info.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/send-request.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-info.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-messages.scss
> Fix  #1548

- webofneeds/won-owner-webapp/src/main/webapp/style/_create-need-title-bar.scss
Fixes #1570 
Should be revisited once #1562 is merged.
> Fixed border and speechbubble color.

- webofneeds/won-owner-webapp/src/main/webapp/app/components/post/post.js
> adds visitor title bar module (since it was missing)

- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-info.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/send-request.js
> fixed link in post-info and send-request

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js
> fixes #1566

- documentation/need-structure.md
describes how the RDF data constituing a need is structured  and interpreted
> need-structure.md

- webofneeds/won-owner-webapp/src/main/webapp/style/_signup-title-bar.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_signup.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_title-bar.scss
> Fix signup title bar styling issue.

- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-isseeks.js
- webofneeds/won-owner-webapp/src/main/webapp/app/utils.js
Need creation should work as normal. This is just a refactoring.
> Refac create isseeks tags

- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/send-request.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_connections-overview.scss
- Removes the Buttons that link directly to the last (unread) connection in the mobile view (connection indicators)
- Shorten the placeholder text in the request and reply message to make sure it will not result in a multi lined placeholder
> Fixes Some issues that occured during UserTest

- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-header.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-indicators.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-selection-item.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-overview.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_connection-header.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_connection-indicators.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_connection-selection-item-line.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_connections-overview.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_feed-item.scss
style connections-overview similar to how the feed used to look like
fixes #1621
> Feat connection overview style #1621

- webofneeds/won-owner-webapp/src/main/webapp/app/components/connections/connections.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-info.js
This fixes the issue that a empty view is displayed when the only present need of a user is a closed whats around need... this has been fixed and the empty view text is displayed correctly
> Fix faulty empty view

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/create-need-action.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/cstm-router-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/app_jspm.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connections/connections.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connections/connections.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/topnav.js
- webofneeds/won-owner-webapp/src/main/webapp/app/configRouting.js
- webofneeds/won-owner-webapp/src/main/webapp/app/sref-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_connections.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-messages.scss
This makes the create view obsolete by adding it to the connections view. Fixes #1607, fixes #1608 
When testing, pay attention to the layout in case anything is broken from adding a new button and verify that it's not possible to get to the old create view anymore.
> Feat add create to connections view

- webofneeds/won-owner-webapp/src/main/webapp/app/components/connections/connections.html
> missing parentheses in logic

- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-header.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer.js
> FIXES #1660  missing connection data

- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-info.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-is-info.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-seeks-info.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/visitor-title-bar.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-info.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-visitor.scss
fixes #1670 
fixes #1551
Also removes the back button within the header of a visitor link
> Fix visitorlink #1670 top border #1551

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-agreement.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js
- webofneeds/won-owner-webapp/src/main/webapp/app/messaging-agent.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer.js
- webofneeds/won-owner-webapp/src/main/webapp/app/won-message-utils.js
Use the isLoading value from the state + remove old unsused functions
Fixes #1524 
Resolve #1680
> Refac is loading

- webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-overview.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_connections-overview.scss
> include a simple loading indicator that is displayed as long as initialPageLoad is not finished yet

- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-header.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/send-request.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_connection-header.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_connection-indicators.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-header.scss
this pull request changes the visible information of the connection headers (subtitle is now the connection state instead of what the remoteneed is)
additionally i changed the layout to a grid and will ellipsize anything that overflows from the title (includes white space no wrap)
therefore all the headers will be the same height
> Feat style headers

- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/send-request.js
> fixes merge issues #1697

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-agreement.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-message.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js
Retract and reject in chat gui
Resolve #1501
Fixes #1509
Fixes #1691
> Add retract and reject #1501

- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-header.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/square-image.js
- webofneeds/won-owner-webapp/src/main/webapp/app/utils.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_connection-agreement.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_connection-header.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_connection-message.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_connection-selection-item-line.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_matches-flow-item.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_need-tab-bar.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-header.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_square-image.scss
updates the connection-headers so that they differ more from a need-header (by almost diagonally cutting the icons)
> Feat better connectionheadericons

- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-isseeks.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/location-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_create-isseeks.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_locationpicker.scss
Changed detail picker so only one detail can be added at a time and changed location picker to show the picked location when opened again.
> Changed detail and location picker behaviour

- webofneeds/won-owner-webapp/src/main/webapp/app/components/extended-connection-indicators.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_connection-selection-item-line.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_connections-overview.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_extended-connection-indicators.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_won-config.scss
fixes #1713 
-set responsivenessthreshold to have the max-content-width
-remove display: flex from some item (not needed any longer)
> Fix captions #1713

- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-context-dropdown.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-overview.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-context-dropdown.js
> changing labels of close buttons to be less misleading

- webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-overview.js
> Reintroduce the show post detail button for closed/archived needs

- documentation/svg-icon-creation.md
Check for typos/unclear instructions.
> Documentation: How to create new SVG icons

- .gitignore
- webofneeds/won-owner-webapp/pom.xml
- webofneeds/won-owner-webapp/src/main/webapp/package-lock.json
- webofneeds/won-owner-webapp/src/main/webapp/package.json
Improves performance significantly and fixes a few bugs.
Blocked by #1743
> Bump webpack

- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-isseeks.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/location-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/images/won-icons/ico36_location_current.svg
- webofneeds/won-owner-webapp/src/main/webapp/style/_border-utils.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_create-isseeks.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_locationpicker.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/won.scss
Fixes #920, Fixes #1637 
Known limitation: only found locations can be picked, location names can't be manually shortened
> Style location picker

- webofneeds/won-owner-webapp/README.md
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer.js
Resolve #1726
Optimize loading process.
Hide agreementDataPanel if new agreementMessages comes in.
Clear and filter agreementData in state.
Update README.md.
Remove unused code
> Refac add agreement data to state #1726

- webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-overview.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_connection-header.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_connection-indicators.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_connections.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-header.scss
fixes the "jumping" columns by also abbreviating the subtitle in favor of breaking into multiple lines
fixes #1729
> Fix jumping columns #1729

- webofneeds/won-owner-webapp/src/main/webapp/style/_context-dropdown.scss
> adds vertical padding to the dropdown icon (if opened)

- webofneeds/won-owner-webapp/src/main/webapp/package-lock.json
- webofneeds/won-owner-webapp/src/main/webapp/package.json
The lockfile contained old sha1 checksums. Also, it was autoformatted by prettier, which is not very useful because it will be autogenerated with its own style every time.
> Fix  wrong lockfile

- webofneeds/won-core/src/main/java/won/protocol/vocabulary/WON.java
- webofneeds/won-node/src/main/java/won/node/service/impl/LinkedDataServiceImpl.java
* link sysinfo graph to need via rdfg:subGraphOf
* link need to content graphs via won:hasContent
* un-deprecate won:hasContent for use here
> Make need content graphs easier to find

- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-message.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-is-info.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-seeks-info.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_connection-message.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-info.scss
fixes #1782 
fixes #1781 
blocked by #1783
> Fix  workaround newline bug #1782

- documentation/build-with-eclipse.md
> Update build with eclipse.md #1793

- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-isseeks.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-is-info.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-seeks-info.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/tags-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/ttl-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/index.html
- webofneeds/won-owner-webapp/src/main/webapp/style/_create-isseeks.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_locationpicker.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-info.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_tagspicker.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_textfield.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_ttlpicker.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_won-config.scss
Includes changes from #1792 
Moved TTL picker to own component.
> Refac  add ttl picker component

- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-agreement.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-message.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer.js
The headers and the text of the accept messages change to:
- "Accept proposal"
- "Accept cancel"
And the shown text is the text of the proposal
Resolve #1798
> Refac change text in accept message #1798

- webofneeds/won-owner-webapp/src/main/java/won/owner/web/rest/BridgeForLinkedDataController.java
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/about/about.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-message.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-share-link.js
- webofneeds/won-owner-webapp/src/main/webapp/app/messaging-agent.js
- webofneeds/won-owner-webapp/src/main/webapp/app/piwik.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js
- webofneeds/won-owner-webapp/src/main/webapp/app/utils.js
- webofneeds/won-owner-webapp/src/main/webapp/app/won-message-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/app/won-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/config/default.js
- webofneeds/won-owner-webapp/src/main/webapp/config/live.js
- webofneeds/won-owner-webapp/src/main/webapp/package-lock.json
- webofneeds/won-owner-webapp/src/main/webapp/package.json
It's not drop-in confable like the skin-folder, but I wanted to avoid introducing another round-trip to the page load and keep the application statically servable.
Note: can't properly test this, as my setup's fubar atm. The work for this PR was an attempt to circumvent this by using an alternative owner-server like integration-testing.
> Made base-uri confable via default.js and live.js

- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-context-dropdown.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-overview.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_connections.scss
> Fix overflow #1757

- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer.js
> change the location retrieval to use fully qualified names

- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-message.js
> Quickfix raw message bug

- documentation/future_work/feature-requests.md
- documentation/future_work/refactoring.md
Adds a documentation folder intended for collecting all sorts of ideas that could improve WoN.
> Add future work documentation stub

- webofneeds/won-owner-webapp/src/main/webapp/app/components/logged-in-menu.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/signup/signup.html
> Change "Transfer Account" to "Keep Postings"

- webofneeds/won-owner-webapp/src/main/webapp/app/components/connections/connections.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connections/connections.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_create-post.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-info.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-messages.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_won-config.scss
This does quickfix the problem in the chat-view.
The keyboard problem for the other views will be fixed in a seperate pull request.
Part of #1625
> Quickfix mobile view input #1625

- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-isseeks.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-info.js
Separate pullrequest because this is completely unrelated to the branch I'm currently working on. 
Only removes a now unneeded debug output that was overlooked in an earlier pull request.
> Removed debug output.

- webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-overview.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-header.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_connections-overview.scss
fixes #1879 
fixes #1880 -> without the border removal
> Fix tooltip improve needview includes #1880 #1879

- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-selection-item.js
Forgot to fix this before merging #1865
> Quick fix html closing tag

- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-isseeks.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/logged-in-menu.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/topnav.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_button.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_create-isseeks.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_create-post.scss
> Quick fix input #1625

- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js
fixes #1898 
also removes logoutput from linkeddata-service to have less verbose logging (not necessary anymore)
> Fix incompleteneeddata and logoutput #1898

- webofneeds/won-docker/deploy_uki.sh
this branch is for completeness, this is already deployed at uki
> Feat debug output uki

- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-agreement.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-message.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_connection-agreement.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_connection-message.scss
Now the buttons are on the same line again
Fix #1900
> Refac agreement buttons #1900

- webofneeds/won-owner-webapp/src/main/webapp/app/won-utils.js
fixes the encoding problem on login, i only added the charset within the login fetch as it seems all the other calls worked before anyway (register and transfer pushed the correct string as is)
fixes #1916
> fixes umlaut issue in password and email

- webofneeds/won-owner-webapp/src/main/webapp/style/_slidein.scss
> Made text of large slide-ins scrollable.

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/account-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/create-need-action.js
Fixes  #1914 
Also incidentally fixes #1892
> Check and refresh login when reconnecting.

- webofneeds/won-owner-webapp/src/main/webapp/app/components/about/about.js
Remove 'do I have to register?' question
> Update FAQ on about page

- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/matching-context-picker.js
> Improve matching context picker

- webofneeds/won-matcher-solr/src/main/java/won/matcher/solr/actor/SolrMatcherActor.java
* combine WhatsAround and WhatsNew with OR not (implicitly) with AND
> Fix missing hints for WhatsX

- webofneeds/won-docker/deploy/uki_satvm06/docker-compose.yml
- webofneeds/won-docker/image/nginx/nginx-uki-http.conf
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/account-actions.js
removes the ssl_verify_client optional from the nginx conf for meicogsci.matchat.org, and switch the connected node to node.matchat.org
thus ensuring that the user will not see a popup request to provide a certificate
> Fix meicogsci node

- webofneeds/won-owner-webapp/src/main/webapp/app/components/topnav.js
> Show Sign Up button for all screen widths

- webofneeds/won-owner-webapp/src/main/webapp/app/components/signup/signup.html
Add target="_blank" to link -> opens in new tab/window.
Closes #1967
> Quickfix #1967

- webofneeds/won-owner-webapp/src/main/webapp/app/components/account-menu.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/logged-in-menu.js
- webofneeds/won-owner-webapp/src/main/webapp/app/selectors.js
> Not showing private account name in account menu anymore.

- webofneeds/won-matcher-sparql/src/main/java/won/matcher/sparql/actor/SparqlMatcherActor.java
Fixes #1707 
It still doesn't respect testing flags.
> Sparql matcher now respects hint flags

- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-isseeks.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js
Better scroll behavoir on mobile devices to see input fields better.
Note: As we think about refactoring the create-post-view, this issue can be closed with this PR and the new view optimized again.
Closes #1625
> Refac scrolling in create post #1625

- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/behaviour/AnalyzeBehaviour.java
- webofneeds/won-core/src/main/java/won/protocol/util/NeedModelWrapper.java
Fixed #2006 
Take the Shapes graph and the data graph and create Strings of those statements. Order them in Array and calculate the SHA-256 Hash of this sorted array. Convert the hash to base64 and return it.
> Fixed #2006 getUniqueGoalId try 2

- webofneeds/won-owner-webapp/src/main/webapp/app/components/send-request.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/reduce-connections.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/reduce-needs.js
- webofneeds/won-owner-webapp/src/main/webapp/app/won-message-utils.js
fixes #1998 (the visitor link was always in loading if it was a non owned post, now the post is displayed correctly)
removed or replaced some verbose logging
> Fix visitor link #1998

- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-info.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-is-or-seeks-info.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/parse-need.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/need-builder.js
Resolves #1977 
Resolves #1980
> Adapt rdf created for search #1977

- webofneeds/won-matcher-sparql/src/main/java/won/matcher/sparql/actor/SparqlMatcherActor.java
Fixes #1978 (at least for the sparql matcher).
> Added support for won:hasSearchString

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-header.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-header.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/parse-need.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/need-builder.js
- webofneeds/won-owner-webapp/src/main/webapp/app/won-label-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/package-lock.json
- webofneeds/won-owner-webapp/src/main/webapp/style/_connection-header.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_connections-overview.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-header.scss
1. create post, but don't enter a title. instead enter abitrary rdf (e.g. `<_:isNeedContent> dc:description "hello world!".`)
2. copy the share-link for the need and open it in another browser
3. make an ad hoc connection.
4. neither the original need nor the ad-hoc need should have a title. the entire view should look like this: ![](https://user-images.githubusercontent.com/1730492/41673399-1fbdc9f6-74bd-11e8-97b8-b24b5d928edd.png)
> Feat  optional title

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/feedback-grid.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/message-reducers.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/need-reducer-main.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/reduce-connections.js
- webofneeds/won-owner-webapp/src/main/webapp/app/selectors.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_create-isseeks.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_feedback-grid.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_signup.scss
1. open need and get matches
2. make a request to one of those -- it should work as usual (side-benefit of PR: we're now actually sending rating messages to the servers)
3. kill you owner server, the client should lose connection
4. try to request a connection to another match -- the buttons should be greyed out.
Resolves #1987
> Fix  disabled rate btn on disconnect  #1987

- webofneeds/won-owner-webapp/src/main/webapp/config/detail-definitions.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecase-definitions.js
Adds config files containing definitions for use cases and details. No code changes, structure may change as usecases get implemented.
Fixes #2022, Fixes #2023
> Feat  detail usecase definitions  #2022 #2023

- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/tags-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/app/utils.js
> Tag picker no longer requires # symbols.

- webofneeds/won-vocab/src/main/resources/ontology/won_ontology_v1.0.ttl
* Add two properties to allow restricting matching to a time interval
* change occurrences of xsd:dateTimeStamp to xsd:dateTime in the ontology
> Feat do not match before after

- webofneeds/won-matcher-sparql/src/main/java/won/matcher/sparql/actor/SparqlMatcherActor.java
Fixes #1974 
Requires #1973 for testing properly.
> Added relevant time matching

- webofneeds/won-owner-webapp/src/main/webapp/app/components/connections/connections.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connections/connections.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-isseeks.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post-item.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/usecase-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/app/configRouting.js
- webofneeds/won-owner-webapp/src/main/webapp/config/detail-definitions.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecase-definitions.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_connections.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_usecase-picker.scss
- webofneeds/won-owner-webapp/src/main/webapp/webpack.config.ts
this branch was branched off of feat_usecasepicker the PR #2051 was closed and will be integrated in master within this branch
Fixes #2024
> Feat detaillist for create isseeks

- webofneeds/won-matcher-sparql/src/main/java/won/matcher/sparql/actor/SparqlMatcherActor.java
It is now in line with the need creation in the client again.
> Moved hasSearchString checking to root of need

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/create-need-action.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/need-builder.js
Default matching context should work again. Fixes #2070 
Also fixes a wrong import statement.
> Fix  #2070

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/account-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/create-need-action.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connections/connections.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connections/connections.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-info.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/send-request.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/usecase-picker-content.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/usecase-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/need-builder.js
- webofneeds/won-owner-webapp/src/main/webapp/skin/blue/config.json
- webofneeds/won-owner-webapp/src/main/webapp/skin/blue/welcomeTemplate.html
- webofneeds/won-owner-webapp/src/main/webapp/skin/current/config.json
- webofneeds/won-owner-webapp/src/main/webapp/skin/current/welcomeTemplate.html
- webofneeds/won-owner-webapp/src/main/webapp/skin/green/config.json
- webofneeds/won-owner-webapp/src/main/webapp/skin/green/welcomeTemplate.html
- webofneeds/won-owner-webapp/src/main/webapp/skin/matchat/config.json
- webofneeds/won-owner-webapp/src/main/webapp/skin/matchat/welcomeTemplate.html
- webofneeds/won-owner-webapp/src/main/webapp/skin/uki/config.json
- webofneeds/won-owner-webapp/src/main/webapp/skin/uki/welcomeTemplate.html
- webofneeds/won-owner-webapp/src/main/webapp/style/_connections.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_usecase-picker-content.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_usecase-picker.scss
Made a welcome page out of the "no element selected" right hand side
-displayed on desktop: whenever nothing is selected from the left side
-displayed on mobile: whenever no Own Needs are present
-also removes the auto creation of the whatsX needs
-introduces two buttons on the welcome-page that you can create a whatsaround or a whatsnew (closes all preexisting whats arounds)
-adds welcomeTemplate to the skin to create the ability to skin a welcomeText (text for skins still pending)
fixes #2077
> Feat improve first visit #2077

- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-isseeks.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js
before: 
after:
Resolves #2081
> Made labels in custom post more user friendly.

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/account-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/load-action.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-overview.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/topnav.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/message-reducers.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/need-reducer-main.js
- webofneeds/won-owner-webapp/src/main/webapp/app/selectors.js
- webofneeds/won-owner-webapp/src/main/webapp/app/won-message-utils.js
> Fix  check for new cncts after reconnect  #2066

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/create-need-action.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-overview.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connections/connections.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connections/connections.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post-item.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/topnav.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/usecase-picker-content.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/usecase-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/app/configRouting.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecase-definitions.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_connections.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_create-post-item.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_usecase-picker-content.scss
blocked by #2092  (includes commits of that pr as well)
fixes #2085
> Feat stickyusecases #2085

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/create-need-action.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-overview.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connections/connections.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connections/connections.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post-item.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/topnav.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/usecase-picker-content.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/usecase-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/app/configRouting.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_connections.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_usecase-picker-content.scss
fixes #2089 
also refactors the showCreateView url parameter (values are strings) to the showUseCases: bool parameter
> Feat whatsx #2089

- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-context-dropdown.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-overview.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post-item.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-context-dropdown.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-info.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-is-or-seeks-info.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/send-request.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_usecase-picker-content.scss
- usecase button label and icons are centered now
- selected usecase is also spanning the whole width instead of getting cut off
> added two minor style changes, fix being stuck on usecase, fixed display of post-info in suggested posts

- webofneeds/won-owner-webapp/src/main/webapp/index.html
Apparently also fixed styling of `index.html`
> Fixed viewport meta tag to reduce click delays and disable tap-to-zoom

- webofneeds/won-owner-webapp/src/main/webapp/images/won-icons/ico36_title_circle.svg
- webofneeds/won-owner-webapp/src/main/webapp/images/won-icons/ico36_uc_consortium-search.svg
> Add title icon

- webofneeds/won-owner-webapp/src/main/webapp/style/_usecase-picker.scss
This fixes the display bugs in mobile safari.
*We should **really** clean up our dom*
fixes #2109
> Added hack to make usecase buttons render in their own layer.

- webofneeds/won-owner-webapp/src/main/webapp/style/_slidein.scss
> Added fallbacks for older browser and switched height to vh

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-context-dropdown.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-header.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-selection-item.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/logged-in-menu.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/combined-message-content.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/connection-message-status.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/connection-message.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/message-content.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/referenced-message-content.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-context-dropdown.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-header.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_animate.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_combined-message-content.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_connection-header.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_connection-message.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_connection-selection-item-line.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_connections-overview.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-header.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-messages.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_referenced-message-content.scss
changes the styling of the connection and post header so we see more of the title, also moved the unreadmessage indicator to be visible instead of the connection type
blocked by #2132
> Feat restyle connpost header

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-context-dropdown.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/logged-in-menu.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/combined-message-content.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/connection-message-status.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/connection-message.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/message-content.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/referenced-message-content.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-context-dropdown.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_animate.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_combined-message-content.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_connection-message.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_connections-overview.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-messages.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_referenced-message-content.scss
fixes #1105 (indicator for unread messages when chat is not snapped to bottom, or in agreement view)
fixes #2031 (proposal view gets closed when messages come in)
also implemented cascading of referenced messages, to see the full content of the referenced message
> Feat combined message content master

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-context-dropdown.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-header.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-selection-item.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/logged-in-menu.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/combined-message-content.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/connection-message-status.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/connection-message.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/message-content.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/referenced-message-content.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-context-dropdown.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-header.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js
- webofneeds/won-owner-webapp/src/main/webapp/app/messaging-agent.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/need-reducer-main.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_animate.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_combined-message-content.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_connection-header.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_connection-message.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_connection-selection-item-line.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_connections-overview.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-header.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-messages.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_referenced-message-content.scss
implements the ability to load messages that are not in the state yet but seem to be visible in a proposal by clicking on the message
blocked by #2134
fixes #2135
how to test:
1) write quite alot of messages with debugbot (usually send 9 /send 9/usage should suffice)
2) go to the your first message and select propose
3) go to the debugbots first message and select propose as well
4) type propose any 5 and wait for all the proposal by the bot
5) reload the page
6) you should see approx. the last 15msgs now
7) the agreements/proposals might show a "message not loaded"-text
8) click on all of these messages
9) if you have received all the messages the pr is ok... just be sure its proposals of both sent and received msgs
> Feat loadmsgonclick

- webofneeds/conf/matcher-sparql/matcher-sparql.properties
- webofneeds/won-docker/deploy/int_satvm05/docker-compose.yml
- webofneeds/won-docker/deploy/live_satvm01/docker-compose.yml
- webofneeds/won-docker/deploy/local/docker-compose.yml
- webofneeds/won-docker/deploy/master_satvm02/docker-compose.yml
- webofneeds/won-docker/deploy/uki_satvm06/docker-compose.yml
- webofneeds/won-matcher-sparql/pom.xml
- webofneeds/won-matcher-sparql/src/main/java/won/matcher/sparql/actor/SparqlMatcherActor.java
- webofneeds/won-matcher-sparql/src/main/java/won/matcher/sparql/config/SparqlMatcherConfig.java
- webofneeds/won-matcher-sparql/src/main/java/won/matcher/sparql/spring/MatcherSparqlAppConfiguration.java
- webofneeds/won-matcher-sparql/src/main/resources/matcher-sparql-ehcache.xml
- webofneeds/won-matcher-sparql/src/main/resources/matcher-sparql-security.xml
> Only produce match if matching context found.

- webofneeds/won-owner-webapp/src/main/webapp/config/usecase-definitions.js
Add use case definitions for renting real estate. Related to #1817
> Real estate use case definition

- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/number-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_numberpicker.scss
> fixes #2155

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/account-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/message-reducers.js
Test:
1. set breakpoint to `messaging-agent.js:425`
2. create need without being logged in
3. connect from another need and chat a bit -- the messages should arrive properly (i.e. the websocket is working as intended)
4. logout
The app should reset the websocket during login and logout and thus trigger the break-point. If you have redux-devtools you can check that no reconnect-actions are dispatched.
> Triggering ws-reset on normal login/logout actions instead of dispatching `reconnect__start`.

- webofneeds/won-matcher-sparql/src/main/java/won/matcher/sparql/actor/SparqlMatcherActor.java
> Checking if need fragments are empty before querying.

- webofneeds/won-owner-webapp/src/main/webapp/style-demo.html
Build and then go to <https://localhost:8443/owner/style-demo.html>. You should see a page demo'ing a button.
> Feat  style demo

- webofneeds/won-owner-webapp/src/main/webapp/style-demo.html
Makes centering a bit cleaner and styles the code-blocks a bit.
> Fix  style of style demo

- webofneeds/won-owner-webapp/src/main/webapp/app/service/need-builder.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecase-definitions.js
- webofneeds/won-owner-webapp/src/main/webapp/package-lock.json
- webofneeds/won-owner-webapp/src/main/webapp/package.json
Resolves #2170 
1. Check out the branch
2. Run `npm install` to install the new `sparqljs` dependency
3. Add a `queryGenerator` to a usecase definition
e.g. apply [this diff](https://gist.githubusercontent.com/peacememories/27a2bcaad0817fdc627678527dcc760e/raw/7afe78dfa061f2f8f9589027aaf269839a5d546e/usecasetest.diff)
```
$ curl https://gist.githubusercontent.com/peacememories/27a2bcaad0817fdc627678527dcc760e/raw/7afe78dfa061f2f8f9589027aaf269839a5d546e/usecasetest.diff | git apply -v
```
4. Create a need with the usecase (in the case of the example a breakfast need)
5. Observe that the created need has a `won:hasQuery` attached at the root
> Feat  create sparql queries #2170

- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/number-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/range-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/select-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/viewer/range-viewer.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/viewer/select-viewer.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-is-or-seeks-info.js
- webofneeds/won-owner-webapp/src/main/webapp/config/detail-definitions.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecase-definitions.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_create-isseeks.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-is-or-seeks-info.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_range-viewer.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_rangepicker.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_select-viewer.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_selectpicker.scss
fixes #2181 (preliminary work until so we can create the sparql query within the usecase definition)
two new abstract pickers/types:
range-picker -> min-max number picker
select-picker -> either with multiselect (checkbox) or single select (radio)
these should be testable within the testpicker usecase (which we can remove after this is done)
> Feat newpickertypes #2181

- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/description-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/matching-context-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/number-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/person-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/range-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/tags-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/title-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/ttl-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/app/directives/input.js
> Replaced keyup listeners with won-input

- webofneeds/won-owner-webapp/src/main/webapp/images/won-icons/ico36_added_circle.svg
- webofneeds/won-owner-webapp/src/main/webapp/images/won-icons/ico36_area_circle.svg
- webofneeds/won-owner-webapp/src/main/webapp/images/won-icons/ico36_close_circle.svg
- webofneeds/won-owner-webapp/src/main/webapp/images/won-icons/ico36_description_circle.svg
- webofneeds/won-owner-webapp/src/main/webapp/images/won-icons/ico36_location_circle.svg
- webofneeds/won-owner-webapp/src/main/webapp/images/won-icons/ico36_media_circle.svg
- webofneeds/won-owner-webapp/src/main/webapp/images/won-icons/ico36_notification_circle.svg
- webofneeds/won-owner-webapp/src/main/webapp/images/won-icons/ico36_plus_circle.svg
- webofneeds/won-owner-webapp/src/main/webapp/images/won-icons/ico36_rdf_logo.svg
- webofneeds/won-owner-webapp/src/main/webapp/images/won-icons/ico36_rdf_logo_circle.svg
- webofneeds/won-owner-webapp/src/main/webapp/images/won-icons/ico36_tags_circle.svg
- webofneeds/won-owner-webapp/src/main/webapp/images/won-icons/ico36_time_circle.svg
In addition to that:
* made RDF icon in circle a little stronger
* increased size of RDF icon without circle (shown in user menu)
Closes #2211
> Remove white fill from circle icons

- webofneeds/won-owner-webapp/src/main/webapp/app/service/need-builder.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecase-definitions.js
- real estate pricerange detail replaced the pricedetail in the search for place to rent usecase
- additional failsafe in need-builder (do not replace already present key and log if the detail with the key would have had a value)
> Feat realestatepricerange seeks detail

- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-isseeks.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-search.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_create-isseeks.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_create-post.scss
fixes #2207 is also preliminary work for further tune matching things, and for further humanReadable detail parsing
> Feat restyle createdetails

- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-isseeks.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-search.js
- webofneeds/won-owner-webapp/src/main/webapp/config/detail-definitions.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecase-definitions.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_create-isseeks.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_create-post.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_matching-contextpicker.scss
adds the generateHumanReadable function within all details
this function parses the detail to a readable string
- this string is currently visible as an indicator which content is set behind each detail
- this string will be used to parse a title for a need in the future
How to Test:
1) create a costum post
2) add random values
3) see that the random value is displayed once you close the detail again
4) Create from a use case with set values
5) see that preset values are already visible
X) location, travelAction, rentRange Picker, tag picker, and person, have a combined representation based on the given values, for example:
a person with a title and a name and company and position will display something like: "Dr. Who works at ChocolateFactory as a Neurosurgeon"
whereas the same person …
> Feat create content in detail header

- webofneeds/won-owner-webapp/src/main/webapp/config/usecase-definitions.js
fixes #2225 
also fixes the problem that if either min or max is not present the post-info would show a "Map{type=xsd:float}" string instead of hiding the element itself
> fixes #2225

- webofneeds/won-owner-webapp/src/main/webapp/config/usecase-definitions.js
adds the height to the transport something
fixes #2222
> fixes missing dimension #2222

- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/need-builder.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/won.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecase-definitions.js
- webofneeds/won-owner-webapp/src/main/webapp/package-lock.json
- webofneeds/won-owner-webapp/src/main/webapp/package.json
Look at `usecase-definitions.js:855`, that's how the types are declared. Atm this is demoed with the "search rent" use-case.
Create a need using that use-case. It should have an `rdf:type`/`@type`/`a` triple in it's is- and seeks-nodes.
Resolves #2084
> Feat  type in use cases

- webofneeds/won-owner-webapp/src/main/webapp/package-lock.json
- webofneeds/won-owner-webapp/src/main/webapp/package.json
This removes a few warnings and inconsistencies.
> Bumped webpack plugin versions

- webofneeds/won-utils/won-utils-import/src/main/java/won/utils/im/port/RealEstateNeedGenerator.java
- webofneeds/won-utils/won-utils-import/src/main/java/won/utils/im/port/TaxiDemandNeedGenerator.java
- webofneeds/won-utils/won-utils-import/src/main/java/won/utils/im/port/TransportOfferNeedGenerator.java
Adds java generators for real estate offers, transport offers and taxi demands. 
Fixes #2150 
Fixes #2183 
Needs can be imported with the rdf-import-bot.
> Feat sample need generation

- webofneeds/pom.xml
- webofneeds/won-bot/pom.xml
- webofneeds/won-core/pom.xml
- webofneeds/won-cryptography/pom.xml
- webofneeds/won-docker/pom.xml
- webofneeds/won-facets/pom.xml
- webofneeds/won-facets/won-facets-tx/pom.xml
- webofneeds/won-matcher-rescal/pom.xml
- webofneeds/won-matcher-service/pom.xml
- webofneeds/won-matcher-solr/pom.xml
- webofneeds/won-matcher-sparql/pom.xml
- webofneeds/won-matcher-utils/pom.xml
- webofneeds/won-matcher/pom.xml
- webofneeds/won-node-webapp/pom.xml
- webofneeds/won-node/pom.xml
- webofneeds/won-ontology-validator/pom.xml
- webofneeds/won-owner-webapp/pom.xml
- webofneeds/won-owner/pom.xml
- webofneeds/won-utils/pom.xml
- webofneeds/won-utils/won-utils-conversation/pom.xml
- webofneeds/won-utils/won-utils-crawl/pom.xml
- webofneeds/won-utils/won-utils-goals/pom.xml
- webofneeds/won-utils/won-utils-import/pom.xml
- webofneeds/won-utils/won-utils-mail/pom.xml
- webofneeds/won-vocab/pom.xml
Release the project to Maven Central.
> Feat release 0.2

- webofneeds/conf/node.properties
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/counter/CounterImpl.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/trigger/AddFiringsAction.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/trigger/BotTrigger.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/trigger/FireCountLimitedBotTrigger.java
- webofneeds/won-core/src/main/java/won/protocol/repository/ConnectionRepository.java
- webofneeds/won-core/src/main/java/won/protocol/rest/LinkedDataRestClientHttps.java
- webofneeds/won-docker/deploy/int_satvm05/docker-compose.yml
- webofneeds/won-matcher-service/src/main/java/won/matcher/service/nodemanager/config/ActiveMqWonNodeConnectionFactory.java
- webofneeds/won-node/src/main/java/won/node/camel/processor/fixed/HintMessageProcessor.java
- webofneeds/won-node/src/main/resources/spring/component/broker/activemq.xml
Better performance in the face of a fast uploader and a generous matcher
> Feat reduce hint count

- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/petrinet-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/viewer/petrinet-viewer.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/message-content.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-is-or-seeks-info.js
- webofneeds/won-owner-webapp/src/main/webapp/config/detail-definitions.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_petrinet-viewer.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_petrinetpicker.scss
fixes #2294 
instead of updating the workflow picker, i have decided to generate a new detail for the upload of petrinets, this is just a quick implementation without any failsafes for correctness of the uploaded (petrinet)-file, it works just like the normal file-picker detail but only lets you upload one specific file.
this should be enough for us to implement the backend side of the workflow process, anything else can or should be dealt with in the future
> new quick petrinetviewer/picker (similar to file-picker)

- webofneeds/won-owner-webapp/src/main/webapp/app/won-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecase-definitions.js
1. create a real-estate need with amenity features
2. look at the trig, it should contain something like below
3. check if the features are shown in the post-detail-view
```ttl
s:amenityFeature [ 
a s:LocationFeatureSpecification ;
s:value "Garden"^^s:Text
] ;
s:amenityFeature [ 
a s:LocationFeatureSpecification ;
s:value "Elevator"^^s:Text
] ;
s:amenityFeature [ 
a s:LocationFeatureSpecification ;
s:value "Dishwasher"^^s:Text
]
```
Resolves  #2297
> Fix  amenity features  #2297

- webofneeds/won-owner-webapp/src/main/webapp/app/utils.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecase-definitions.js
Musicians can now search for reahearsal rooms to rent and offer them as well
Resolves #2317
> Add rehearsal search and offer #2317

- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/debugbot/DebugBotIncomingMessageToEventMappingAction.java
- webofneeds/won-owner-webapp/src/main/webapp/app/components/chat-textfield-simple.js
- webofneeds/won-owner-webapp/src/main/webapp/config/detail-definitions.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecase-definitions.js
fixes the detail identifiers to correspond with their names
made the debug bot usage message less cluttering for the chat interface (one message now instead of many)
> Fix chatdetails

- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/behaviour/AnalyzeBehaviour.java
- webofneeds/won-owner-webapp/src/main/webapp/config/detail-definitions.js
- webofneeds/won-utils/won-utils-goals/src/main/java/won/utils/goals/GoalInstantiationProducer.java
removes everything that is not a content graph from the conversation (within the goalInstantiationProducer)
> Fix conversation delete graphs

- webofneeds/won-owner-webapp/src/main/webapp/config/detail-definitions.js
fixes a problem within the generateHumanReadable that lead to a js error when only one location is put into the travelaction
> Fix travelaction humanreadable

- webofneeds/won-core/src/main/resources/validation/message/02_prop/invalid-msg-properties-in-content.rq
- webofneeds/won-core/src/main/resources/validation/message/05_sign/invalid_from_external_signer.rq
- webofneeds/won-core/src/main/resources/validation/message/05_sign/invalid_from_owner_signer.rq
- webofneeds/won-core/src/main/resources/validation/message/05_sign/invalid_from_system_signer.rq
- webofneeds/won-core/src/test/java/won/protocol/message/WonMessageValidatorTest.java
* Revert previous change that tries to ignore message content
* Add checks for properties from the msg namespace - there must not be
any in the message content
> Improve message validation

- webofneeds/won-core/src/main/java/won/protocol/util/RdfUtils.java
- webofneeds/won-core/src/main/java/won/protocol/validation/WonSparqlValidator.java
- webofneeds/won-core/src/main/resources/validation/message/02_prop/invalid_type.rq
- webofneeds/won-core/src/main/resources/validation/message/03_chain/invalid_content_chain.rq
- webofneeds/won-core/src/main/resources/validation/message/05_sign/invalid_from_external_signer.rq
- webofneeds/won-core/src/main/resources/validation/message/05_sign/signature_chain.rq
- webofneeds/won-core/src/main/resources/validation/message/05_sign/signed_or_signature.rq
- webofneeds/won-core/src/test/java/won/protocol/message/Utils.java
- webofneeds/won-core/src/test/java/won/protocol/message/WonMessageValidatorTest.java
- webofneeds/won-core/src/test/resources/validation/valid/create_msg2.trig
- webofneeds/won-core/src/test/resources/validation/valid/failure_response_msg.trig
- webofneeds/won-core/src/test/resources/validation/valid/hint_msg.trig
Test: try to create needs, get hints, connect, talk, close.
Look into the owner's and the node's logs: we don't want to see validation errors
> Fix messagevalidation for hints

- webofneeds/won-owner-webapp/src/main/webapp/app/components/usecase-group.js
> Fixed routing for responsive view

- webofneeds/won-matcher-sparql/src/main/java/won/matcher/sparql/actor/SparqlMatcherActor.java
- webofneeds/won-matcher-sparql/src/main/java/won/matcher/sparql/actor/SparqlMatcherUtils.java
- webofneeds/won-matcher-sparql/src/test/java/won/matcher/sparql/SparqlMatcherActorExperiment.java
- webofneeds/won-matcher-sparql/src/test/java/won/matcher/sparql/SparqlQueryTest.java
- webofneeds/won-matcher-sparql/src/test/resources/sparqlquerytest/need.trig
- webofneeds/won-matcher-sparql/src/test/resources/sparqlquerytest/query-with-graph-clause.rq
- webofneeds/won-matcher-sparql/src/test/resources/sparqlquerytest/query.rq
Inverse matching is only done if the current need is also a match for the found need
> Fix inverse match

- webofneeds/won-matcher-sparql/src/main/java/won/matcher/sparql/actor/SparqlMatcherActor.java
- webofneeds/won-matcher-sparql/src/test/java/won/matcher/sparql/SparqlQueryTest.java
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/price-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/app/sparql-builder-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/real-estate.js
* Improves query generation for the supply side
* switches back to using the external sparql service for checking inverse matches
> Matching for supply -> demand

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/create-need-action.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/parse-need.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/need-builder.js
- webofneeds/won-owner-webapp/src/main/webapp/app/sparql-builder-utils.js
fixes #2378 -> add query for whats around and whats new (see sparql-builder-utils.js) and reduces the info stored in a whatsaround/whatsnew to the minimum of data (only flag and additional location for whatsaround, and only the flag for whatsnew)
> Fix whatsaround #2378

- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/wonmessage/execCommand/ExecuteCreateNeedCommandAction.java
- webofneeds/won-core/src/main/java/won/protocol/util/RdfUtils.java
- webofneeds/won-utils/won-utils-import/src/main/java/won/utils/im/port/RealEstateNeedGenerator.java
- webofneeds/won-utils/won-utils-import/src/main/java/won/utils/im/port/TaxiDemandNeedGenerator.java
- webofneeds/won-utils/won-utils-import/src/main/java/won/utils/im/port/TransportOfferNeedGenerator.java
* no facets in generated sample files
* replacement of need resource substrings at creation time
> Fix need generation wrt facets and need uris

- webofneeds/won-node/src/main/java/won/node/maintenance/NeedInactivityChecker.java
Now supports an inactivity interval of 0, which deactivates it.
> Fix for the NeedInactivityChecker

- webofneeds/won-core/src/main/java/won/protocol/util/NeedModelWrapper.java
used to be based on is/seeks now is based on won:isInState
> fixed content/sysinfo detection

- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/person-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/tags-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/need-builder.js
- webofneeds/won-owner-webapp/src/main/webapp/app/utils.js
- webofneeds/won-owner-webapp/src/main/webapp/config/detail-definitions.js
- webofneeds/won-owner-webapp/src/main/webapp/config/details/basic.js
- webofneeds/won-owner-webapp/src/main/webapp/config/details/jobs.js
- webofneeds/won-owner-webapp/src/main/webapp/config/details/location.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/professional.js
- webofneeds/won-owner-webapp/src/main/webapp/icons-demo.html
- webofneeds/won-owner-webapp/src/main/webapp/package-lock.json
> Use-Case for job-offers

- webofneeds/won-owner-webapp/src/main/webapp/app/won-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/config/detail-definitions.js
implements the ability to add details that are solely available within the chat-messages (e.g. bpmn and petrinet workflow)
> implements details that are solely available as chat-message content

- webofneeds/won-core/src/main/java/won/protocol/message/WonMessageBuilder.java
- webofneeds/won-core/src/main/java/won/protocol/model/Facet.java
- webofneeds/won-core/src/main/java/won/protocol/model/FacetType.java
- webofneeds/won-node/src/main/java/won/node/camel/processor/fixed/ConnectMessageFromNodeProcessor.java
- webofneeds/won-node/src/main/java/won/node/facet/HolderFacetConfig.java
- webofneeds/won-owner-webapp/src/main/java/won/owner/web/rest/ServerSideActionController.java
- webofneeds/won-owner-webapp/src/main/java/won/owner/web/service/ServerSideActionService.java
- webofneeds/won-owner-webapp/src/main/java/won/owner/web/service/serversideaction/EventTriggeredAction.java
- webofneeds/won-owner-webapp/src/main/java/won/owner/web/service/serversideaction/EventTriggeredActionContainer.java
- webofneeds/won-owner-webapp/src/main/java/won/owner/web/service/serversideaction/predicate/ResponseToPredicate.java
- webofneeds/won-owner-webapp/src/main/java/won/owner/web/websocket/WonWebSocketHandler.java
- webofneeds/won-owner-webapp/src/main/webapp/WEB-INF/dispatcher-servlet.xml
Server-side connect  now works - tested only with holds/holdable combinations.
> Feat serverside actions

- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/pickers.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/review-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/viewer/review-viewer.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/viewer/viewers.js
- webofneeds/won-owner-webapp/src/main/webapp/app/won-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/config/detail-definitions.js
- webofneeds/won-owner-webapp/src/main/webapp/config/details/review.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_review-viewer.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_reviewpicker.scss
builds a rateDetail-structure via its own detail-picker/viewer
this is preliminary work for the review/reputation feature that we are going to implement
Please check the picker in general, i think there could be some update issues depending on which element you add/edit first or at least try if a re-edit is going to be processed in the data after publish -> currently you can add the detail in the costum post section as well as in any open chat (i know the rating during need creation does not make alot of sense but we currently dont have the ability to define message only details...)
> Feat detailstruct review

- webofneeds/conf/hokify-job-bot.properties
- webofneeds/won-bot/src/main/java/won/bot/app/HokifyJobBotApp.java
- webofneeds/won-bot/src/main/java/won/bot/framework/bot/context/HokifyJobBotContextWrapper.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/hokify/HokifyJob.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/hokify/WonHokifyJobBotHandler.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/hokify/receive/CreateNeedFromJobAction.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/hokify/send/Connect2HokifyAction.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/hokify/send/Hint2HokifyAction.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/hokify/send/HokifyHelpAction.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/hokify/send/Message2HokifyAction.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/hokify/util/HokifyBotsApi.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/hokify/util/HokifyMessageGenerator.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/event/impl/hokify/CreateNeedFromJobEvent.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/event/impl/hokify/FetchHokifyJobDataEvent.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/event/impl/hokify/StartHokifyFetchEvent.java
- webofneeds/won-bot/src/main/java/won/bot/impl/HokifyJobBot.java
- webofneeds/won-bot/src/main/resources/spring/app/hokifyJobBotApp.xml
- webofneeds/won-bot/src/main/resources/spring/bot/HokifyJobBot.xml
- webofneeds/won-core/src/main/java/won/protocol/util/DefaultPrefixUtils.java
- webofneeds/won-core/src/main/java/won/protocol/vocabulary/SCHEMA.java
- webofneeds/won-core/src/main/java/won/protocol/vocabulary/WON.java
- webofneeds/won-owner-webapp/src/main/webapp/package-lock.json
The bot is runnable and works properly.
Next Steps:
- Filter description (no contact information)
- Normalize job types (gender, type)
> Impl bot #2370

- webofneeds/won-utils/won-utils-conversation/src/main/java/won/protocol/agreement/AgreementProtocolState.java
- webofneeds/won-utils/won-utils-conversation/src/test/java/won/protocol/agreement/petrinet/PetriNetTest.java
- webofneeds/won-utils/won-utils-conversation/src/test/resources/won/protocol/petrinet/conversations/taxi-no-show.trig
* fixes a bug in the order condition in two methods that affected petri
net event order
* adds a unit test revealing the bug
> Fix ordering

- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content-general.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/publish-button.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/rating-view.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/settings/settings-wrapper.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/parse-need.js
- webofneeds/won-owner-webapp/src/main/webapp/app/selectors.js
- webofneeds/won-owner-webapp/src/main/webapp/app/won-message-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/app/won-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/elm/PublishButton.elm
- webofneeds/won-owner-webapp/src/main/webapp/elm/RatingView.elm
- webofneeds/won-owner-webapp/src/main/webapp/elm/Settings/Personas.elm
- webofneeds/won-owner-webapp/src/main/webapp/elm/Skin.elm
Ratings are currently only mocked up, but the interface is fully functional.
Rating a persona does not do anything, and the displayed rating is derived from the persona uri.
> Displaying author and rating on connections

- webofneeds/won-owner-webapp/src/main/webapp/app/selectors.js
> Filtering for own personas

- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/suggestpost-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/app/utils.js
> Adjusted sorting function to use lower case strings

- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/mobility.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/transport.js
How to test:
on integrationtest, create transport offer/demand with roughly same location/fromLocation and see if there is a match
Also fixes need a lift/ridesharing/taxi - try those too
> Feat transport query

- webofneeds/won-owner-webapp/src/main/java/won/owner/web/websocket/WonWebSocketHandler.java
Instead of
1. trigger server-side actions
2. process message and forward to client
do
1. process message and forward to client
2. trigger server-side actions
This should reduce the risk of unexpected message order seen by the
client (e.g. receive connect with newly created need before receiving
the success response to the create)
> Change handling of message coming from the WoN node

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/persona-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/need-reducer-main.js
- webofneeds/won-owner-webapp/src/main/webapp/elm/RatingView.elm
- webofneeds/won-owner-webapp/src/main/webapp/elm/Settings/Personas.elm
The only changed behaviour should be that "saving" personas now properly display identicons.
> Refactored code for personas interfaces.

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js
fixes the "Direct response to: undefined"
fixes #2463
> Made description optional

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/chat-textfield-simple.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/send-request.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/submit-button.js
- webofneeds/won-owner-webapp/src/main/webapp/elm/SubmitButton.elm
- webofneeds/won-owner-webapp/src/main/webapp/style/_chattextfield.scss
Closes #2471 
Added persona selections to adhoc connections, i.e. connections started from a WhatsX-Post or from a shared Post-URI. 
Things to check:
* persona selection is only visible if the user is logged in
* persona selection is only visible where it's useful, that is creating a new post, not for any actions that do not create a new post
* the submit button (which is next to every text field) does behave as expected
> Fix personas in re posts

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/messaging-agent.js
- webofneeds/won-owner-webapp/src/main/webapp/app/piwik.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/need-reducer-main.js
Fixes #2498 
HowToTest:
1) Create some needs with attached persona with one account
2) Create a whatsNew need with another account
3) see that the incoming hintConnection already show the corresponding persona
> Fixes #2498

- webofneeds/won-owner-webapp/src/main/webapp/elm/Settings/Personas.elm
> Added button behaviour to personas cards

- webofneeds/won-owner-webapp/src/main/java/won/owner/pojo/RestStatusResponse.java
- webofneeds/won-owner-webapp/src/main/java/won/owner/pojo/UserPojo.java
- webofneeds/won-owner-webapp/src/main/java/won/owner/pojo/UserSettingsPojo.java
- webofneeds/won-owner-webapp/src/main/java/won/owner/pojo/UsernamePojo.java
- webofneeds/won-owner-webapp/src/main/java/won/owner/web/WonOwnerMailSender.java
- webofneeds/won-owner-webapp/src/main/java/won/owner/web/configuration/AsynchronousSpringEventsConfig.java
- webofneeds/won-owner-webapp/src/main/java/won/owner/web/events/OnRegistrationCompleteEvent.java
- webofneeds/won-owner-webapp/src/main/java/won/owner/web/listener/RegistrationListener.java
- webofneeds/won-owner-webapp/src/main/java/won/owner/web/rest/RestUserController.java
- webofneeds/won-owner-webapp/src/main/resources/mail-templates/verification-html.vm
- webofneeds/won-owner-webapp/src/main/resources/spring/owner-security.xml
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/account-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/load-action.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/login-form.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/slide-in.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/toast-reducer.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/user-reducer.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/won.js
- webofneeds/won-owner-webapp/src/main/webapp/app/won-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_login.scss
- webofneeds/won-owner/src/main/java/won/owner/model/EmailVerificationToken.java
- webofneeds/won-owner/src/main/java/won/owner/model/User.java
- webofneeds/won-owner/src/main/java/won/owner/repository/EmailVerificationRepository.java
- webofneeds/won-owner/src/main/java/won/owner/service/impl/UserService.java
- webofneeds/won-owner/src/main/resources/db/migration/V7_0__add_emailverification.sql
- webofneeds/won-owner/src/main/resources/spring/core/owner-core.xml
Implemented the email_verifcation after signup/transfer (fixes #2524)
What has been done:
- Updated won-owner database schema
- Added new Verification Endpoints
- Send VerificationEmail after signup/transfer
...
- Every newly registered or transfered User will receive a email with a verification token (valid for 24hours)
- the user has a GracePeriod of 72 hours after signup where the login still works
- after this period the login will not be possible any longer (however a call to action -> "resend LInk", is presented to the User on login) Warning: This probably concerns ALL preexisting Users as the graceperiod is determined by the new registrationDate column (which is undefined for already existing users) -> they will have to verify their email adress with the above mentioned call to …
> Feat verifyemail #2524

- webofneeds/won-owner-webapp/src/main/java/won/owner/pojo/RestStatusResponse.java
- webofneeds/won-owner-webapp/src/main/webapp/app/components/login-form.js
- webofneeds/won-owner-webapp/src/main/webapp/app/won-utils.js
> Fix #2553 unverified login impossible

- webofneeds/won-owner-webapp/src/main/resources/spring/owner-security.xml
- webofneeds/won-owner-webapp/src/main/webapp/app/won-utils.js
> Add missing Content-Type header

- webofneeds/won-owner-webapp/src/main/webapp/app/leaflet-bundleable.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/mobility.js
Fixes #2556 - "Need a Lift" posts can now be created again.
Also fixes an exception that occured due to map markers not being found.
> Fix "Need a Lift" use case

- webofneeds/won-owner-webapp/src/main/java/won/owner/pojo/UserPojo.java
- webofneeds/won-owner-webapp/src/main/java/won/owner/web/rest/RestUserController.java
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/account-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/account-menu.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/logged-in-menu.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/signup/signup.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/signup/signup.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/slide-in.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/topnav.js
- webofneeds/won-owner-webapp/src/main/webapp/app/configRouting.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/account-reducer.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/message-reducers.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/process-reducer.js
- webofneeds/won-owner-webapp/src/main/webapp/app/selectors/general-selectors.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/won.js
- webofneeds/won-owner-webapp/src/main/webapp/app/sref-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/app/won-localstorage.js
- webofneeds/won-owner-webapp/src/main/webapp/app/won-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_slidein.scss
- webofneeds/won-owner/src/main/java/won/owner/model/User.java
- webofneeds/won-owner/src/main/java/won/owner/service/impl/UserService.java
- webofneeds/won-owner/src/main/resources/db/migration/V8_0__add_privateid.sql
Refactors the initialLoad/login in a way that it supports reloading a logged in private User without having a set privateId in the url (will be retrieved directly from the state, storing in the state will be handling with account.store and uses the payload response from isSignedIn or signin calls
fixes #2572 anonymous link no longer working
fixes #2571 copy link to clipboard
fixes #2495
> Fix  anonlink #2572

- webofneeds/won-owner-webapp/src/main/webapp/app/components/settings/settings-wrapper.js
- webofneeds/won-owner-webapp/src/main/webapp/elm/Elements.elm
- webofneeds/won-owner-webapp/src/main/webapp/elm/Settings.elm
- webofneeds/won-owner-webapp/src/main/webapp/elm/SubmitButton.elm
This adds a mobile view to the settings ui.
> Made settings interface responsive

- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/hokify/HokifyJob.java
- webofneeds/won-docker/deploy/int_satvm05/docker-compose.yml
- webofneeds/won-docker/deploy/master_satvm02/docker-compose.yml
This deploys the Hokify bot to integration test, ownerblue and ownergreen.
> Deploying Hokify-Bot

- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js
- webofneeds/won-owner-webapp/src/main/webapp/package-lock.json
> Fixed scrolling behaviour on connection selection

- webofneeds/won-owner-webapp/src/main/webapp/app/sparql-builder-utils.js
By introducing a property path allowing a number of location properties,
including an optional won:seeks.
> Imrove whatsaround query

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/need-reducer-main.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/reduce-connections.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/process-reducer.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js
Fixes bug in which hints currently removed the persona of an already loaded need in the state
> Fix deletedneed #2577 personas

- webofneeds/won-node/src/main/java/won/node/camel/processor/general/FacetTypeSlipComputer.java
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-header.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content-general.js
- webofneeds/won-owner-webapp/src/main/webapp/app/connection-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/need-reducer-main.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/reduce-connections.js
- webofneeds/won-owner-webapp/src/main/webapp/app/won-label-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/app/won-message-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecase-definitions.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/group-other.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-content-general.scss
fix the problem that we bounced between connected and requestreceived state for connections
> Fix deletedneed #2577 groupchat

- webofneeds/won-owner-webapp/src/main/webapp/app/components/settings/settings-wrapper.js
- webofneeds/won-owner-webapp/src/main/webapp/elm/Persona.elm
- webofneeds/won-owner-webapp/src/main/webapp/elm/Settings/Personas.elm
> Fixed slow loading of personas

- webofneeds/won-owner-webapp/src/main/webapp/app/components/usecase-picker.js
> Made usecase search resilient to duplicate use cases

- webofneeds/won-owner-webapp/src/main/webapp/elm.json
- webofneeds/won-owner-webapp/src/main/webapp/elm/Settings/Personas.elm
> Added url validation to persona creation

- webofneeds/won-matcher-service/src/main/java/won/matcher/service/nodemanager/service/HintDBService.java
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-band-search.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-get-breakfast.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-get-lunch.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-goods-service-search.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-goods-transport-offer.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-handle-complaint.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-musician-search.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-personal-transport-search.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-postdoc-offer.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-postdoc-search.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-rehearsal-room-offer.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-rehearsal-room-search.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-rent-real-estate-offer.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-rent-real-estate-search.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-service-offer.js
* need a lift fixed
* lowered false positive rate in duplicate match filtering
> Fix ridesharing lift taxi

- webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/combined-message-content.js
> Fixes #2642 personaName shown at wrong side

- webofneeds/won-node/src/main/java/won/node/facet/FacetService.java
Increments the version each time a data derivation is made, thereby changing the need's etag
> Increment need version on data derivation

- webofneeds/won-owner-webapp/src/main/webapp/app/components/chat-textfield.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/group-administration.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/group-post-messages.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/send-request.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_chattextfield.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_group-administration.scss
Implemented the Possibility to join a GroupChat (that is owned by you) with a Persona
fixes #2656
> Feat  joingroup with persona #2656

- webofneeds/won-core/src/test/java/won/protocol/message/WonMessageTest.java
- webofneeds/won-core/src/test/resources/wonmessage/forward/forwarded-msg-1.trig
Adding a test for forwarded messages used to rule out a message parsing
error as the source of a bug
> Add unit test for WonMessage

- webofneeds/conf/matcher-service/matcher-service.properties
- webofneeds/won-matcher-service/src/main/java/won/matcher/service/crawler/actor/MasterCrawlerActor.java
Matcher service crawls won nodes more often and also follows connections.
> Feat crawl connections

- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/view-reducer.js
fixes the main menu toggle again -> we weren't able to close the mainmenu
> Fixes mainmenu toggle #2678

- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-header.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-header.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/visitor-title-bar.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_connection-header.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_login.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-header.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_visitor-title-bar.scss
Implements displaying personaName within post-header and connection-header
Implements displaying personaName within visitor-view (as well as if the viewed element is a group-Chat)
Implements a bolder (pun intended) approach to the visual weight of the resend verification mail link in the login-form
> Feat lowfi persona names

- webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js
> Removes unused methods in linkeddata-service-won.js -> fixes #422

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-overview.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/combined-message-content.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/referenced-message-content.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content-general.js
- webofneeds/won-owner-webapp/src/main/webapp/app/message-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/reduce-connections.js
- webofneeds/won-owner-webapp/src/main/webapp/app/selectors/connection-selectors.js
- webofneeds/won-owner-webapp/src/main/webapp/app/selectors/general-selectors.js
Enhances the performance of certain state Retrievals:
-instead of filter and size > 0 we just check if we find an element
-instead of filter and first we just check if we find an element
> Feat  performance find

- webofneeds/won-owner-webapp/src/main/webapp/images/won-icons/ico16_share.svg
> Added share icon.

- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-is-or-seeks-info.js
> Filtering out title from details.

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/labelled-hr.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-share-link.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/view-reducer.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_labelledhr.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-content.scss
> Made general information collapsible.

- webofneeds/won-owner-webapp/src/main/webapp/app/components/connections/connections.js
> fixes #2717

- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/group-post-messages.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_group-post-messages.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-info.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-messages.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_share-dropdown.scss
fixes #2723 
- Adds share button to group-conversations
- Adapts styling of share-button so it does not cling to the border of the dropdown as much
> Fix sharebutton #2723

- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/need-reducer-main.js
> Removing needs from `held` when deleting.

- webofneeds/won-owner-webapp/src/main/webapp/config/details/location.js
Fixes #2707
Not entirely yet. This does not change the `parseFromRdf` function at all.
> Returning undefined in genSPlace if not all data is present.

- webofneeds/won-owner-webapp/src/main/webapp/app/sparql-builder-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/group-activities.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/group-classifieds.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/group-real-estate.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-goods-transport-offer.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-goods-transport-search.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-personal-transport-search.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-rehearsal-room-offer.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-rehearsal-room-search.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-rent-real-estate-offer.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-rent-real-estate-search.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-rideshare-offer.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-taxi-offer.js
Updates location based queries in their respective usecases to use a faster matching than what we would be able to match with filterInVicinity
> Feat enhancequeries

- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-context-dropdown.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-context-dropdown.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-content.scss
Changes the position of the button from the post-content component, to the post-context-dropdown or connection-context-dropdown in order to be less "in your face" (which was probably too much for the user in most cases)
New Position:
> Change Position of "Post this too!"-Button in UI

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-overview.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/post-content-message.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-info.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-menu.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/send-request.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/visitor-title-bar.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/view-reducer.js
- webofneeds/won-owner-webapp/src/main/webapp/app/view-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/skin/blue/config.css
- webofneeds/won-owner-webapp/src/main/webapp/skin/current/config.css
- webofneeds/won-owner-webapp/src/main/webapp/skin/green/config.css
- webofneeds/won-owner-webapp/src/main/webapp/skin/matchat/config.css
- webofneeds/won-owner-webapp/src/main/webapp/skin/uki/config.css
- webofneeds/won-owner-webapp/src/main/webapp/style/_connection-selection-item-line.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_connections-overview.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_create-isseeks.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_group-administration-selection-item-line.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_need-overlay.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-content-message.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-content.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-info.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-menu.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_square-image.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_suggestion-selection-item-line.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_visitor-title-bar.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_won-config.scss
First implementation of cleaning up/enhancing the post-content view
- Implements Tabs to reduce visual clutter for the default view
- Directly go to suggested Tab if "suggestions" of a need is clicked (within the connection overview)
- Directly go to detail Tab if Details-Button is clicked (within the connection overview)
> Feat  enhance postcontent

- webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-overview.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_connections-overview.scss
Removes unused/unnecessary ng-class attribute
> Fixes #2765 archived need-item in list

- webofneeds/won-owner-webapp/src/main/webapp/app/components/accordion.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/description-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/viewer/description-viewer.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/message-content.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/toasts.js
- webofneeds/won-owner-webapp/src/main/webapp/elm.json
- webofneeds/won-owner-webapp/src/main/webapp/elm/Settings/Personas.elm
- webofneeds/won-owner-webapp/src/main/webapp/style/_accordion.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_description-viewer.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_descriptionpicker.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_message-content.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_toasts.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_won-markdown.scss
> Added markdown support to persona settings.

- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content-persona.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content.js
> Showing add/remove persona button only when reasonable.

- webofneeds/won-owner-webapp/src/main/webapp/elm/Element/Styled.elm
- webofneeds/won-owner-webapp/src/main/webapp/elm/Icons.elm
> Fixed overlow caused by svg element.

- webofneeds/won-owner-webapp/src/main/webapp/app/need-utils.js
> Fixed generic need type display.

- webofneeds/won-owner-webapp/src/main/webapp/package-lock.json
- webofneeds/won-owner-webapp/src/main/webapp/package.json
Fixes some 181 vulnerabilities in our dependencies.
> *Note:*
> Please re-run `npm install`
> Fixed npm vulnerabilities.

- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/paypal-payment-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/viewer/paypal-payment-viewer.js
- webofneeds/won-owner-webapp/src/main/webapp/config/details/payment.js
Removed customer and secret fields from payment detail. This PR is only useful in combination with https://github.com/researchstudio-sat/won-payment/pull/12
As only the payment picker is changed, nothing else in this repository should be affected.
> Paypal-Bot functionality reduced. 

- webofneeds/won-core/src/main/java/won/protocol/util/LoggingUtils.java
- webofneeds/won-node/src/main/java/won/node/camel/processor/fixed/SendMessageFromNodeReactionProcessor.java
- webofneeds/won-owner-webapp/src/main/java/won/owner/web/service/serversideaction/EventTriggeredActionContainer.java
- webofneeds/won-owner/src/main/java/won/owner/messaging/OwnerProtocolCommunicationServiceImpl.java
- webofneeds/won-owner/src/main/java/won/owner/messaging/OwnerWonMessageSenderJMSBased.java
Improves logging behaviour for cases in which registering with a WoN node fails
> Feat improve register errormessage

- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content-persona.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content.js
> Add Persona only available if need has holdableFacet

- documentation/build-with-eclipse.md
- webofneeds/won-docker/deploy/int_satvm05/docker-compose.yml
- webofneeds/won-docker/image/owner/Dockerfile
- webofneeds/won-docker/image/owner/ssl/server.xml
- webofneeds/won-docker/image/wonnode/Dockerfile
- webofneeds/won-docker/image/wonnode/ssl/server.xml
- webofneeds/won-node/pom.xml
- webofneeds/won-node/src/main/resources/spring/component/broker/activemq.xml
- webofneeds/won-owner-webapp/src/main/webapp/WEB-INF/web.xml
- webofneeds/won-utils/pom.xml
- webofneeds/won-utils/won-utils-tls/pom.xml
- webofneeds/won-utils/won-utils-tls/src/main/java/won/utils/tls/AcceptAllCertsTrustManager.java
Upgrade to tomcat 9
How to test: 
* try both owners/nodes on integrationtest, i.e. also the one on 8081
> Feat upgrade to tomcat 9

- webofneeds/won-owner-webapp/src/main/webapp/app/components/footer.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_footer.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_slidein.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_topnav.scss
(Anonymous) slide-in & footer resized the demonstrator on mobile devices (automatic rescaling)
This PR fixes the problem by:
- removing the min-width of the slide-in text
- restyling (work in progress) of the footer in mobile (remove the dividers and changed flex-direction to column)
fixes #2677
> Fixes #2677

- webofneeds/won-owner-webapp/src/main/webapp/package.json
Update package.json for elm and ell-format
> Update elm settings

- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/datetime-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/location-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/travel-action-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/signup/signup.html
Removes or replaces the id-attributes with a real unique id
how to test:
- try datetime-picker.js
- try location-picker.js
- try travel-action-picker.js
- try signup (both start from scratch and keep postings option)
fixes #2396
> Remove or replace attribute id's in pickers

- webofneeds/won-owner-webapp/src/main/webapp/app/components/usecase-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/app/usecase-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_usecase-picker.scss
- Displays a Reset button in the usecase search field
- Sorts the search results based on the usecase label (asc)
- Displays "no usecases found for [searchstring]" if no usecases are found
- Displays "new custom post" if no usecases are found in addition to the label above
Fixes #2848
> Adapted UseCase Search

- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/travel-action-picker.js
Fixes route-picker
How To Test:
- create a need from a useCase with a route-detail (travelAction detail) -> see that the picker opens and a route can be selected
fixes #2858
> remove unique-id generation -> fixes #2858

- webofneeds/won-owner-webapp/src/main/webapp/app/configRouting.js
> Added login check to settings route.

- webofneeds/won-owner-webapp/src/main/java/won/owner/web/websocket/WonWebSocketHandler.java
If the owner webapp client sends invalid JSON-LD, a message is logged
(little on info, more on debug), but the WS does not break any more
> Ignore invalid JSON-LD message

- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/file-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/viewer/file-viewer.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_file-viewer.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_filepicker.scss
Changes the styling of the file-viewer and file-picker to a simpler design (only one file per row in picker/viewer, and removal of the borders and background colors in the viewer (simple list of files)
> Feat  rework file viewer

- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js
Removes the publish button if the need is being edited
> Fixes #2886

- webofneeds/won-owner-webapp/src/main/webapp/app/components/about/about.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/usecase-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_about.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_usecase-picker.scss
> Fixes #2884

- webofneeds/won-owner-webapp/src/main/webapp/elm/Settings/Personas.elm
> Displaying rounded persona icons.

- webofneeds/won-owner-webapp/src/main/webapp/app/atom-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-overview.js
- rename location back to hasLocation
- rename socket back to hasSocket
- rename unreadSuggestedConnections back to hasUnreadSuggestedConnections
fixes #2893
> Fixes #2893

- webofneeds/won-owner-webapp/src/main/webapp/app/atom-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-card.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content-general.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-header.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/visitor-title-bar.js
- webofneeds/won-owner-webapp/src/main/webapp/app/won-label-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_post-content-general.scss
Refactors general-info so that it actually uses one two column grid
> Refac  general info

- webofneeds/won-owner-webapp/src/main/webapp/elm.json
- webofneeds/won-owner-webapp/src/main/webapp/elm/PublishButton.elm
- webofneeds/won-owner-webapp/src/main/webapp/style/_publish-button.scss
> Made publish button dropdown direction dynamic

- webofneeds/won-vocab/src/main/resources/ontology/ext/won-ext-hold.ttl
- webofneeds/won-vocab/src/main/resources/ontology/won-core.ttl
Refactor split between hold ontology and core, rework socket configuration
> Refactor ontologies

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/about/about.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/about/about.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-card.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-map.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/location-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/travel-action-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/map/map.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/map/map.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/overview/overview.html
- webofneeds/won-owner-webapp/src/main/webapp/app/components/overview/overview.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/usecase-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/view-reducer.js
- webofneeds/won-owner-webapp/src/main/webapp/app/selectors/general-selectors.js
- webofneeds/won-owner-webapp/src/main/webapp/app/utils.js
- webofneeds/won-owner-webapp/src/main/webapp/app/view-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_map.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_overview.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_textfield.scss
Implements a search-input field in the whatsAround view, that way you can search around any location and retrieve the atoms that are around the location.
This enables users who did not grant geolocation access to still see whats around certain places
> Feat  enhance whats around

- webofneeds/won-buildtools/src/main/resources/eclipse/formatter.xml
- webofneeds/won-core/src/main/java/won/protocol/model/SocketType.java
- webofneeds/won-core/src/main/java/won/protocol/rest/LinkedDataRestClientHttps.java
- webofneeds/won-core/src/main/java/won/protocol/rest/RdfDatasetConverter.java
- webofneeds/won-core/src/main/java/won/protocol/util/linkeddata/WonLinkedDataUtils.java
- webofneeds/won-owner-webapp/pom.xml
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connections/connections.html
* Dataset converter also responsible for triple-based formats
* Fix for SocketType URIs in java Enum (SocketType.java)
* useful error messages when socket definition fetching fails
* move the RDFDatasetConverter to first position in message converters list of RestTemplate so it trumps the jackson implementation
> Fix  ontology loading

- webofneeds/conf/node.properties
- webofneeds/won-node/src/main/resources/spring/component/broker/activemq.xml
- webofneeds/won-node/src/main/resources/spring/component/crypto/node-crypto.xml
> Fix  activemq connectfail

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/create-atom-action.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/persona-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/post-context-dropdown.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/atom-reducer/atom-reducer-main.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/atom-reducer/parse-atom.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/atom-reducer/parse-connection.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/atom-reducer/reduce-atoms.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/atom-reducer/reduce-connections.js
Adding a Persona to an atom was not visible without a reload:
- creating an atom with a persona (whether it was a normal publish or a publish as an enable or reaction UseCase)
- adding an atom with a persona
... did not add the "publish as persona" in the ui (without reload)
This is fixed with this PR
> Fix  addpersona

- webofneeds/won-core/src/main/java/won/protocol/util/DefaultPrefixUtils.java
- webofneeds/won-core/src/main/java/won/protocol/vocabulary/WXBUDDY.java
- webofneeds/won-core/src/test/java/won/protocol/util/Prefixer.java
* Adds two prefixes to the default prefixes
* Adds a class for pruning a jena Dataset's prefixes, `won.protocol.util.Prefixer`, to the test sources
* adds the WXBUDDY vocabulary constants class
> Feat  improve prefixes

- webofneeds/won-bot/src/main/java/won/bot/impl/DebugBot.java
- webofneeds/won-bot/src/main/resources/spring/bot/DebugBot.xml
- webofneeds/won-core/src/main/java/won/protocol/message/WonMessage.java
- webofneeds/won-core/src/main/java/won/protocol/util/RdfUtils.java
- webofneeds/won-core/src/test/java/won/protocol/message/EncodeDecodeMessageTest.java
- webofneeds/won-core/src/test/java/won/protocol/message/ReadWriteTest.java
- webofneeds/won-core/src/test/java/won/protocol/message/Utils.java
- webofneeds/won-core/src/test/java/won/protocol/message/WonMessageBuilderTest.java
- webofneeds/won-core/src/test/java/won/protocol/message/WonMessageTest.java
- webofneeds/won-core/src/test/java/won/protocol/model/URISerializeVsToStringTest.java
- webofneeds/won-core/src/test/java/won/protocol/model/util/RdfIoSpeedTest.java
- webofneeds/won-core/src/test/java/won/protocol/rest/WonEtagHelperTests.java
- webofneeds/won-core/src/test/java/won/protocol/util/Prefixer.java
- webofneeds/won-core/src/test/resources/wonmessage/extract_content/create_message.trig
- webofneeds/won-matcher/src/main/java/won/matcher/camel/routes/MatcherApplicationListenerRouteBuilder.java
- webofneeds/won-node/src/main/java/won/node/camel/processor/fixed/ConnectionStateChangeReactionProcessor.java
- webofneeds/won-node/src/main/java/won/node/camel/processor/fixed/CreateAtomMessageProcessor.java
- webofneeds/won-node/src/main/java/won/node/camel/processor/fixed/ReplaceAtomMessageProcessor.java
- webofneeds/won-utils/won-utils-goals/src/test/java/won/utils/goals/extraction/GoalDataExtractionTest.java
- webofneeds/won-utils/won-utils-goals/src/test/java/won/utils/goals/instantiation/GoalInstantiationTest.java
- webofneeds/won-utils/won-utils-goals/src/test/java/won/utils/shacl/ShaclTest.java
Fixes the extraction of content graphs from WoN messages. 
With this PR, the atoms' content graphs have URIs within the URI space of the atom, and their signatures are in separate signature graphs.
> Fix  content graph signatures

- webofneeds/won-node/src/main/java/won/node/camel/processor/fixed/ReplaceAtomMessageProcessor.java
> Fix bug #2968: replace deletes derived data

- webofneeds/won-owner-webapp/src/main/webapp/app/pages/map.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/pages/overview.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/atom-reducer/atom-reducer-main.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/atom-reducer/reduce-atoms.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/reducers.js
- webofneeds/won-owner-webapp/src/main/webapp/app/redux/selectors/general-selectors.js
Refactors storing of whatsNew/Around metaAtoms the same way we store our owned Meta Atoms
Removes redundant conditionals
> Refac  fix structure

- webofneeds/won-bot/src/main/java/won/bot/exception/NoBotResponsibleException.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/atomlifecycle/AbstractDeleteAtomAction.java
- webofneeds/won-bot/src/main/java/won/bot/framework/manager/impl/BotManagerImpl.java
- webofneeds/won-bot/src/main/java/won/bot/integration/BotOwnerCallback.java
- webofneeds/won-core/src/main/java/won/protocol/message/WonMessageBuilder.java
- webofneeds/won-core/src/main/java/won/protocol/vocabulary/SCHEMA.java
- webofneeds/won-core/src/test/java/won/protocol/util/Prefixer.java
- webofneeds/won-cryptography/src/main/java/won/protocol/message/processor/impl/SignatureCheckingWonMessageProcessor.java
Adds abstract helper class to simplify AtomDeletion Actions in bots
Adds missing Resource/Property constants in SCHEMA.java (e.g. PlanAction)
Avoids checking the signature for successResponses of DeleteMessages (signature can't be checked since the signature has been deleted)
> Feat  spoco updates

- webofneeds/won-owner-webapp/src/main/webapp/app/app.js
Safari doesn't (yet?) support the new permissions api.
> Make app work on Safari again.

- webofneeds/won-owner-webapp/src/main/webapp/style/_atom-content-buddies.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_atom-content-holds.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_atom-content-participants.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_atom-content-suggestions.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_inventory.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_map.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_other-card.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_overview.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_persona-card.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_skeleton-card.scss
fixes grid layouts and makes them responsive
fixes #2978
> Fixes #2978

- webofneeds/won-owner-webapp/src/main/webapp/app/service/won.js
Fixes TTL parsing in RDF mode.
fixes #2967
> Fixes #2967

- webofneeds/won-owner/src/main/java/won/owner/model/User.java
> Prevent duplicate insert of useratom

- webofneeds/won-docker/README.md
- webofneeds/won-docker/deploy/local_image/docker-compose.yml
It is now possible again to download and start won from the docker hub image
> Feat docker hub image

- webofneeds/won-owner-webapp/src/main/webapp/app/components/svg-icon.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_publish-button.scss
fixes persona selection dropdown icon in createView
> Fixes #2975

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/menu.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/slide-in.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/topnav.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/usecase-picker.js
- webofneeds/won-owner-webapp/src/main/webapp/app/pages/about.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/pages/inventory.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/pages/settings.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/pages/signup.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/view-reducer.js
- webofneeds/won-owner-webapp/src/main/webapp/app/redux/selectors/view-selectors.js
- webofneeds/won-owner-webapp/src/main/webapp/app/redux/utils/view-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_menu.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_slidein.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_topnav.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_usecase-picker.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/won.scss
Implements a "mobile"-menu with a hamburger-button indicator left of the logo
> Feat  update menu

- webofneeds/won-owner-webapp/src/main/webapp/app/components/account-menu.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/login-form.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/topnav.js
- webofneeds/won-owner-webapp/src/main/webapp/app/pages/about.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/pages/connections.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/pages/settings.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/pages/signup.jsx
- webofneeds/won-owner-webapp/src/main/webapp/static/skin/uki/config.css
- webofneeds/won-owner-webapp/src/main/webapp/style/_atom-content-buddies.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_atom-content-participants.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_atom-content-suggestions.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_connection-header.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_covering-dropdown.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_inventory.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_login.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_menu.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_topnav.scss
> Feat  update topnav

- webofneeds/won-core/src/main/java/won/protocol/util/linkeddata/CachingLinkedDataSource.java
- webofneeds/won-owner-webapp/src/main/webapp/app/components/topnav.js
- webofneeds/won-owner-webapp/src/main/webapp/app/pages/about.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/pages/connections.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/pages/create.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/pages/inventory.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/pages/map.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/pages/overview.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/pages/post.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/pages/settings.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/pages/signup.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/atom-reducer/parse-atom.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_overview.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/won.scss
Groups the whats new atoms by usecases.
Not implemented within map yet
> Feat  group whats new

- webofneeds/won-owner-webapp/src/main/java/won/owner/web/websocket/WonWebSocketHandler.java
No push/email notifications in two cases:
* the message is a hint and the respective connection is not in state
suggested
* sender and recipient atom are owned by the same user
> Reduce push and email notifications

- webofneeds/won-owner-webapp/src/main/java/won/owner/web/websocket/WonWebSocketHandler.java
- webofneeds/won-utils/won-utils-batch/pom.xml
- webofneeds/won-utils/won-utils-batch/src/main/java/won/utils/batch/BatchingConsumer.java
- webofneeds/won-utils/won-utils-batch/src/test/java/won/utils/batch/BatchingConsumerTest.java
Owner webapp now does not send mails repeatedly for the same match.
> Fix  too many matches per mail

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/persona-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-content-persona.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/elm-react.jsx
- webofneeds/won-owner-webapp/src/main/webapp/package-lock.json
> Fixed floating `this`.

- webofneeds/won-bot/src/main/java/won/bot/framework/component/atomproducer/impl/MailFileAtomProducer.java
- webofneeds/won-bot/src/main/java/won/bot/framework/component/atomproducer/impl/TrigFileAtomProducer.java
- webofneeds/won-bot/src/main/java/won/bot/framework/component/atomproducer/impl/TurtleFileAtomProducer.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/atomlifecycle/AbstractCreateAtomAction.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/atomlifecycle/AbstractModifyAtomAction.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/atomlifecycle/CreateAtomWithSocketsAction.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/wonmessage/PrintWonMessageAction.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/wonmessage/execCommand/ExecuteCreateAtomCommandAction.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/wonmessage/execCommand/ExecuteReplaceCommandAction.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/event/impl/wonmessage/WonMessageSentOnConnectionEvent.java
- webofneeds/won-core/src/main/java/won/cryptography/keymanagement/KeyPairAliasDerivationStrategyFactory.java
- webofneeds/won-core/src/main/java/won/cryptography/service/keystore/FileBasedKeyStoreService.java
- webofneeds/won-core/src/main/java/won/protocol/message/WonMessageType.java
- webofneeds/won-core/src/main/java/won/protocol/model/Socket.java
- webofneeds/won-core/src/main/java/won/protocol/util/AtomModelWrapper.java
- webofneeds/won-core/src/test/java/won/protocol/message/EncodeDecodeMessageTest.java
- webofneeds/won-core/src/test/java/won/protocol/util/AtomModelWrapperTest.java
- webofneeds/won-node/src/main/java/won/node/camel/processor/general/FailResponder.java
- webofneeds/won-node/src/main/resources/db/migration/V8_0__socketuri_nonnull.sql
- webofneeds/won-owner-webapp/src/main/resources/spring/owner-context.xml
- webofneeds/won-owner/src/main/resources/spring/component/crypto/owner-crypto.xml
In an attempt to make the randomsimulatorbot usable, found and fixed some bugs
> Some fixes for AtomModelWrapper and Socket

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/account-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/app.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/slide-in.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/configRedux.js
- webofneeds/won-owner-webapp/src/main/webapp/app/configRouting.js
- webofneeds/won-owner-webapp/src/main/webapp/app/redux/selectors/view-selectors.js
Verification requests are now made and indepent of the top-nav.
Also fixed a few prop-type warnings.
Resolves #3055
> Fix  email verification  #3055

- webofneeds/won-bot/src/main/java/won/bot/framework/bot/base/EventBot.java
- webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/wonmessage/PrintWonMessageAction.java
- webofneeds/won-core/src/main/java/won/protocol/jms/BrokerComponentFactory.java
- webofneeds/won-core/src/main/java/won/protocol/jms/WonJmsConfiguration.java
- webofneeds/won-core/src/main/java/won/protocol/message/WonMessage.java
- webofneeds/won-core/src/test/java/won/protocol/util/UriChecker.java
- webofneeds/won-node/src/main/java/won/node/camel/processor/general/AtomProtocolOutgoingMessagesProcessor.java
- webofneeds/won-node/src/main/java/won/node/camel/processor/general/OwnerProtocolOutgoingMessagesProcessor.java
- webofneeds/won-owner/src/main/java/won/owner/camel/routes/fixed/AmqpToJms.java
- webofneeds/won-owner/src/main/java/won/owner/messaging/OwnerProtocolCamelConfiguratorImpl.java
- webofneeds/won-owner/src/main/resources/spring/component/camel/owner-camel.xml
AFAICT this fixes the problems we had with the DebugBot. 
Check this PR with debugbot and randomsimulatorbot.
> Feat  message debugging

- webofneeds/won-owner-webapp/src/main/webapp/app/components/file-dropzone.jsx
> Little refac of dropzone code

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-info.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/viewer/suggest-atom-viewer.jsx
- Fixes: AdHoc requests weren't created beacuase of missing counter part socketUri
- Now its possible again to connect AdHoc
- For atoms with chatFacet -> ask to chat
- For atoms with groupFacet -> ask to join group
> Fix  connect ad hoc #3086

- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/location-picker.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/person-picker.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/title-picker.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/travel-action-picker.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/usecase-picker.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/pages/react/map.jsx
- Fixes: Location search field was not updated when selecting locations
Fixes #3090
> Fixed locationpicker bugs and refactored title-picker.

- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-card.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-messages.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/cards/pokemon-raid-card.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-atom.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/viewer/suggest-atom-viewer.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/footer.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/group-atom-messages.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/combined-message-content.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/connection-message.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/pages/react/about.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/pages/react/connections.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/pages/react/create.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/pages/react/map.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/pages/react/overview.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/pages/react/settings.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/pages/react/signup.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/redux/selectors/process-selectors.js
- webofneeds/won-owner-webapp/src/main/webapp/app/redux/selectors/view-selectors.js
- webofneeds/won-owner-webapp/src/main/webapp/app/redux/utils/view-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_pokemon-raid-card.scss
- PokemonRaids are displayed within the generic other-card component
- PokemonRaids display the pokemonImageUrl as an image if there is already a pokemon present
- Additionally refactored frontend code -> use *Selector.js or *Util.js helper functions for certain state retrieval instead of accessing data stored deep in the state directly in the component
- Additionally show Atoms in WhatsNew and WhatsAround regardless of the used "invisible" or "DirectResponse" or "SearchAtom" flags, when debugmode is enabled
> Feat  enhance spoco raid ui

- webofneeds/won-owner-webapp/src/main/webapp/app/pages/react/map.jsx
Inputs in the search field of the What's Around view are now debounced.
Fixes #3099
> Added debounce to map.

- webofneeds/won-owner-webapp/src/main/java/won/owner/pojo/RestStatusResponse.java
- webofneeds/won-owner-webapp/src/main/webapp/app/service/won.js
> Fix RestStatusResponse

- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-connections-indicator.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/cards/other-card.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/redux/selectors/connection-selectors.js
- webofneeds/won-owner-webapp/src/main/webapp/app/redux/utils/atom-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_atom-connections-indicator.scss
See #2966 for problem description
Fixes #2966
- Adds a card that indicates new messages/connection requests for atoms in the inventory
- Connection indicator replaces suggestion indicator if there are unread requests or messages
> Fix more visible connections

- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-content-buddies.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-content-participants.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-context-swipeable-view.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-header.jsx
- webofneeds/won-owner-webapp/src/main/webapp/package-lock.json
- webofneeds/won-owner-webapp/src/main/webapp/package.json
- webofneeds/won-owner-webapp/src/main/webapp/style/_atom-content-buddies.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_atom-content-participants.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_atom-context-layout.scss
- Interaction buttons to big + cards to big
- Fixes: N/A
- Interaction buttons are slideable
- Also swipable on media
> Feat  interaction update

- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-info.jsx
- webofneeds/won-owner-webapp/src/main/webapp/style/_atom-info.scss
> Fix inactive need status visibility #3024

- webofneeds/won-owner-webapp/src/main/webapp/app/api/owner-api.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/atom-reducer/parse-message.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/atom-reducer/reduce-messages.js
- webofneeds/won-owner-webapp/src/main/webapp/app/redux/selectors/connection-selectors.js
> Make groupChats work

- webofneeds/pom.xml
- webofneeds/won-parent-pom/pom.xml
The refactoring of the main `pom.xml`  into main `pom.xml` and `won-parent-pom/pom.xml` broke releasing. This PR is supposed to fix that
> Fix poms to enable releasing

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/atom-reducer/parse-connection.js
Fixes displaying sent/received proposals or anything that causes messageEffects to work without a reload
> Fix  ui proposals

- webofneeds/pom.xml
> Disable javadoc linting when attaching javadoc jar

- webofneeds/pom.xml
- webofneeds/won-bot/pom.xml
- webofneeds/won-buildtools/pom.xml
- webofneeds/won-core/pom.xml
- webofneeds/won-cryptography/pom.xml
- webofneeds/won-docker/pom.xml
- webofneeds/won-matcher-rescal/pom.xml
- webofneeds/won-matcher-service/pom.xml
- webofneeds/won-matcher-solr/pom.xml
- webofneeds/won-matcher-sparql/pom.xml
- webofneeds/won-matcher-utils/pom.xml
- webofneeds/won-matcher/pom.xml
- webofneeds/won-node-webapp/pom.xml
- webofneeds/won-node/pom.xml
- webofneeds/won-ontology-validator/pom.xml
- webofneeds/won-owner-webapp/pom.xml
- webofneeds/won-owner/pom.xml
- webofneeds/won-parent-pom/pom.xml
- webofneeds/won-sockets/pom.xml
- webofneeds/won-sockets/won-sockets-tx/pom.xml
- webofneeds/won-test/pom.xml
- webofneeds/won-utils/pom.xml
- webofneeds/won-utils/won-utils-batch/pom.xml
- webofneeds/won-utils/won-utils-conversation/pom.xml
- webofneeds/won-utils/won-utils-crawl/pom.xml
- webofneeds/won-utils/won-utils-goals/pom.xml
- webofneeds/won-utils/won-utils-import/pom.xml
- webofneeds/won-utils/won-utils-mail/pom.xml
- webofneeds/won-utils/won-utils-tls/pom.xml
- webofneeds/won-vocab/pom.xml
Changes made by the maven release plugin.
> New development version 0.8-SNAPSHOT

- webofneeds/won-node/src/main/java/won/node/camel/processor/general/ToNodeSender.java
- webofneeds/won-node/src/main/java/won/node/service/persistence/ConnectionService.java
* Messages cannot be sent to atoms on other nodes
* hint processing on the node causes an exception
Above bugs fixed
> Fix  hint and remote send

- webofneeds/won-node-webapp/src/main/java/won/node/web/LinkedDataWebController.java
Cannot view a message in 'Show RDF Data' mode.
Can view a message in 'Show RDF Data' mode.
> Fix human readable linked data for message

- webofneeds/won-owner-webapp/src/main/webapp/app/redux/utils/atom-utils.js
https://github.com/WoN-Hackathon-2019/Information/issues/4
- Fixes: N/A
-
-
-
- [x ] No
> should fix undefined image bug described in link below

- webofneeds/won-owner-webapp/src/main/webapp/config/details/location.js
Should fix graphId generation for toLocation and fromLocation
> Fixes generating invalid graph id

- webofneeds/won-owner-webapp/src/main/webapp/config/detail-definitions.js
- webofneeds/won-owner-webapp/src/main/webapp/config/details/extended.js
Adds isbn detail
Adds author detail
Visible in custom UseCase
> Feat extended details

- webofneeds/won-docker/deploy/hackathon_satvm02/docker-compose.yml
The sparql matcher on hackathon.matchat.org does not do anything
The sparql matcher works
> Fix  hackathon sparql matcher

- documentation/howto/README.md
Adds howtos for the most pressing beginner questions.
- Fixes: N/A
-
-
-
> Add howtos

- webofneeds/won-core/src/main/java/won/protocol/vocabulary/SCHEMA.java
- webofneeds/won-core/src/main/java/won/protocol/vocabulary/WONMATCH.java
Adds missing property 
- Fixes: N/A
-
-
-
> Add missing match:searchString property

- webofneeds/won-core/src/main/java/won/protocol/util/linkeddata/LDPContainerPage.java
- webofneeds/won-core/src/main/java/won/protocol/util/linkeddata/LinkedDataSource.java
- webofneeds/won-core/src/main/java/won/protocol/util/linkeddata/LinkedDataSourceBase.java
- webofneeds/won-core/src/main/java/won/protocol/util/linkeddata/WonLinkedDataUtils.java
- webofneeds/won-core/src/test/java/won/protocol/util/WonLinkedDataUtilsTest.java
- webofneeds/won-cryptography/src/test/java/won/cryptography/utils/TestingDataSource.java
- webofneeds/won-node-webapp/src/main/java/won/node/web/LinkedDataWebController.java
- webofneeds/won-node/src/main/java/won/node/service/linkeddata/generate/LinkedDataServiceImpl.java
- webofneeds/won-node/src/main/java/won/node/service/persistence/AtomInformationServiceImpl.java
- webofneeds/won-owner-webapp/src/main/java/won/owner/web/rest/RestAtomController.java
- webofneeds/won-owner-webapp/src/main/webapp/app/api/owner-api.js
- [~] Bugfix
- [~] Feature
A large number of atoms is fetched into the owner webapp server for "What's New/What's Around" cases, then effectively shuffled, filtered by some criteria and only the top N are used, leading to fresh content sometimes missing
Atoms are fetched in batches of size `limit` , filtered and only if not enough atoms are present, the next batch is fetched
> Feat  page atomlist

- documentation/howto/README.md
> Fix: proper mongo command to init the database

- documentation/howto/README.md
- [x ] Docs have been reviewed and added/updated if needed (for bug fixes / features)
- [x ] Documentation content changes
Mongo command in mongo shell did not work as described.
- Fixes: N/A
Fixed typo in command. 
-
-
-
- [x ] No
> Typo in command in documentation/howto/README.md / docker example for mongodb

- documentation/howto/README.md
Fixed code example in "HowTo: Obtaining the Connection If You Only have the Socket URIs"
- Fixes: N/A
-
-
-
> fixed wrong reference in howto

- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/group-classifieds.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-books-offer.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-books-search.js
UseCases for Book Bot (Hackathon)
2 new useCases:
- Find a Book
- Offer a Book
> Adds 2 new usecases for a hackathon project-team (BookPileBot)

- documentation/howto/README.md
- remains unchanged
- remains unchanged
> Fix wrong file reference

- webofneeds/won-owner-webapp/src/main/webapp/app/pages/react/map.jsx
- Fixes: #3188
- State is now set first so the typed input is shown directly before Nimonatim lookup
> Fix WhatsAround Location Picker

- webofneeds/won-owner-webapp/src/main/webapp/app/components/petrinet-state.jsx
- Fixes: #3185
- EnabledTransitions are shown again
> Show enabled transitions for petrinet view

- webofneeds/won-core/src/main/java/won/protocol/WonConstants.java
- webofneeds/won-vocab/src/main/resources/ontology/won-core.ttl
- webofneeds/won-vocab/src/main/resources/ontology/won-message.ttl
a few ontology properties are missing.
properties are there now
> Feat  minor ontology fixes

- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/travel-action-picker.jsx
no further description necessary
> Fixes #3193 -> routepicker suggestions "undefined"

- webofneeds/won-owner-webapp/src/main/java/won/owner/web/rest/RestAtomController.java
An unforseen error down the stack when loading one atom
that could be just logged causes the application to break
in a major way (no atoms shown for user at all). 
This update makes it more resilient when fetching an atom fails.
> Catch any Exception when gathering atoms in ownerapp

- webofneeds/won-owner-webapp/src/main/java/won/owner/web/websocket/WonWebSocketHandler.java
* Fix echo checks - instead of checking for the envelope type (ie,
message direction), which is always msg:FromOwner since the message
refactoring, we check whether the focal message is a response.
* Add a case branch for pushing message notifications
Email notifications and browser push notifications aren't sent
Both notifications should now work, though it's not possible to test this locally.
> Fix email and push notifications in owner webapp

- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-content-buddies.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-content-participants.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-content-suggestions.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-overview.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/redux/selectors/connection-selectors.js
- webofneeds/won-owner-webapp/src/main/webapp/app/won-label-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_atom-content-buddies.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_atom-content-holds.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_atom-content-participants.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_atom-content-suggestions.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_atom-content.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_atom-footer.scss
Categorize Suggested Connections in order to indicate what sockets will be used....
> Feat  suggestion categories

- webofneeds/won-owner-webapp/src/main/webapp/app/components/create-atom.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/atom-reducer/reduce-messages.js
> Feat  minor fixes

- webofneeds/won-docker/deploy/live_satvm01/docker-compose.yml
- webofneeds/won-docker/deploy_live.sh
- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-content-suggestions.jsx
Configures docker-compose and deploy script to include raidbot for matchat.org
> Feat  raidbot live

- webofneeds/won-docker/deploy/live_satvm01/docker-compose.yml
> Fix mongodb port for jobbot

- webofneeds/won-core/src/main/java/won/protocol/jms/WonJmsConfiguration.java
- webofneeds/won-node/src/main/resources/spring/component/broker/activemq.xml
- [x ] Build was run locally and `mvn install` succeeds
(continuation of #3213 - that one hadn't done the trick completely)
> Fix  activemq settings cont

- webofneeds/won-core/src/main/java/won/protocol/jms/BrokerComponentFactory.java
- webofneeds/won-docker/deploy/live_satvm01/docker-compose.yml
- webofneeds/won-matcher-service/src/main/java/won/matcher/service/nodemanager/actor/AtomConsumerProtocolActor.java
- webofneeds/won-node/src/main/java/won/node/camel/processor/fixed/SocketHintMessageProcessor.java
- webofneeds/won-node/src/main/java/won/node/service/persistence/ConnectionService.java
- webofneeds/won-owner-webapp/src/main/java/won/owner/web/rest/RestUserController.java
- webofneeds/won-owner/src/main/java/won/owner/protocol/message/base/OwnerCallbackAdapter.java
- webofneeds/won-owner/src/main/java/won/owner/service/impl/KeystoreEnabledPersistentRememberMeServices.java
- webofneeds/won-owner/src/main/java/won/owner/service/impl/OwnerApplicationService.java
Springs CachingConnectionFactory and its underlying ActiveMQSession produce the behaviour that the activemq session times out after 10mins of no messages, the factory refreshes it, but it can happen that too many messages remain in-flight, which are never consumed (or at least, acknowledged), and the broker does not deliver any newer messages.
Removed the CachingConnectionFactory, using only the underlying ActiveMqConnectionFactory, which seems to work better
* Clients must update to this version to use the change. If you see an exception message `Setup of JMS message listener invoker failed for destination [...] - trying to recover. Cause: The Session is closed`, you should …
> Change ActiveMQ/JMS config

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/api/owner-api.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-messages.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/petrinet-state.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/atom-reducer/atom-reducer-main.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/atom-reducer/reduce-messages.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/process-reducer.js
- webofneeds/won-owner-webapp/src/main/webapp/package-lock.json
- Fixes: #3201 
- Messages are claimed with a several claim message
- Claimed message is collapsed
-
> Fix  petri net transition claim #3201

- webofneeds/won-docker/image/nginx/nginx-int.conf
- webofneeds/won-docker/image/nginx/nginx.conf
- webofneeds/won-docker/image/owner/ssl/server.xml
- webofneeds/won-docker/image/wonnode/ssl/server.xml
> Enable HTTP/2

- webofneeds/won-utils/won-utils-conversation/src/main/java/won/protocol/agreement/AgreementProtocolState.java
- webofneeds/won-utils/won-utils-conversation/src/main/java/won/protocol/agreement/AgreementProtocolUris.java
Issue #3225
- Fixes: #3225 
- Claimed messages will be marked as claimed and also stay claimed after reload
> Mark claimed messages in chat

- webofneeds/won-core/src/main/java/won/protocol/util/WonRdfUtils.java
- webofneeds/won-core/src/main/java/won/protocol/vocabulary/SCHEMA.java
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/file-picker.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/image-picker.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/viewer/file-viewer.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/viewer/image-viewer.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/file-dropzone.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/service/message-builder.js
- webofneeds/won-owner-webapp/src/main/webapp/config/details/files.js
- Bots/non webapp applications could not send files in messages
-  Sending files in messages
-
-
> Send messages with files

- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-messages.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/group-atom-messages.jsx
- webofneeds/won-owner-webapp/src/main/webapp/package-lock.json
- webofneeds/won-owner-webapp/src/main/webapp/package.json
Currently everytime the state of the displayed messages changes it will induce a scroll to the bottom, this is rather bad because that way you can't open any messages actions, or load prev. messages without having a scroll to the bottom on load after.
- Fixes: #3216
Scroll bar "snaps" to the bottom and initiates auto-scroll whenever the scroll bar is (almost) at the bottom, if the user scrolls it is automatically unsnapped (if it is not within the snap area: bottom + 75px) If unsnapped automatic scrolling to new messages is deactivated
-
-
-
The 75px threshold is there to make the snapping easier to be met, and also to avoid missing a necessary scroll due to our react update …
> Fixes #3216 (scroll to bottom)

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/atoms-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/persona-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-messages.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/referenced-message-content.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/slide-in.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/messaging-agent.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/atom-reducer/atom-reducer-main.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/atom-reducer/parse-message.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/atom-reducer/reduce-messages.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/process-reducer.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/won.js
- webofneeds/won-owner-webapp/src/main/webapp/app/won-message-utils.js
Up until now deep fetched connections contained a set of messages, the parsing performance was not great.
Removes unused code in wonMessage generation and enhance the performance bottle neck within message parsing of a deep connection yada yada yada 
- faster....
-[X] No
> Refac  performance won message

- webofneeds/won-owner-webapp/src/main/webapp/app/components/login-form.jsx
- Fixes #3212 
The default submit action of the login form now gets prevented using `preventDefault()` which keeps the browser from refreshing the page, therefore canceling the login request
> Peventing default action of form submission

- webofneeds/won-owner-webapp/src/main/java/won/owner/web/WonOwnerMailSender.java
- webofneeds/won-owner-webapp/src/main/java/won/owner/web/sitemap/SitemapService.java
- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-context-dropdown.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-share-link.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-context-dropdown.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/won-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/sw.js
Fixes deep links in share component /emails and serviceworker
> Fix deep-links

- webofneeds/won-core/src/main/java/won/protocol/repository/MessageEventRepository.java
When retrieving `[atom]/unread`, incoming and outgoing messages are counted
When retrieving `[atom]/unread`, only incoming messages are counted
> Only report incoming msgs as unread

- webofneeds/won-vocab/src/main/resources/ontology/won-workflow.ttl
the `wf` namespace is used but no ontology is published at `https://w3id.org/won/workflow`
The `won-workflow` ontology is now in the project and can be published.
> Feat  add workflow ontology

- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/location-picker.jsx
- webofneeds/won-owner-webapp/src/main/webapp/style/_locationpicker.scss
- Fixes #1748
- When a user starts typing in the location picker, a loading spinner appears while the search hasn't finished loading
- If no results are found a message indicating this is shown
> Added feedback to location input.

- webofneeds/won-owner-webapp/src/main/webapp/app/components/cards/other-card.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/cards/persona-card.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/cards/pokemon-raid-card.jsx
Fixes faulty personaIcon image in other-cards, persona-cards and pokemon-raid cards
> Fixes Persona Icons

- webofneeds/won-owner-webapp/src/main/webapp/app/app.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/svg-icon.js
- Fixes: Elm components would not render svg sprites correctly
- The won-icon webcomponent has been updated to look up the name of the icon in a map generated from the svg files
> Fixed icon loading for elm components

- webofneeds/won-owner-webapp/src/main/webapp/app/components/cards/other-card.jsx
> Fix faulty persona-icon in other-card

- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-messages.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/location-picker.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/travel-action-picker.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/group-atom-messages.jsx
Fixes location markers in locationbased pickers
Fixes calling loadPrevMessages with a wrong parameter which resulted in loading ALL remaining messages of a connection
> - Fixes fetch of all messages

- webofneeds/won-owner-webapp/src/main/webapp/app/redux/state-store.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js
> Fixes fetching of non-connected connections for owned atoms

- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-menu.jsx
Always enable tabs for atom-info
> Do not show any socket tabs as inactive anymore

- webofneeds/won-owner-webapp/src/main/webapp/package-lock.json
- webofneeds/won-vocab/src/main/resources/ontology/ext/won-ext-valueflows.ttl
- webofneeds/won-vocab/src/main/resources/utils/generate-docs/widoco.sh
> Add won-ext-valueflows ontology

- webofneeds/won-owner-webapp/src/main/webapp/app/components/socket-add-atom.jsx
> Fixes issue #3291

- webofneeds/won-vocab/src/main/resources/ontology/won-workflow-widoco/description-en.md
- webofneeds/won-vocab/src/main/resources/utils/generate-docs/widoco.sh
the workflow ontology is there, but the docs can't be generated
The docs can be generated for the workflow ontology
> Add generation of won-workflow ontology docs

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/api/wikidata-api.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/cards/other-card.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/cards/pokemon-raid-card.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/cards/snippets/holder-snippet.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/wikidata-picker.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/viewer/wikidata-viewer.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/process-reducer.js
- webofneeds/won-owner-webapp/src/main/webapp/app/redux/state-store.js
- webofneeds/won-owner-webapp/src/main/webapp/app/redux/utils/process-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_holder-snippet.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_other-card.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_pokemon-raid-card.scss
- Fixes broken WikiData Link in wikiDataViewer
- moved wikidata search and fetch into sep. file
- adapted "loading"-process from atom and use it for wikiData/externalData in order to avoid duplicate fetches (performance enhancement)
> Fix  wikidatalink fetch

- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-messages.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/group-atom-messages.jsx
> fix msg component problems

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/atom-reducer/reduce-connections.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/atom-reducer/reduce-messages.js
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/process-reducer.js
- webofneeds/won-owner-webapp/src/main/webapp/app/redux/selectors/general-selectors.js
- Fixes: Wrong state handling of processState for agreementDataset
- Computing state change in FetchMessagesSuccess
-
-
> Fix process State & getAtomUriFromConnectionUri

- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-messages.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/group-atom-messages.jsx
- Clicking the header of an open chat will show the atom incl. the connection
> Adds click handler in chats header

- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-card-grid.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-content/atom-content-chats.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-content/atom-content-socket.jsx
> Moves add buttons to the front/top

- webofneeds/won-node/src/main/java/won/node/camel/processor/general/ToOwnerSender.java
- webofneeds/won-node/src/main/java/won/node/service/persistence/OwnerManagementService.java
When an owner does not register after the node starts - but has registered before - sending messages to that owner causes camel to create a queue for that owner, and the messages are put in that queue. If the owner never comes back, that queue will eventually overflow, causing all message delivery to fail.
As long as an owner is not registered, no messages are queued.
Owners may miss messages
> Drop messages for owners that are not registered

- webofneeds/won-node/src/main/java/won/node/camel/processor/general/ToOwnerSender.java
- webofneeds/won-node/src/main/java/won/node/service/persistence/OwnerManagementService.java
- webofneeds/won-node/src/main/resources/spring/component/broker/activemq.xml
> Fix  activemq inactive queues

- webofneeds/won-node/src/main/java/won/node/camel/processor/general/ToOwnerSender.java
- webofneeds/won-node/src/main/java/won/node/service/persistence/OwnerManagementService.java
> Fix  queue name handling

- webofneeds/won-node/src/main/java/won/node/camel/processor/general/ToNodeSender.java
- webofneeds/won-node/src/main/java/won/node/camel/processor/general/ToOwnerSender.java
- webofneeds/won-node/src/main/java/won/node/service/persistence/OwnerManagementService.java
Messages remain in node's queues forever
Messages expire after 20 seconds
Clients that expect messages not to expire will not work after this PR.
> Expire outgoing messages

- webofneeds/won-core/src/main/java/won/protocol/jms/WonJmsConfiguration.java
- webofneeds/won-node/src/main/java/won/node/camel/processor/general/ToOwnerSender.java
- webofneeds/won-node/src/main/java/won/node/service/persistence/OwnerManagementService.java
> Fix QOS settings for owner/node communication

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js
Fixes faulty promise chaining for message/connection fetches
> Fixes mishap due to return of promise and not value

- webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js
> Adds failsafe for empty wonMessage

- webofneeds/won-owner-webapp/src/main/webapp/app/redux/state-store.js
- webofneeds/won-owner-webapp/src/main/webapp/fetch-worker.js
- fixes registration (anon and email)
- fixes 410 (atom deleted) handling
> Feat  fix worker error

- webofneeds/won-owner-webapp/src/main/java/won/owner/web/rest/RestAtomController.java
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-afterparty.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-band-search.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-breakfast.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-goods-transport-offer.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-goods-transport-search.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-interest.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-job-search.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-musician-search.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-rehearsal-room-search.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-rent-real-estate-offer.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-rent-real-estate-search.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-rideshare-offer.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-sightseeing.js
- Currently many (all usecases that used a query) are not working anymore due to a refactoring issue (won.defaultContext was moved to vocab.defaultContext)
- Fetching the Owned Meta Atoms is processed in a synchronous for loop (every metaAtom is fetched after the other)
- Fetch and Collect MetaAtoms with a parallelStream
- Fix Broken UseCases
> Fix  usecases enhance backendfetch

- webofneeds/won-matcher-service/src/main/java/won/matcher/service/crawler/actor/WorkerCrawlerActor.java
Causes the matcher to give up after receiving a 403 response for a resource.
- Fixes: N/A
-
-
-
> Let Matcher give up after 403

- webofneeds/won-owner-webapp/src/main/webapp/app/components/group-atom-messages.jsx
Forwarded Message envelopes are filtered out in the group-chats (only original/forwarded message is displayed)
this causes the state to (sometimes) leave forwardmessage-envelopes in a state of unread since we set the markMessageAsRead upon visibilty within the chat. this change/fix ensures that all non-displayed and unread envelopes are markedAsRead
> Fix unread messages bug in group-atom-messages

- webofneeds/won-auth/src/test/resources/won/opreq/spec/opreq-018.ttl
- webofneeds/won-auth/src/test/resources/won/opreq/spec/opreq-020.ttl
- webofneeds/won-auth/src/test/resources/won/opreq/spec/opreq-022.ttl
- webofneeds/won-auth/src/test/resources/won/opreq/spec/opreq-024.ttl
- webofneeds/won-auth/src/test/resources/won/opreq/spec/opreq-025.ttl
- webofneeds/won-auth/src/test/resources/won/opreq/spec/opreq-026.ttl
- webofneeds/won-vocab/src/main/resources/ontology/ext/won-ext-schema.ttl
- No acl before
- Members can see EventSocket Connections of their organizations
- Event Attendees can see each other
- Event Attendees can see Event Holder and Organization
> Event Auth

- webofneeds/won-owner-webapp/src/main/java/won/owner/pojo/ServerSideConnectPayload.java
> Improve javadoc

- webofneeds/won-vocab/src/main/resources/ontology/won-auth.ttl
- [] Documentation content changes
wasn't a bug yet but some terms were missing in the ontology. Also, used the soon-to-be-supported markup for linking to ontology terms here and there.
- Fixes: N/A
-
-
-
> Improve  won auth ontology

- webofneeds/won-docker/image/nginx/nginx.conf
- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-map.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/location-picker.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/travel-action-picker.jsx
No OSM Tiles Proxy needed anymore
> Remove osm tiles proxy

- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-content/atom-content-auth.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/redux/state-store.js
- webofneeds/won-owner-webapp/src/main/webapp/app/redux/utils/atom-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/fetch-worker.js
- webofneeds/won-owner-webapp/src/main/webapp/parseAtom-worker.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_atom-content-auth.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_atom-messages.scss
- Adds overscroll behaviour for chat-message views (minor improvement)
- Stores auth graph with full uris now (not compacted anymore)
- Display more info in the ACL tab (requestedBy, bearer, provideAuthInfo...)
> Feat  acl expanded

- webofneeds/won-owner-webapp/src/main/java/won/owner/web/service/ServerSideActionService.java
Befor this commit, ssc does not work if both atoms are already present.
- Fixes: N/A
-
-
-
> Fix server-side connect

- webofneeds/won-owner-webapp/src/main/java/won/owner/web/WonOwnerMailSender.java
- webofneeds/won-owner-webapp/src/main/java/won/owner/web/service/ServerSideActionService.java
- webofneeds/won-owner-webapp/src/main/webapp/sw.js
Deep links from emails or notifications take the user to the webapp but do not force a login, so depending on the session state, the user sees the external view or the internal view. Really confusing for a user.
Deep links hava an additional `requireLogin=true` parameter that can be used by the webapp to trigger a session check and if not logged in, a modal login dialog.
> Add requireLogin parameter to deeplinks

- webofneeds/won-owner-webapp/src/main/java/won/owner/web/WonOwnerMailSender.java
- webofneeds/won-owner-webapp/src/main/java/won/owner/web/websocket/WonWebSocketHandler.java
- webofneeds/won-owner-webapp/src/main/resources/mail-templates/anonymous.vm
- webofneeds/won-owner-webapp/src/main/resources/mail-templates/atommessage-notification.vm
- webofneeds/won-owner-webapp/src/main/resources/mail-templates/close-notification.vm
- webofneeds/won-owner-webapp/src/main/resources/mail-templates/connect-notification.vm
- webofneeds/won-owner-webapp/src/main/resources/mail-templates/conversation-notification.vm
- webofneeds/won-owner-webapp/src/main/resources/mail-templates/hint-notification.vm
- webofneeds/won-owner-webapp/src/main/resources/mail-templates/multiple-hints-notification.vm
- webofneeds/won-owner-webapp/src/main/resources/mail-templates/system-deactivate-notification.vm
- webofneeds/won-owner-webapp/src/main/resources/mail-templates/systemclose-notification.vm
Mail notifications improved
Notification mails are not very informative
There is differentiation of 
* Whether the sender or recipient is a Persona, a group chat, or another type of atom
* Whether we were able to extract some kind of label for an atom or not
* Whether the connection a message was sent in is a chat connection or another type
> Improve notification email wording

- webofneeds/won-owner-webapp/src/main/webapp/app/actions/account-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/atoms-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js
- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-content/atom-content-auth.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-editor/create-atom.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/modal-dialog.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/socket-add-atom.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/view-reducer.js
- webofneeds/won-owner-webapp/src/main/webapp/app/redux/state-store.js
- webofneeds/won-owner-webapp/src/main/webapp/app/redux/utils/atom-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/fetch-worker.js
- webofneeds/won-owner-webapp/src/main/webapp/parseAtom-worker.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_atom-content-auth.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_atom-messages.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_modal-dialog.scss
Currently there is no real check if the session is expired, it is only checked if the user seems to be "logged in" in the redux-state, however this does not reflect the real login state itself.
- Refactored ensureLoggedIn functionality to actually check the loginState
- Removed the showTermsDialog that is pushed when no user is not logged in into the respective action
- Refactored the ensureLoggedIn functionality to open a modal dialog asking the user to login or create an anon-account, and proceed with the chosen action (currently create or connect) as a "success"-callback
- Changed the login function to send a login request even if the redux-state seems to have a logged in …
> Fix  handletimeout

- webofneeds/won-owner-webapp/src/main/java/won/owner/web/rest/BridgeForLinkedDataController.java
The owner webapp cannot authenticate using WoN Bearer tokens
It can
> Pass Auth token through linkeddata bridge

- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-editor/create-atom.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/socket-add-atom.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/redux/utils/atom-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/app/won-label-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/config/detail-definitions.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-event.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-organization.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-persona.js
- New Icons for UseCases
- Implement UseCaseGroup "Corporate"
- Button labels
- Fixes #3358
> Labels, UseCases reordered, Icons

- webofneeds/won-owner-webapp/src/main/webapp/app/pages/react/connections.jsx
- Coming to a connection request from notification mail, view always looks like chat view.
- If the requested connection has no Chat- or GroupSocket, redirect to detail view of the requester atom with available actions (accept, decline)
> Don't show chat view if no chat exists

- webofneeds/won-owner-webapp/src/main/webapp/app/app.js
- After tab is inactive for longer time, connection gets lost without letting the user know
- Reconnect if necessary after reactivating the tab
> Fix Loosing Connection

- webofneeds/won-node/src/main/java/won/node/service/persistence/ConnectionService.java
> Omit target atom/socket checks if access denied

- webofneeds/won-owner-webapp/src/main/webapp/app/pages/react/connections.jsx
- Fixes: #3374
- Check if targetAtom is loaded before reading socket
> Make sure targetAtom is loaded to get targetSocket

- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-content.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-content/atom-content-details.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-content/atom-content-tag-sockets.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-feed.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-header-feed.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/details/viewer/image-viewer.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/components/feed-items/generic-feed-item.jsx
- webofneeds/won-owner-webapp/src/main/webapp/app/reducers/atom-reducer/parse-atom.js
- webofneeds/won-owner-webapp/src/main/webapp/app/redux/selectors/general-selectors.js
- webofneeds/won-owner-webapp/src/main/webapp/app/redux/selectors/process-selectors.js
- webofneeds/won-owner-webapp/src/main/webapp/app/redux/state-store.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/atom-builder.js
- webofneeds/won-owner-webapp/src/main/webapp/app/service/vocab.js
- webofneeds/won-owner-webapp/src/main/webapp/app/won-label-utils.js
- webofneeds/won-owner-webapp/src/main/webapp/config/details/basic.js
- webofneeds/won-owner-webapp/src/main/webapp/parseAtom-worker.js
- webofneeds/won-owner-webapp/src/main/webapp/style/_atom-feed.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_atom-header-big.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_atom-header-feed.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_connection-selection-item-line.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_elevation.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_feed-item.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_image-viewer.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_inventory.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_speech-bubble.scss
- Fixes: #3379 (NewsArticles ar not shown)
- fixes #3379
- Adds a "Feed" in the Detail Tab of every Atom that has stored Connections in the state (happens when at least one connContainer request is successful)
- The Feed shows the Newest 15 connection changes (or less)
> Feature Atom Feed

- webofneeds/won-owner-webapp/src/main/webapp/style/_chattextfield.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_connection-message.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_elevation.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_referenced-message-content.scss
- webofneeds/won-owner-webapp/src/main/webapp/style/_speech-bubble.scss
Fixes speechbubble positioning and shadows
> Fix  speechbubble

- webofneeds/won-owner-webapp/src/main/java/won/owner/web/websocket/WonWebSocketHandler.java
> Fix test for owned atoms

- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-event.js
- webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-project.js
- Projects have no GroupChat
- GroupChat added to Project for better communication
> Add Group Chat to Project
