researchstudio-sat/webofneeds

webofneeds/won-bot/src/main/java/won/bot/framework/events/action/BaseEventBotAction.java, webofneeds/won-bot/src/main/java/won/bot/framework/events/event/impl/ErrorEvent.java, webofneeds/won-bot/src/main/java/won/bot/framework/events/event/impl/TestFailedEvent.java, webofneeds/won-bot/src/main/java/won/bot/framework/events/event/impl/TestFinishedEvent.java, webofneeds/won-bot/src/main/java/won/bot/framework/events/event/impl/TestPassedEvent.java, webofneeds/won-bot/src/main/java/won/bot/framework/events/listener/BaseEventListener.java, webofneeds/won-bot/src/test/java/won/bot/ContextExposingBot.java, webofneeds/won-bot/src/test/java/won/bot/IntegrationtestBot.java, webofneeds/won-bot/src/test/java/won/bot/integrationtest/SecurityBotTests.java, webofneeds/won-bot/src/test/java/won/bot/integrationtest/failsim/BaseEventListenerContextDecorator.java, webofneeds/won-bot/src/test/java/won/bot/integrationtest/failsim/ConstantNewEventURIDecorator.java, webofneeds/won-bot/src/test/java/won/bot/integrationtest/failsim/ConstantNewNeedURIDecorator.java, webofneeds/won-bot/src/test/java/won/bot/integrationtest/failsim/DelayedDuplicateMessageSenderDecorator.java, webofneeds/won-bot/src/test/java/won/bot/integrationtest/failsim/DuplicateMessageSenderDecorator.java, webofneeds/won-bot/src/test/java/won/bot/integrationtest/security/DelayedDuplicateMessageSendingConversationBot.java, webofneeds/won-bot/src/test/java/won/bot/integrationtest/security/DuplicateMessageSendingConversationBot.java, webofneeds/won-bot/src/test/java/won/bot/integrationtest/security/DuplicateMessageURIFailureBot.java, webofneeds/won-bot/src/test/java/won/bot/integrationtest/security/DuplicateNeedURIFailureBot.java, webofneeds/won-cryptography/src/main/java/won/protocol/message/processor/impl/KeyForNewNeedAddingProcessor.java, webofneeds/won-owner/src/main/java/won/owner/messaging/OwnerWonMessageSenderJMSBased.java
Four bots are implemented, the class ```won.bot.integrationtest.SecurityBotTests``` is their junit test class. The bots communicate with the junit test through special events (TestFailedEvent, TestPassedEvent, ErrorEvent) that the test class reacts to using Assert.fail(message) if appropriate. This communication structure makes it necessary for the bots to expose their EventListenerContext, otherwise the test code would not be able to register event listeners for these, normally bot-internal, events.
=> Added security test bots

webofneeds/won-bot/src/main/java/won/bot/framework/bot/base/EventBot.java, webofneeds/won-core/src/main/java/won/protocol/jms/NeedBasedCamelConfiguratorImpl.java, webofneeds/won-core/src/main/java/won/protocol/jms/NeedProtocolCamelConfigurator.java, webofneeds/won-core/src/main/java/won/protocol/jms/OwnerProtocolCommunicationService.java, webofneeds/won-core/src/main/java/won/protocol/message/WonMessageBuilder.java, webofneeds/won-core/src/main/java/won/protocol/message/processor/impl/UriConsistencyCheckingWonMessageProcessor.java, webofneeds/won-matcher/src/main/java/won/matcher/protocol/impl/MatcherProtocolCommunicationServiceImpl.java, webofneeds/won-node/src/main/java/won/node/camel/NeedProtocolCommunicationServiceImpl.java, webofneeds/won-node/src/main/java/won/node/camel/processor/general/NeedProtocolOutgoingMessagesProcessor.java, webofneeds/won-owner-webapp/src/main/webapp/app/service/message-builder.js, webofneeds/won-owner-webapp/src/main/webapp/app/service/won-service.js, webofneeds/won-owner/src/main/java/won/owner/messaging/OwnerProtocolCommunicationServiceImpl.java, webofneeds/won-owner/src/main/java/won/owner/messaging/OwnerWonMessageSenderJMSBased.java
Works again: a need from node on server X is able to connect to another need on server Y. For example, the EchoBotApp and SimpleToNeedConversationTest both work when given a list of two different node source uris.
=> Bugfix msg sender node

webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/overview-incoming-requests/overview-incoming-requests.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/overview-matches/overview-matches.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/overview-sent-requests/overview-sent-requests.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/overview-title-bar.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/owner-title-bar.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-owner-messages/post-owner-messages.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/connection-reducer.js, webofneeds/won-owner-webapp/src/main/webapp/app/selectors.js
There's now a memoized selector function `selectAllByConnections` to get the structure that used to be in `state.getIn(['connections', 'connections'])`.  I've ported all occurances of the later i've found to that selector.
Most of these updated snippet's are copy-pasta code anyway and should be extracted into functions in `selectors.js` anyway, but i've had enough refactoring for a while 
Btw, immutablejs-maps have a `.filter(...)` on their own - there's no need to copy(!) their contents into vanilla-js objects by calling `.toJS()`. I've updated one occurance in `owner-title-bar.js` as example:
``` javascript
hasIncomingRequests: state.getIn(['connections', 'connections'])
.filter(conn =>
conn.get('hasConnectionState') === won.WON.RequestReceived
&& conn.get('belongsToNeed') === …
```
=> Removed connectionsDeprecated from state.

webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/dynamic-textfield.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/request-item-line.js, webofneeds/won-owner-webapp/src/main/webapp/app/messaging-agent.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/event-reducer.js, webofneeds/won-owner-webapp/src/main/webapp/app/selectors.js, webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js, webofneeds/won-owner-webapp/src/main/webapp/app/utils.js, webofneeds/won-owner-webapp/src/main/webapp/app/won-message-utils.js, webofneeds/won-owner-webapp/src/main/webapp/gulpfile.js, webofneeds/won-owner-webapp/src/main/webapp/package.json, webofneeds/won-owner-webapp/src/main/webapp/rework.html
There was a bug that―for incoming connection requests―`unreadEvents[cnctUri].uri` didn’t match any uri in the list of own events. The message handling was just using the first successful framing result―essentially yielding the remote counterpart of the own event, which of course had a different uri. A selector function in the feed-view was crashing as a result, while trying to access properties of an undefined event.
The code is now returning the correct event. What’s more, all events now also contain have property with their counterpart attached, as you can see in the state. Especially for incoming requests, this counterpart holds valuable information.
=> Fix consistent events - accepting incoming requests working

webofneeds/won-bot/src/main/java/won/bot/framework/events/action/impl/CreateEchoNeedWithFacetsAction.java, webofneeds/won-core/src/main/java/won/protocol/repository/ConnectionRepository.java, webofneeds/won-core/src/main/java/won/protocol/service/LinkedDataService.java, webofneeds/won-core/src/main/java/won/protocol/service/NeedInformationService.java, webofneeds/won-core/src/main/java/won/protocol/util/WonRdfUtils.java, webofneeds/won-node-webapp/src/main/java/won/node/web/LinkedDataWebController.java, webofneeds/won-node-webapp/src/main/resources/spring/node-context.xml, webofneeds/won-node/src/main/java/won/node/service/impl/LinkedDataServiceImpl.java, webofneeds/won-node/src/main/java/won/node/service/impl/NeedInformationServiceImpl.java, webofneeds/won-owner-webapp/src/main/java/won/owner/web/WonOwnerMailSender.java, webofneeds/won-owner-webapp/src/main/java/won/owner/web/websocket/WonWebSocketHandler.java, webofneeds/won-utils/won-utils-mail/src/main/java/won/utils/mail/WonMailSender.java
Implemented #444 in a following way:
extended with connections and events need data is accessed via separate URL, - need resource URI plus 'deep' path fragment. Optionally, so that limited number of events and connections are returned, one can specify the size of the connections/events layer.
Example URL:
https://example.com:8443/won/resource/need/1693454629993447400/deep?layer-size=5
This returns need resource description, plus 5 (latest by their events) connections resource descriptions, plus for each connection 5 latest events resource descriptions.
From the Owner client-side the requests should be done via the owner server linked data bridge (because of the webid proving - the need deep data includes confidential events data), for example: …
=> Feat deeper ld

webofneeds/won-owner-webapp/src/main/webapp/app/actions/account-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/load-action.js, webofneeds/won-owner-webapp/src/main/webapp/app/messaging-agent.js, webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js, webofneeds/won-owner-webapp/src/main/webapp/app/won-message-utils.js
With this all rdf-resources get fetched in one go at page startup. There's only one caveats though: As we don't have the uris of the connections and events from the outset, we can't set their cache-state to pending or lock requests to them. So there's the possibility, that up to 3 request-slots are blocked with unnecessary requests that are subsumed by the deep triple set. We'd need to either lock the whole store or make the locking mechanism aware of our data-structure (so it doesn't lock other needs), to even partially address this.
=> Feat deepld clientside

webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js, webofneeds/won-owner-webapp/src/main/webapp/app/service/won.js
Before: when accepting a request then getting chat messages―which causes the connection-rdf to be reloaded―the connection had two triples with the predicate `hasConnectionStates` in the rdfstore which showed up as array in the state. As a result it didn't show up in the messages-tab as it wasn't registered as open.
=> Fix duplicatepredicates

webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js, webofneeds/won-owner-webapp/src/main/webapp/app/messaging-agent.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/connection-reducer.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/event-reducer.js
With this patch all chat-messages should use the owner-server's timestamps and thus sort correctly. as As @quasarchimaere suggested, pending messages now have a boolean flag, that allows displaying them at the very bottom.
See extended chat-messages for more information.
=> Fix sorting chatmessages

webofneeds/won-owner-webapp/src/main/resources/spring/owner-security.xml, webofneeds/won-owner-webapp/src/main/webapp/app/actions/account-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/load-action.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/app_jspm.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/owner-title-bar.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post/post.html, webofneeds/won-owner-webapp/src/main/webapp/app/components/post/post.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/visitor-title-bar.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/connection-reducer.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/event-reducer.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/posts-reducer.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/reducers.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/user-reducer.js, webofneeds/won-owner-webapp/src/main/webapp/app/utils.js, webofneeds/won-owner-webapp/src/main/webapp/app/won-message-utils.js
Merge #529 first
Turns out our action-creators for login, page-load, etc were calling and being called by other action-creators in a slightly confusing mess. Also there was a distinct action dispatched for every reducer. The mess should be untangled via this branch and redundancies removed―there's one action-creator for login and one for page-load now. They get called directly, fetch all relevant data and dispatch one main action that carries the data. 
Without this, we would have needed to load need for the visitors-view at multiple places, adding even more complexity to the call-graph.
=> Refac login and pageload

webofneeds/won-core/src/main/java/won/protocol/rest/RDFMediaType.java, webofneeds/won-owner-webapp/src/main/java/won/owner/web/rest/BridgeForLinkedDataController.java
At the linked data bridge: if you get a link like  <https://www.matchat.org/owner/rest/linked-data/?uri=http:%2F%2Fevil.com%2F> the server would just pass through the html and any javascript contained therein, thus undermining any protection against cross-origin requests. If you'd click such a link, an attacker could hijack your session.
=> @ld-bridge: filtering out responses that would have been a huge same-origin security leak

webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/load-action.js, webofneeds/won-owner-webapp/src/main/webapp/app/app_jspm.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/visitor-title-bar.js, webofneeds/won-owner-webapp/src/main/webapp/app/configRouting.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/reducers.js, webofneeds/won-owner-webapp/src/main/webapp/app/selectors.js
When you pasted a uri for the post-view while the page already was loaded (thus after the `initialPageLoad` action was created and dispatched) the need wouldn't get loaded. The assumption before was that pasting and entering always triggers a page-reload. However when the base-url matches, the browser only "jumps" to the new fragment-identifier, without reloading and thus without triggering `initialPageLoad`. 
This patch adds a listener to route-changes and causes the post to be loaded if the user would run into an unitialized post-view.
This branch also include simple access managment.
Check the following behaviours:
* once logged in and once logged out do:
* reload on posts-overview
* while on some other view (e.g. landing-page): paste link to posts-overview
* reload on post-detail view …
=> Fix visitorsviewloading + simple access managment

webofneeds/won-node/src/main/java/won/node/camel/processor/annotation/FixedMessageProcessor.java, webofneeds/won-node/src/main/java/won/node/camel/processor/annotation/FixedMessageReactionProcessor.java, webofneeds/won-node/src/main/java/won/node/camel/processor/facet/ownerFacet/HintFeedbackMessageFromOwnerOwnerFacetImpl.java, webofneeds/won-node/src/main/java/won/node/camel/processor/fixed/ActivateNeedMessageProcessor.java, webofneeds/won-node/src/main/java/won/node/camel/processor/fixed/ActivateNeedMessageReactionProcessor.java, webofneeds/won-node/src/main/java/won/node/camel/processor/fixed/CreateNeedMessageProcessor.java, webofneeds/won-node/src/main/java/won/node/camel/processor/fixed/CreateNeedMessageReactionProcessor.java, webofneeds/won-node/src/main/java/won/node/camel/processor/fixed/DeactivateNeedMessageProcessor.java, webofneeds/won-node/src/main/java/won/node/camel/processor/fixed/DeactivateNeedMessageReactionProcessor.java, webofneeds/won-node/src/main/java/won/node/camel/processor/general/MessageTypeSlipComputer.java, webofneeds/won-node/src/main/java/won/node/camel/processor/general/UriAlreadyUsedCheckingWonMessageProcessor.java, webofneeds/won-node/src/main/java/won/node/camel/route/fixed/WonMessageRoutes.java, webofneeds/won-node/src/main/resources/spring/component/camel/node-camel.xml
What to test:
* create a need - the GUI will react much faster now because success/failure messages arrive instantly
* generally afflicted actions are activate, deactivate, create
* a bug was fixed regarding hintFeedback - there should not be any failuremessages in response to such a message any more (I think, however, that these messages were swallowed prior to this PR because of wrong message ordering)
fixes #595
=> Fix message processing and reaction ordering

webofneeds/won-owner-webapp/src/main/webapp/app/actions/account-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/messaging-agent.js, webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js, webofneeds/won-owner-webapp/src/main/webapp/app/service/won.js
WARN: Despite the title this PullRequest does not handle a user-close of a connection yet (# 569)
fixes #610 -> GUI should react to a partner close:
Testing:
1) Create new need
2) Connect with the DebugBot Request
3) type "close"
result -> you should receive a message that will close this connection (message should disappear from the gui)
1) Create new need
2) Close Post
result -> you should receive messages that close the respective connections -> the messages are marked as #Closed in the state (visible via console)
=> Feat closeonpartnerclose fixes#610

webofneeds/won-owner-webapp/src/main/webapp/app/components/post-item-line.js
The Indicators in the post overview should display whether or not a post even has the certain type of connection, if it doesnt it will be shown as grey (unclickable) if it does it will be shown as a light red clickable button, the counters for new connections are implemented in this view although they are currently not working due to a different bug with the counters
=> Feat post overview counters

webofneeds/won-owner-webapp/src/main/webapp/app/reducers/drafts-reducer.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/event-reducer.js
fixes #607 
after a logout the state for events: and drafts: (see console output) should be wiped -> before all the events and drafts where still in the state and another login had data from an old session
=> Fix clear state #607

webofneeds/won-owner-webapp/src/main/webapp/app/components/chat-textfield.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/need-textfield.js
The replace fixes odd behaviour of FF, which inserts  a `<br>` at the end after the first space is typed -- unless the space is the first character in the field. \*sigh\* #plzfixcontenteditable 
Resolves #679
=> Filtering `<br>` from end of mediumjs.value()

webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/debugbot/CreateDebugNeedWithFacetsAction.java, webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/needlifecycle/AbstractCreateNeedAction.java, webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/needlifecycle/CreateNeedWithFacetsAction.java, webofneeds/won-bot/src/main/java/won/bot/impl/DebugBot.java, webofneeds/won-core/src/main/java/won/protocol/util/NeedBuilder.java, webofneeds/won-core/src/main/java/won/protocol/util/NeedBuilderBase.java, webofneeds/won-core/src/main/java/won/protocol/util/NeedModelBuilder.java, webofneeds/won-core/src/main/java/won/protocol/vocabulary/WON.java, webofneeds/won-vocab/src/main/resources/ontology/won_ontology_v1.0.ttl
This PR adds two functionalities, which are achieved by adding flags to a need and the matching services respecting the flags.
When a need is flagged with DoNotMatch, it is not supposed to receive any hints, nor are other needs supposed to receive hints about it.
When a need is flagged with UsedForTesting, it is may only be sent hints to other needs that have this flag.
The PR adds a new property, `won:hasFlag`, and two Resources, `won:DoNotMatch` and `won:UsedForTesting`, the intended use is on the need resource:
```
[need] won:hasFlag [flag]
```
=> Feat do not match

webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js
Single conversations no longer hang and the null OID message is gone.
Replaced old promise-hell implementation with crawlable query implementation - that fixed it.
fixes #651 
fixes #691
=> Fixed hanging conversations

webofneeds/won-owner-webapp/src/main/java/won/owner/web/WonOwnerMailSender.java, webofneeds/won-owner-webapp/src/main/java/won/owner/web/websocket/WonWebSocketHandler.java
A few changes to the way the owner app sends emails:
* emails are only sent when no websocket session is found
* text was improved 
* links were improved
Not all the links work, though, as it is currently unclear how to link directly into a conversation - so this link doesn't work completely, but it gets you to the post view at least.
How to test:
* deploy to integration-test
* use two user accounts with real email addresses
* create two needs that will be matched, one in each account
* log out quickly with account A after creating the need
* check that you got the hint email of account A
* go to account B, request contact on the hint
* check that you got the open email in account A
* log in with A, accept the conversation, send a message
* reply with B then log out
* reply with A
* check …
=> Fix too many emails

webofneeds/won-bot/src/main/java/won/bot/app/LastSeenNeedsMatcherApp.java, webofneeds/won-bot/src/main/resources/spring/app/lastSeenNeedsMatcherApp.xml
This bot matches the two needs it has seen last, sending a hint to the newer need. Useful for testing ownerapp-to-ownerapp without a functioning matcher
=> added lastNeedsSeenMatcher app

webofneeds/won-core/src/main/java/won/protocol/service/LinkedDataService.java, webofneeds/won-node-webapp/src/main/java/won/node/web/LinkedDataWebController.java, webofneeds/won-node/src/main/java/won/node/service/impl/LinkedDataServiceImpl.java
adding `deep=true` in the HTTP request for an event container causes the events' datasets to be included in the response
fixes #746
=> added capability to query event container optionally with deep=true

webofneeds/won-owner-webapp/src/main/webapp/app/components/feed-item.js, webofneeds/won-owner-webapp/src/main/webapp/app/won-label-utils.js
Test by running the debugbot and look a the feed after creating a need. Keep an eye on the descriptions as you move your connections through connected/closed states.
fixes #718
=> improved labels describing the connection state in the feed view

webofneeds/won-owner-webapp/src/main/webapp/app/messaging-agent.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/message-reducers.js
This change will introduce heartbeat checks, heartbeats are sent by the server yet up until this point we simply ignored them on the client side.
now we have a method that will process a received heartbeat by setting a var (in this case the missedHeartbeat counter) back to 0. Furthermore we added a method that checks how many heartbeats have been missed in a certain interval (in our case every 30 seconds) and if the missedHeartbeat counter is bigger than 3 we will dispatch a logout event to clear our state.
How to test: after the server has lost or closed the session the heartbeats will not get sent over the websocket anymore and thus increasing the missedHeartbeat counter every interval check (so the logout should occur roughly 2minutes after the session is lost)
This Pull Request …
=> Feat session handling fixes

webofneeds/won-owner-webapp/src/main/java/won/owner/web/rest/BridgeForLinkedDataController.java, webofneeds/won-owner-webapp/src/main/webapp/app/components/open-request.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-info.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-item-line.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/send-request.js, webofneeds/won-owner-webapp/src/main/webapp/style/won.scss
Fix #822
This pullrequest inserts links (in postoverview, post-info, request and match views) to access the corresponding connection/need/event data
BE AWARE:
in order to make the rest/linked-data view accessible within the browser, i needed to alter the BridgeForLinkedDataController to accept text/html again. Unfortunately the response status needed to be something other than 200 (so i kept the bad gateway response) because the redux-ui-router would have linked me to the landingpage for some in my opinion unknown reason
=> implemented developer data links

webofneeds/conf/logback.xml, webofneeds/conf/logback_error.xml, webofneeds/conf/logback_info.xml, webofneeds/conf/logback_warn.xml, webofneeds/won-owner/src/main/java/won/owner/messaging/OwnerProtocolCommunicationServiceImpl.java, webofneeds/won-owner/src/main/java/won/owner/messaging/OwnerWonMessageSenderJMSBased.java, webofneeds/won-owner/src/main/java/won/owner/messaging/WonNodeRegistrationEvent.java, webofneeds/won-owner/src/main/java/won/owner/messaging/WonNodeRegistrationEventPublisher.java, webofneeds/won-owner/src/main/resources/spring/component/ownerProtocolCommunicationService/wonNodeRegistrationEventPublisher.xml, webofneeds/won-owner/src/main/resources/spring/owner-jmsonly.xml
* owner now is able to "wait" until wonnode is up
* log messages are reduced in case wonnode is not up 
* for more details see fixes #850 
* deployed on intergration test
=> owner try registering at default wonnode until success

webofneeds/won-docker/deploy/int_satsrv06/docker-compose.yml, webofneeds/won-docker/deploy/master_satsrv06/docker-compose.yml
use the follwing mail addresses for the mail bot now:
* master: won-internal@researchstudio.at
* int: mail2won.int@gmail.com
* already tested in integration-test
=> use different mail addresses for master and int mail bot deployments

webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/EventBotActionUtils.java, webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/mail/model/ActionType.java, webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/mail/model/SubscribeStatus.java, webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/mail/receive/MailCommandAction.java, webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/mail/receive/MailContentExtractor.java, webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/mail/receive/MailParserAction.java, webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/mail/receive/SubscribeUnsubscribeAction.java, webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/mail/send/WelcomeMailAction.java, webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/mail/send/WonMimeMessage.java, webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/mail/send/WonMimeMessageGenerator.java, webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/event/impl/mail/SubscribeUnsubscribeEvent.java, webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/event/impl/mail/WelcomeMailEvent.java, webofneeds/won-bot/src/main/java/won/bot/impl/Mail2WonBot.java, webofneeds/won-bot/src/main/resources/mail-templates/connect-mail.vm, webofneeds/won-bot/src/main/resources/mail-templates/hint-mail.vm, webofneeds/won-bot/src/main/resources/mail-templates/inc/footer.vm, webofneeds/won-bot/src/main/resources/mail-templates/message-mail.vm, webofneeds/won-bot/src/main/resources/mail-templates/welcome-mail.vm, webofneeds/won-bot/src/main/resources/spring/component/mail/mailContentExtractor.xml
* fixes #882, fixes #889 
* added functionality for the user to subscribe/unsubscribe to the mail bot, meaning publish all my future needs / ignore mail bot in future (opt-in/opt-out)
* created first draft of welcome mail that is sent in response to mails on the mailinglist if user has not subscribed or unsubscribed yet 
* added footer to hint/connect/message mails to send and close event using mailto links (close need functionality is not yet implemented)
=> User mail subscription

webofneeds/won-owner-webapp/src/main/resources/spring/owner-security.xml, webofneeds/won-owner-webapp/src/main/webapp/WEB-INF/web.xml, webofneeds/won-owner-webapp/src/main/webapp/index.html
improved caching headers in owner application to allow for client side caching of static resources
How to test: open the owner application, inspect the network information in the browser. After the first page view, almost all resources should cause a 304 not modified response upon page reload. 
If the page is requested again (via entering the url again), most resources should be served from the cache directly.
=> improved cache headers and landingpage config in owner application

webofneeds/won-owner-webapp/src/main/webapp/app/components/chat-textfield.js
The other events, even though this.value() was empty, were
dispatched and showed up in the chat and on the node. For
some reason they had the previously cleared value still set
as content.
Resolves #710
=> Only triggering a submit-event when a message has been entered

webofneeds/won-owner-webapp/src/main/webapp/app/selectors.js
Apparently for some success-responses the corresponding-remote-message is only saved as string. This is a quick fix, that allows a selector used by the "show more"-button to deal with these without crashing.
Test: open connection, chat around a bit, click show-more -> no more exceptions. Make sure to test with the master-branch first, so you have a events on your connections that cause the exception to begin with.
=> Fixed bug in selector used by "show more".

webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/EventBotActionUtils.java, webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/mail/receive/CreateNeedFromMailAction.java, webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/mail/receive/MailCommandAction.java, webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/mail/receive/MailContentExtractor.java, webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/mail/send/Connect2MailParserAction.java, webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/mail/send/Hint2MailParserAction.java, webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/mail/send/Message2MailAction.java, webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/mail/send/WonMimeMessageGenerator.java, webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/event/impl/command/DeactivateNeedCommandEvent.java, webofneeds/won-bot/src/main/java/won/bot/impl/Mail2WonBot.java, webofneeds/won-bot/src/main/resources/mail-templates/welcome-mail.vm, webofneeds/won-bot/src/main/resources/spring/component/mail/mailContentExtractor.xml, webofneeds/won-core/src/main/java/won/protocol/util/WonRdfUtils.java
implemented the possibility to close an open need via an e-mail that matches a takenCmdPattern (currently set to [TAKEN]) in the subject line, the mailbot will then crawl through all the created needs of that e-mail adress and close the first open need that matches the title e.g "[WANT] testneed" will be closed when the same e-mail adress sends a "[TAKEN] testneed" e-mail
=> Feat close need on taken

webofneeds/won-owner-webapp/src/main/webapp/app/components/post-info.js
The map now initialises itself *after* the location data for the need has loaded.
Resolves #983
=> @post-info: map now correctly initialises.

webofneeds/won-owner-webapp/src/main/webapp/app/components/need-textfield.js
Tags are now only delimited by white-space. Anything else is fair-game, thus enabling the use of the full range of unicode in tags.
Resolves #1039
=> Tags can now contain umlauts.

webofneeds/won-owner-webapp/pom.xml
If the won-owner-webapp project is built with 'clean' before the first 'install', the 'clean' goal used to fail. this is becaue node.js is only installed locally with the first run of 'mvn install'. This fix adds a maven profile that deactivates the npm clean command if the local installation of nodejs is not found.
To test this PR, clone this branch into a new folder and try `mvn clean`. Before this PR, this fails, with the PR, it succeeds.
=> fix for the fail of npm clean  in won-owner-webapp

webofneeds/won-owner-webapp/src/main/webapp/app/components/need-textfield.js
Test: go to create-need in FF, enter title like "asdf #asdf" and don't line-break. before this fix, the tag would contain a "\<br\>". Alternatively you can just create a need with a title and check how it turns out in any post-specific view where the title shows up.
Resolves #1080, #1052
=> Using textContent instead of innerHTML to get title.

webofneeds/won-owner-webapp/src/main/webapp/app/components/post-info.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/visitor-title-bar.js, webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js, webofneeds/won-owner-webapp/src/main/webapp/app/won-utils.js, webofneeds/won-owner-webapp/src/main/webapp/style/_need-tab-bar.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_post-messages.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_visitor-title-bar.scss
"Avatars" and title in the chat are now clickable and lead to the post-info page for the other person's need.
Resolves #1057 (mostly anyway -- for further details see "post info as first 'message'" in #1057 and #1081)
=> Fix view remote after connect #1057

webofneeds/won-owner-webapp/src/main/webapp/app/components/chat-textfield.js
When writing chat messages, the cursor should refocus the text-field, thus allowing continous writing without moving the hand to the mouse.
=> Refocusing chat-txt-field after sending a message.

webofneeds/won-owner-webapp/src/main/webapp/gulpfile.js, webofneeds/won-owner-webapp/src/main/webapp/index.html
Doesn't need systemjs as an external dependency
any more.
This *might* fix the white-screen-of-death-issue #1109 (i can't test locally as the issue only occurs on matchat)
=> Made app-bundle self-executing.

webofneeds/won-docker/image/nginx/nginx-master.conf, webofneeds/won-docker/image/nginx/nginx.conf
In both the master and the live config, the directive setting the Origin header was copied from integration-test and not changed.
=> fixed typos in nginx config

webofneeds/won-node/src/main/java/won/node/camel/route/fixed/WonMessageRoutes.java
improved transaction handling in the node
If the matcher sends a hint for a need pointing to the need itself, this raises a db level exception, which wasn't handled gracefully before. The current behaviour is that a FailureResponse is created that can't be routed back to the matcher because it isn't represented by a need. Not perfect but slightly better.
=> Fix matcher incoming routes

webofneeds/won-matcher-rescal/src/main/java/won/matcher/rescal/service/HintReader.java, webofneeds/won-matcher-rescal/src/main/python/rescal-matcher.py, webofneeds/won-matcher-rescal/src/main/python/tools/tensor_utils.py, webofneeds/won-matcher-utils/src/main/java/won/matcher/utils/tensor/TensorMatchingData.java
improve the rescal matchers scalability and performance by not computing whole mask and prediction matrices anymore. also use a needIndices file to identify the needs (in contrast to attributes) in the header file.
=> Rescal big tensor data

webofneeds/won-owner-webapp/src/main/webapp/app/components/feed/feed.html, webofneeds/won-owner-webapp/src/main/webapp/app/components/login.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/matches.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/open-request.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/overview-incoming-requests/overview-incoming-requests.html, webofneeds/won-owner-webapp/src/main/webapp/app/components/overview-posts/overview-posts.html, webofneeds/won-owner-webapp/src/main/webapp/app/components/overview-title-bar.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/owner-title-bar.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-item-line.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post/post.html, webofneeds/won-owner-webapp/src/main/webapp/app/components/send-request.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/topnav.js
css class clickable was added to some elements (mostly in the navbars) that previously used the ui-sref as a action but now use ng-click, long story short the pointer icon was not automatically present anymore, this pr fixes this and gives a visual feedback of links/buttons that can be clicked again
=> Fix visible click indicator

webofneeds/won-owner-webapp/src/main/webapp/app/reducers/reducers.js
remove connections that have a remoteNeedUri that is also from a need that the user owns, (aka do not show connections between your own needs)
=> Fix matches withownneeds #1175

webofneeds/won-matcher-service/src/main/java/won/matcher/service/common/service/http/HttpService.java
fixes #1189 
=> the json http request to the solr index didnt encode the sent data as UTF-8 => this is fixed now and special character are saved correctly in the index
=> use UTF-8 encoding in postJson Http request for Solr matcher

webofneeds/won-owner-webapp/src/main/webapp/index.html
Reduces the css-size from 22.5k (gziped) to 15.5k (gziped), 120ms download to 80ms of actual download time (560ms are spend waiting for the first byte, though). Not a big/noticeable improvement, but also almost no work.
=> Switched to minified css that's already being generated.

webofneeds/won-docker/image/owner/ssl/server.xml
On [integration-testing](https://satvm05.researchstudio.at/owner/#!/landingpage) you can see that in the response-header of e.g. app_jspm.bundle.js the content-encoding is "gzip". You should also be able to notice the speed with which the bundle load in comparison to [matchat](https://www.matchat.org/owner/#/landingpage) (if necessary, set throttling to "fast 3g" to have an even more pronounced contrast)
Make sure to also enable it in you local setup: <https://github.com/researchstudio-sat/webofneeds/issues/1198#issuecomment-327824502>
=> Enabled gzip-compression in tomcat's server.xml.

webofneeds/won-owner-webapp/src/main/webapp/app/components/chat-textfield.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/need-textfield.js, webofneeds/won-owner-webapp/src/main/webapp/gulpfile.js, webofneeds/won-owner-webapp/src/main/webapp/index.html, webofneeds/won-owner-webapp/src/main/webapp/jspm_config.js, webofneeds/won-owner-webapp/src/main/webapp/package.json
Medium.js is capable of being bundled (without extra config) now! This allows us to load bundle directly after the html finishes loading/parsing.
**before:**
(see [here](https://github.com/researchstudio-sat/webofneeds/issues/546#issuecomment-327556409) for explanation of the experiment))
**after:**
The **1 second spent queuing** for the bundle-download is gone. For some reason the bundle download is faster now but the sign-in request takes a lot longer.
=> Feat unified js

webofneeds/won-owner-webapp/src/main/webapp/app/configRouting.js
With this patch, the page-load process queries `.../owner/isSignedIn` only once.
=> Refac  removed duplicate checkloginstatus

webofneeds/won-owner-webapp/src/main/webapp/app/actions/account-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/load-action.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/feed/feed.html, webofneeds/won-owner-webapp/src/main/webapp/app/components/feed/feed.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/reducers.js, webofneeds/won-owner-webapp/src/main/webapp/app/won-message-utils.js, webofneeds/won-owner-webapp/src/main/webapp/style/_feed.scss
With this, needs are dispatched as soon as they are returned from the server (instead of waiting for all own needs to load, then waiting for all connections to load, etc, i.e. "aligning" them). This should make a improve the time to the first meaningful render for accounts with a lot of needs and/or connections.
=> Feat  login multidispatch

webofneeds/won-owner-webapp/src/main/webapp/app/components/login-form.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/topnav.js
Ui-sref doesn't update after properly when a private-id is added or removed, so I changed these usages to href's using templated strings.
=> Fixed links that were still using ui-sref.

webofneeds/won-owner-webapp/src/main/webapp/app/components/matches-flow-item.js
fixes the many requests sent to leaflet by removing the map in the tile view (for now, until we have found a better and more performant solution to include open-street-maps/leaflet)
=> "removes" won-need-map from tile view (makes leaflet too slow)

webofneeds/won-owner-webapp/src/main/webapp/app/components/feed-item-line.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/feed-item.js
Removes the (visibility of) closed connections from the feed -> we do not need to show these in the feed
=> Refac remove closedconnectionsfromfeed

webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer.js, webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js, webofneeds/won-owner-webapp/src/main/webapp/app/service/won.js
The chat-messages should have relative timestamps (e.g. "just now", "5 minutes ago") again. Timestamps should (also) show again for matches, the post-info-page, etc.
NOTE: merge after #1252
=> Fix  relative time stamps

webofneeds/won-node/src/main/java/won/node/camel/processor/general/FailResponder.java, webofneeds/won-node/src/main/java/won/node/camel/processor/general/SuccessResponder.java
should fixes #1237 
i was testing about 1 hour on master after increasing to the neweset camel version and the cyclic expections didnt occur anymore.
also dont try to send failure and success respose messages to matchers for hints
=> Improve message handling

webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/service/need-builder.js, webofneeds/won-owner-webapp/src/main/webapp/app/won-message-utils.js
* Changed the reply need creation process by adding a noHints flag to the intermediate need structure.
* Adapted won.buildNeedRdf to pick up that new flag
How to test:
1. create a need A
2. with another account, create a What's Around B need such that it will be matched with A
3. connect from B to A
4. with yet another account, create another What's Around need C such that it will be matched with A
5. observe that you do not get a hint to B
6. do the same on a system before this PR, and C will get a hint to B
=> Suppress hints for Reply needs

webofneeds/won-node/src/main/java/won/node/camel/route/fixed/WonMessageRoutes.java
* fewer redelivery attempts
* a log message
* mark the exception as handled
=> Experimental: improve camel exception handling

webofneeds/won-owner-webapp/src/main/webapp/app/components/matches-flow-item.js
Go to matches-tab using the dev-tools' mobile-simulation or on your phone -- if you press at the bottom of a tile, the feedback-buttons should show up properly. (Before, the buttons showing up would get clicked instantly)
=> Won't trigger bogus click when feedback-choice shows up.

webofneeds/conf/matcher-service/matcher-service.properties, webofneeds/won-core/src/main/java/won/protocol/model/Need.java, webofneeds/won-core/src/main/java/won/protocol/rest/DatasetResponseWithStatusCodeAndHeaders.java, webofneeds/won-core/src/main/java/won/protocol/rest/LinkedDataRestClient.java, webofneeds/won-core/src/main/java/won/protocol/util/NeedModelMapper.java, webofneeds/won-core/src/main/java/won/protocol/util/linkeddata/CachingLinkedDataSource.java, webofneeds/won-core/src/main/java/won/protocol/util/linkeddata/LinkedDataSource.java, webofneeds/won-core/src/main/java/won/protocol/util/linkeddata/LinkedDataSourceBase.java, webofneeds/won-matcher-service/src/main/java/won/matcher/service/crawler/actor/MasterCrawlerActor.java, webofneeds/won-matcher-service/src/main/java/won/matcher/service/crawler/actor/WorkerCrawlerActor.java, webofneeds/won-matcher-service/src/main/java/won/matcher/service/crawler/service/CrawlSparqlService.java, webofneeds/won-node/src/main/java/won/node/service/impl/NeedInformationServiceImpl.java
fixes #1001 
fixes #1268 
* crawl needs and connections only once
* query new needs and connections by using http query parameter "resumeafter" for needs and connections of a won node
* handle paging if won node sends previous "link" in http response with uri to further data
* sort needs in won node by modification date instead of creation date
Note:
for my testing i added an http paging header in my requests:
won/protocol/rest/LinkedDataRestClientHttps.java:131
````
@Override
public DatasetResponseWithStatusCodeAndHeaders readResourceDataWithHeaders(final URI resourceURI) {
Map<String, String> requestHeaders = new HashMap<String, String>();
requestHeaders.put(HttpHeaders.ACCEPT, this.acceptHeaderValue);
// added
requestHeaders.put("Prefer", "return=representation; max-member-count=10"); …
```
=> crawl only new needs and connections in matcher service

webofneeds/won-node/src/main/resources/db/migration/V4_1__add_persistent_logins.sql, webofneeds/won-owner-webapp/src/main/java/won/owner/web/rest/RestUserController.java, webofneeds/won-owner-webapp/src/main/resources/spring/owner-security.xml, webofneeds/won-owner-webapp/src/main/webapp/WEB-INF/web.xml, webofneeds/won-owner-webapp/src/main/webapp/app/components/login-form.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/signup/signup.html, webofneeds/won-owner-webapp/src/main/webapp/app/components/signup/signup.js, webofneeds/won-owner-webapp/src/main/webapp/app/won-utils.js, webofneeds/won-owner/src/main/resources/db/migration/V4_1__add_persistent_logins.sql
* changes signin request from post to get so we can easily pass parameters that can be
picked up by the RememberMeServices
* configures RememberMeServices in owner-security.xml
* changes login method in won-utils.js
* changes the session timeout to 1 day
How to test:
1. log in with an account
2. note there is a 'remember me' checkbox in the login popover
3. do not check that box
4. when logged in, close the window (and all other windows, so the session is closed)
5. open a new browser window
6. open the owner webapp
7. notice that you are not logged in.
8. log in again, now checking 'remember-me'
9. when logged in, close all browser windows
10. open a new browser window and open the owner webapp
11. check that you are now logged in
Note: the remember-me function survives an owner-webapp …
=> Enable remember-me in owner webapp

webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js, webofneeds/won-owner-webapp/src/main/webapp/style/_create-post.scss
fixes two things:
-the hover label/icon of the addDetail Element is showing the correct Icon and key before it is openend
-the emptytag that was always present is also stripped from the tags view now
=> fixes styling and key of addDetail Pane

webofneeds/won-owner-webapp/src/main/webapp/app/components/matches-flow-item.js, webofneeds/won-owner-webapp/src/main/webapp/app/utils.js
Matches-tiles shouldn't have an `<hr>` anymore if there's no description or address on the remote need.
=> Fix  matches hr

webofneeds/won-owner-webapp/src/main/webapp/app/components/account-menu.js, webofneeds/won-owner-webapp/src/main/webapp/app/utils.js
Issue #1222
If the username is longer than 16 characters the middle part is hidden and replaced with "...". Now there are no clashes with the name anymore.
=> Avoid text-clashes in title-bar

webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/messaging-agent.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer.js
Now the connections on both sides are closed when a user closes the connection on his side.
Fixes issue #1231
=> Fix closing connection error #1231

webofneeds/won-core/src/main/java/won/protocol/repository/ConnectionRepository.java, webofneeds/won-node-webapp/doc/linked-data-paging.md, webofneeds/won-node/src/main/java/won/node/service/impl/NeedInformationServiceImpl.java
we have to change the ordering criteria of needs and connections in order for it to be unchanging between requests: 
* for need order criteria we use creationDate (again) instead of modifiedDate
* for connection order criteria we use the creation date of the first event (corresponds to creation date in needs since we dont have a creation date for connections right now) instead of the last event creation date per connection (corresponds modification date in needs)
=> Constant paging

webofneeds/won-bot/src/main/java/won/bot/framework/bot/base/FactoryBot.java
this is so that every class that extends from factorybot has all the outgoing messagebehaviour by default
=> adds messagebehaviour to every factorybot

webofneeds/won-core/src/main/java/won/protocol/rest/LinkedDataRestClient.java
Previously, the LDRC failed with an Exception on anything but a 2xx
response, breaking things like caching with the CachingLinkedDataSource
Fixes #1319
=> Cause LinkedDataRestClient to fail only on 4xx responses

webofneeds/conf/matcher-service/matcher-service.properties, webofneeds/won-matcher-service/src/main/java/won/matcher/service/common/event/NeedEvent.java, webofneeds/won-matcher-service/src/main/java/won/matcher/service/crawler/actor/MasterCrawlerActor.java, webofneeds/won-matcher-service/src/main/java/won/matcher/service/crawler/actor/WorkerCrawlerActor.java, webofneeds/won-matcher-service/src/main/java/won/matcher/service/crawler/service/CrawlSparqlService.java, webofneeds/won-matcher-service/src/main/java/won/matcher/service/nodemanager/actor/NeedConsumerProtocolActor.java, webofneeds/won-matcher-solr/src/main/java/won/matcher/solr/actor/SolrMatcherActor.java, webofneeds/won-matcher-solr/src/test/java/won/matcher/solr/SolrTest.java
closed needs should now (after crawling which takes place every 60 min) not be matched anymore.
you can test this the following way:
* create a need A with Account 1
* create another need B on Account 2 to see that the matching works
* close the need A 
* restart the matching service (to trigger the recrawling) => wait for ~ a minute so that all recrawling has happended
* create another need C on Account 2 which is not matched anymore with need A cause need A was closed 
The need state can also be checked in these servers:
matching service: http://satvm05.researchstudio.at:9999/bigdata
solr matcher: http://satvm05.researchstudio.at:8983/solr/won/browse?q=<needid>
=> Fix do not match closed needs

webofneeds/won-owner-webapp/src/main/webapp/app/piwik.js
It's wasteful to send a tracking request for each hint. We suppress that now, we may do something more complicated once we see that we really need it, like waiting for all hints and then sending one tracking request.
=> Suppress tracking request for each hint

.gitignore, webofneeds/pom.xml
Qpid version we depend upon is (temporarily?) not available.
Found out we actually don't need it.
=> Fix build problem with qpid

webofneeds/won-owner-webapp/src/main/webapp/app/actions/account-actions.js
In case of an 'anonymous' posting, a new account is created with a
made-up '@matchat.org' email address. The process of creating that
account is currently waited for using a timeout (see #1351). This commit
increases the timeout from 500ms to 3s, hoping to catch most of the
cases.
=> Increase message timeout

webofneeds/won-docker/image/nginx/nginx.conf
Prior to this commit, the node's robots.txt was written, not the owner's
=> Fix robots.txt for live

webofneeds/won-owner-webapp/src/main/webapp/app/actions/account-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/messaging-agent.js
In the open() handler of the websocket, after registering the redux
watches, the first enqueued message is sent, causing a chain reaction
that sends all enqueued messages.
All related timeouts are removed, making the app faster.
Fixes #1351
=> Fix the lost postings bug, without using timeouts

webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/needlifecycle/AbstractCreateNeedAction.java, webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/wonmessage/OpenConnectionAction.java, webofneeds/won-bot/src/main/java/won/bot/impl/DebugBot.java, webofneeds/won-core/src/main/java/won/protocol/util/linkeddata/WonLinkedDataUtils.java, webofneeds/won-node/src/main/java/won/node/camel/processor/fixed/OpenMessageFromNodeProcessor.java, webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/create-need-action.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/needs-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-map.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/location-picker.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/send-request.js, webofneeds/won-owner-webapp/src/main/webapp/app/configRedux.js, webofneeds/won-owner-webapp/src/main/webapp/app/configRouting.js, webofneeds/won-owner-webapp/src/main/webapp/app/messaging-agent.js, webofneeds/won-owner-webapp/src/main/webapp/app/piwik.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/message-reducers.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer.js, webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js, webofneeds/won-owner-webapp/src/main/webapp/app/service/message-builder.js, webofneeds/won-owner-webapp/src/main/webapp/app/service/need-builder.js, webofneeds/won-owner-webapp/src/main/webapp/app/service/won.js, webofneeds/won-owner-webapp/src/main/webapp/app/utils.js, webofneeds/won-owner-webapp/src/main/webapp/app/won-message-utils.js, webofneeds/won-owner-webapp/src/main/webapp/app/won-utils.js
* Optimistically add need immediately after posting
* New chaining mechanism for actions
Allows for executing actions when a success/failure response for
a given message is received
* Use chaining mechanism to wait for success of AdHoc need creation,
then send a connect message
* Refactored use of connect and open (connect requires no existing
connection
* What's around need creation now only deactivates all existing *active*
what's around needs, instead of all of them (which is wasteful)
* Removed some excessive log output (still more to be done there)
=> Refactor owner webapp

webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/create-need-action.js
fixes #1367 
problem was that there was a routechange when closing a need, and a route change when a need is created, however creating a whatsaround need closes all preexisting whatsaround needs and due to the asyncronous behaviour of routechanges there was an overlap in the transitions resulting in the described error.
Fix was: remove the routechange in the need close action, and make a routechange for createneed that always goes to the feed when a need is about to be created (thats currently our defaultRoute)
=> Fix route change blocked #1367

webofneeds/won-node-webapp/src/main/java/won/node/web/LinkedDataWebController.java, webofneeds/won-node-webapp/src/main/resources/spring/node-context.xml
Due to our "accept everything that doesnt match a certain pattern"-securityfilter we were able to access content that should have been restricted to users who had the correct webid.
now we only have a certain set of allowed urls that can be accessed and everything else willl be denied.
the ruleset is as follows:
WebID specific urls: (only accessible if the webid is present)
`/(resource|data|page)/((event/.+)|(need/[a-zA-Z0-9]+/((deep.*)|(events/.+)))|(connection/[a-zA-Z0-9]+/events.*deep=true.*))` -> access only if ROLE_WEBID
Registration Urls: (Client Certificate needed)
`/resource\?register=.+` -> access only if ROLE_CLIENT_CERTIFICATE_PRESENTED
Other Urls:
`/(resource|data|page)(/need)?(((\?.*)|/)?)` -> no restriction
`/(resource|data|page)/((need/[a-zA-Z0-9]+(/connections)?)|(connectio …
=> Fix securityflaw eventaccess

webofneeds/won-docker/deploy/live_satvm01/docker-compose.yml, webofneeds/won-docker/deploy/uki_satvm06/docker-compose.yml, webofneeds/won-docker/deploy_uki.sh, webofneeds/won-docker/image/gencert/openssl-uki.conf, webofneeds/won-docker/image/letsencrypt/Dockerfile, webofneeds/won-docker/image/letsencrypt/certificate-request-and-renew.sh, webofneeds/won-docker/image/nginx/nginx-uki-http.conf, webofneeds/won-docker/image/nginx/nginx.conf
change the uki deployment to use the domain "line.uki.or.at", continues or fixes #1355
=> Uki domain change to line.uki.or.at

webofneeds/won-matcher-service/src/main/java/won/matcher/service/crawler/actor/MasterCrawlerActor.java, webofneeds/won-matcher-service/src/main/java/won/matcher/service/crawler/service/CrawlSparqlService.java
* dont do the double crawling with and without trailing slashes, use only without trailing slashes => this should fix warnings described in fixes #1373 
* take the uris as the come from crawling but query them at extraction time with and without trailing slashes
=> Fix trainling slashes

webofneeds/won-matcher-solr/src/main/java/won/matcher/solr/hints/HintBuilder.java, webofneeds/won-matcher-solr/src/main/java/won/matcher/solr/query/DefaultMatcherQueryExecuter.java, webofneeds/won-matcher-solr/src/main/java/won/matcher/solr/query/factory/MatchingContextQueryFactory.java
this is a fix to the mataching context feature added in the matcher. 
in addition to querying the solr with matching context filter, we also need to filter out hints before sending them to both needs. only send hints to both needs if there matching contexts overlap (OR policy) and always send a hint to a need that has not specified a matching context. 
This can be tested by creating needs with different/overlapping/no matching contexts and check if the hints are send correctly to both needs
=> add hint filtering for context matching

webofneeds/conf/matcher-service/matcher-service.properties, webofneeds/won-matcher-service/src/main/java/won/matcher/service/nodemanager/actor/WonNodeControllerActor.java
improved crawler log output handling in the following situations:
* log failed connection attemps to won nodes as warning only if its the first attempt
* show start and end of crawling instead of every single message at info level
=> Fix failed wonnode reconnect

webofneeds/won-owner-webapp/pom.xml
Using 'mvn frontend:npm@watch', the watch task can be activated.
=> Enable npm watch via maven

webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-message.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js, webofneeds/won-owner-webapp/src/main/webapp/style/_connection-message.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_post-messages.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_won-config.scss, webofneeds/won-owner-webapp/src/main/webapp/style/won.scss
- adds "won-unread" class to messages that are "unread"
- adds default styling of a class .won-unread in won.scss (sets background color in this iteration, further styling possible)
- adds won-unread color -> currently set to the helpbox yellow
-altered padding/margin in connection-message and post-messages
=> - removes obsolete watch (moved to ng-class in post-messages.js)

webofneeds/won-owner-webapp/README.md, webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/feedback-grid.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/send-request.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer.js
This PR allows the user to rate a suggested connection within the chat Tab (after the suggested connection is selected), it also removes the ability to rate connections more than once by adding a isRated flag in the connection state -> after a suggested connection has been rated it is possible to close the connection after all or connect with it
=> Refac rateconnection

webofneeds/won-owner-webapp/README.md, webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-message.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-selection-item.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-selection.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-overview.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/feed-item.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/overview-title-bar.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/owner-title-bar.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-item-line.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer.js
Adds/Refactors "unread" flag for need/connection/message
- shows counters for unread connections/messages
- sorts connection list from newest to oldest update
- sorts needlist from newest to oldest update (in chat-overview)
-main-tab-bar shows unread connections number of all open needs next to chats tab
-post title bar shows unread connections number of specific need next to chats tab
-post element in connection-overview shows the same as the above
-connetion element in connection-selection-item shows the amount of unread msgs
the need and connections will be set to read if there are no unread subelements left (e.g a need is unread=false if there are no connections with unread=true within this need, and the same goes for connections and their respective messages... for connections that …
=> Feat connection sort and counters

webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-overview.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/overview-incoming-requests/overview-incoming-requests.html, webofneeds/won-owner-webapp/src/main/webapp/app/components/overview-incoming-requests/overview-incoming-requests.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-header.js
Verify that all needs (closed, open with and without connections) are shown in overview, that inactive needs are listed below active needs and that there are no additional/missing indicators, visible conversations, dropdown arrows, ...
=> Feat  show all needs in overview

webofneeds/won-owner-webapp/src/main/webapp/style/_connections-overview.scss
Move the show-connections caret in the chat view to the center of the line to make it more clickable, less visually distracting.
Also vertically centers the other elements in the need row removing some asymmetry of the indicators.
=> Fix  chat dropdown position

webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js, webofneeds/won-owner-webapp/src/main/webapp/style/_post-messages.scss
When the chat context menu was open it would push the title text to the side. Now it cleanly overlays.
Also the down-caret is now invisible instead of not-displayed so the layout of the title stays exactly the same whether the dropdown menu is opened or closed.
=> Fix  positioning of chat title when dropdown menu is open.

webofneeds/won-owner-webapp/src/main/webapp/style/_post-info.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_post-owner.scss
Now correctly removes padding and border on responsiveness breakpoint.
Previously style cascading would render the media query in `_post-owner.scss` ineffective.
=> Fix responsive mode styling in post-view.

webofneeds/won-owner-webapp/src/main/webapp/style/_connection-indicators.scss
Fixes #1550
Was caused by a seemingly stray selector.
Does not seem to have been important but should probably be checked.
=> Fixed indicator row size in responsive mode.

webofneeds/won-owner-webapp/src/main/webapp/style/_connection-selection-item-line.scss
Fixes #1553 
Probably caused by out-of-order rendering of the bubbles by angular.
=> Fix indicator bubbles being hidden behind connection icons.

webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-overview.js
The up-arrow in the connection overview is now not disabled when a related connection is opened.
Instead, clicking the arrow closes the connection and folds up the connection list.
Watching the state change is necessary to ensure correct behaviour when loading the page with a connectionUri set. Otherwise closing the connection with the "X" button would automatically collapse the list.
Fixes #1563
=> Closing connection on list fold-up

webofneeds/won-owner-webapp/README.md, webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer.js, webofneeds/won-owner-webapp/src/main/webapp/app/utils.js, webofneeds/won-owner-webapp/src/main/webapp/style/_connection-message.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_post-messages.scss
- Saves the read connection/message uris in the localstorage to remove the unread status of read messages when reloading the page or after a login (is not the implementation of #1457)  -> yet we should probably still use it in master/matchat for now as it is a way better user experience as the current one which marks everything as unread on login or reload
fixes #1584 
implements a new/working load Messages behaviour with spinner -> stores parameter "isLoading" in the state of the connection, so we know when a connection is currently Loading messages -> this parameter should also be used while loading/calculating agreement/proposals and should be used in favor of the "loading" in post-messsages.js,
=> Feat store read in localstorage

webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-message.js
Adapted the text of the no-text-message message -> fixes #1590 
if the message is not sufficient or explanatory enough to the reviewer, the reviewer should change the message accordingly and merge the pull afterwards
=> adapted no-textmessage message

webofneeds/won-owner-webapp/src/main/webapp/app/components/logged-in-menu.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/login-form.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-info.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/send-request.js, webofneeds/won-owner-webapp/src/main/webapp/style/_button.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_covering-dropdown.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_topnav.scss
This PR "fixes" some issues that we received from a user:
-The "Show RDF" buttons have been removed -> and a global "Under the hood"-Toggle is implemented which shows rdf-links as we had previously implemented and toggles the rdf mode in the chat
- puts a line between the sign out button and the otherbuttons in the user menu, to seperate these actions from each other better
-add a whitespace no break so that buttons don't turn into multiline buttons
=> Changes based on the Issues that occured in the video provided by david mann

webofneeds/won-owner-webapp/src/main/webapp/package.json
`redux-ui-router` depends on the new `@uirouter/angularjs` (formerly `angular-ui-router`)
=> Added missing peer dependency for webpack build.

webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-state.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/connections/connections.html, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-info.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-share-link.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post/post.html, webofneeds/won-owner-webapp/src/main/webapp/app/components/send-request.js, webofneeds/won-owner-webapp/src/main/webapp/style/_post-info.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_post-share-link.scss, webofneeds/won-owner-webapp/src/main/webapp/style/won.scss
fixes #1560 autoselect link and copy it to clipboard
fixes #1591 cant select visitor link in firefox
implements a different styling for the visitor link (border of post-info is removed when inlcudeheader is set to false)
=> Feat sharelink component

webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/wonmessage/execCommand/ExecuteDeactivateNeedCommandAction.java, webofneeds/won-core/src/main/java/won/protocol/util/WonRdfUtils.java
Implementation had been an incomplete copy/paste production from the create command.
To check:
1. create need in debug mode
2. wait for connect
3. navigate to the conversation
4. enable RDF mode 
5. open the need resource URI in another browser window
6. in the conversation, type 'deactivate'
7.  observe that the connection is removed from your view.
8. reload the other browser window and check that the need's state has changed to `won:Inactive`
Fixes #725
=> Fix deactivate command execution

webofneeds/won-utils/won-utils-conversation/src/main/java/won/protocol/agreement/AgreementProtocolState.java, webofneeds/won-utils/won-utils-conversation/src/main/java/won/protocol/agreement/ConversationMessage.java, webofneeds/won-utils/won-utils-conversation/src/test/java/won/protocol/highlevel/GetAgreementsTests.java, webofneeds/won-utils/won-utils-conversation/src/test/java/won/protocol/highlevel/GetProposalsTests.java, webofneeds/won-utils/won-utils-conversation/src/test/resources/won/protocol/highlevel/proposals/expected/one-agreement-proposaltocancel-rejected-b4-accept.trig, webofneeds/won-utils/won-utils-conversation/src/test/resources/won/protocol/highlevel/proposals/expected/one-agreement-proposaltocancel-retracted-b4-accept.trig, webofneeds/won-utils/won-utils-conversation/src/test/resources/won/protocol/highlevel/proposals/input/one-agreement-proposaltocancel-rejected-b4-accept.trig, webofneeds/won-utils/won-utils-conversation/src/test/resources/won/protocol/highlevel/proposals/input/one-agreement-proposaltocancel-retracted-b4-accept.trig, webofneeds/won-utils/won-utils-conversation/src/test/resources/won/protocol/highlevel/proposals/input/one-agreement-proposaltocancel-retracted.trig
Steps to verify:
`won.protocol.highlevel.GetProposalsTest.oneAgreementProposalToCancelRetractedBeforeAcceptTest() ` uses a conversation with a retract of a proposeToCancel. The expected output therefore is the previously made agreement.
you can edit the input file of that test and remove the retract statement, then the test should fail.
Do the same with the similarly named test for `reject`.
Fixes #1682
=> Fix #1682 - retract/reject fails for proposeToCancel

webofneeds/won-owner-webapp/src/main/webapp/app/actions/account-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/load-action.js, webofneeds/won-owner-webapp/src/main/webapp/app/configRouting.js
Fixes #1692 
Right now navigating to a uri without a privateId doesn't add it back, because the routing doesn't trigger.
=> Storing privateId in localStorage and writing it into the uri on connection

webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-info.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/send-request.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/topnav.js, webofneeds/won-owner-webapp/src/main/webapp/style/_connections.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_create-post.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_post-info.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_post-messages.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_responsiveness-utils.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_topnav.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_won-config.scss
There have been some changes to remove some of the fixed elements in the mobile view to ensure having more space for the "important" parts.
-change close icon of the create-post, post-messages, post-info, and send-request to a smaller back arrow, and only show it within mobile view
-hide the topnav-header if a post or a conneciton is open (but do not hide the slide-in connection loss info, or toasts)
fixes #1671 
ps: responsiveness-utils.js is using !important now for the display attribute, usually i stay away from ever using it, but in this case it isn't as wrong since hide-in-responsive and show-in-responsive are utility classes that should overrule everything else even if the selector priority of a different display attribute would be higher
=> Feat update mobile layout #1671

webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-overview.js, webofneeds/won-owner-webapp/src/main/webapp/style/_connection-header.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_connections-overview.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_create-post.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_post-header.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_post-info.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_post-messages.scss
show a "hide details button"
break word in post-info (necessary to break long one word titles -> even though it is probably unreasonable to have words that exceed the limit.... just to be safe)
includes #1710 (
i changed the display property from flex to grid to ensure that the child elements use the whole available space, because, min-width: 0 is necessary so firefox collapses grid (or even flex) and not display the whole child element -> this is rather unituitive but well explained in this link https://bugzilla.mozilla.org/show_bug.cgi?id=1108514)
fixes #1712 
fixes #1704
=> Feat hide details button

.gitignore, documentation/build-with-eclipse.md, documentation/installation-setting-up-frontend-development-environment.md, webofneeds/won-owner-webapp/pom.xml, webofneeds/won-owner-webapp/src/main/webapp/package-lock.json, webofneeds/won-owner-webapp/src/main/webapp/package.json
npm is now version `next` because `latest` seems to be in a broken state right now: https://github.com/npm/npm/issues/19989
also bumped `node-sass` version because the old version did not have binaries for the new node version: https://github.com/sass/node-sass/issues/2360
This will need a `mvn install` to correctly update the node version.
Also, this might surface a problem with `windows-build-tools` not being installed on developer machines (namely, Python).
Documentation on how to solve this can be found [here](https://github.com/researchstudio-sat/webofneeds/blob/8ba0270affcd265db028bd639db875c3bca08489/documentation/installation-setting-up-frontend-development-environment.md#installing-windows-build-tools-on-windows)
=> Bump npm version

webofneeds/won-owner-webapp/src/main/webapp/package.json, webofneeds/won-owner-webapp/src/main/webapp/webpack.config.ts
Contains fixes for https://github.com/rdfjs/N3.js/issues/135 and https://github.com/rdfjs/N3.js/issues/136
This allows us to minify function names again, and makes it possible to use synchronous parsers in the future.
=> Bumped n3 version to 1.0.0-beta.1

webofneeds/won-owner-webapp/src/main/webapp/app/components/create-isseeks.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-is-info.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-seeks-info.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/tags-picker.js, webofneeds/won-owner-webapp/src/main/webapp/index.html, webofneeds/won-owner-webapp/src/main/webapp/style/_create-isseeks.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_locationpicker.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_post-info.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_tagspicker.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_won-config.scss
Moved tags picker to own component. Tags can now only be set via the tag picker and should not disappear while editing other details. 
Closes #1580, closes #1745 by restricting tag addition/deletion to only one textfield.
=> Refac  add tags picker component

webofneeds/won-owner-webapp/src/main/webapp/.babelrc, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js, webofneeds/won-owner-webapp/src/main/webapp/package-lock.json, webofneeds/won-owner-webapp/src/main/webapp/package.json
Fixes #1777
This also allowes us to stop removing strict mode from our es6 modules.
To properly test, first run `npm i && npm prune` to assure the removed packages are actually removed.
Also restart your watch task if it is running, as the babel configuration has changed.
=> Linted post-messages.js

webofneeds/won-owner-webapp/src/main/webapp/style/_create-isseeks.scss
due to reasons unknown to me the scss to css compilation does not replace the $won-primary-color placeholder if it is assigned to a css variable: therefore we need to reference it with the "real" css var value instead of using the syntactic sugar of scss....
fixes #1791
=> fixes the disappearing icon when selected (detail picker) #1791

webofneeds/won-owner-webapp/src/main/webapp/app/components/post-header.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/visitor-title-bar.js
The matching context is currently not used.
Resolves #1668
=> Remove "no machting context..."

webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js
adding log to (almost) every method of linkeddata-service-won.js to ensure we all see how many times and when methods are called
making a first performance update -> remove the unnecessary ensureRdfsMemberArrays from the code base, it was never creating a different object and the recursion went to deep to begin with (the recursion was called for each individual character of a string too -> and thus creating many many unused method recursions )
=> Feat remove perfomance hogging method

webofneeds/won-owner-webapp/src/main/webapp/app/actions/create-need-action.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js, webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js
If a whatsaround or whatsnew already exists, the login process and duration is very fidgety -> the old whatsX is loaded and visible in the ui and then suddenly disappears (due to the fact that we create a new one each time we login and close the old ones), therefore we load alot of connections and needs unnecessarily
This PR is a fast fix for this problem -> the whatsnew is not automatically created if there is already an open whatsnew or whatsaround for this user, and the whats around need will not be created if there is already an open whatsaround need for this user.
=> Fix autocreate whatsx

webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer.js, webofneeds/won-owner-webapp/src/main/webapp/app/service/need-builder.js
There were some issues within the routepicker rdf creation see need-builder.js changes
also somehow we got the prefixed attributes in the need-reducer again and therefore couldnt parse the creationDate and the location as they assumed a fully qualified name, since i didnt want to go on a fact finding mission to find out why this is different again i added resilience to our need-reducer parsing -> now it will work with either of the two options (prefixed and fully qualified name)
=> Fix need parsing and route rdf

webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer.js, webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js, webofneeds/won-owner-webapp/src/main/webapp/app/service/won.js, webofneeds/won-owner-webapp/src/main/webapp/app/utils.js, webofneeds/won-owner-webapp/src/main/webapp/app/won-localstorage.js, webofneeds/won-owner-webapp/src/main/webapp/app/won-message-utils.js
instead of crawling all the connection uris directly and only returning the ones we actually want we just get all the connectionUris from a need, and then storing the closed ones similar to the process we will implement for deactivated needs (in the local storage) so we do not ever crawl a closed connection again on reload/login etc... the connection is marked as closed if the connection is added to the redux state and has a state of WON.Closed, or when the connectionState itself changes
Fixes in this branch:
-removed an unused method
-called the executeCrawlableQuery with the right set of parameters (3 instead of 2)
-omit further crawling for a connUri that has already been deemed as closed (from the localStorage)
This should enhance the login speed for users with alot of needs and …
=> Feat enhance connuri crawling

webofneeds/won-docker/deploy/live_satvm01/docker-compose.yml, webofneeds/won-docker/deploy/uki_satvm06/docker-compose.yml, webofneeds/won-docker/deploy_uki.sh, webofneeds/won-docker/image/gencert/openssl-uki.conf, webofneeds/won-docker/image/nginx/nginx-uki-http.conf, webofneeds/won-docker/image/nginx/nginx.conf
Needs to be deployed:
on master (just cuz)
on live (for our nginx load balancer)
on uki (to deploy the actual instance in the correct place)
we currently do not have the dns entry for meicogsci.matchat.org and thats why we can't re-generate the letsencrypt certificate yet, but once this has happened someone will update it and then we should be able to use the instance from meicogsci.matchat.org
Child of #1866
=> replace all occurences of line.uki.or.at with meicogsci.matchat.org

webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/needs-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-overview.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer.js, webofneeds/won-owner-webapp/src/main/webapp/app/won-localstorage.js, webofneeds/won-owner-webapp/src/main/webapp/app/won-message-utils.js
Fixes #1869
Things to look out for:
* Are `inactiveNeeds` (localstorage) accidentally pruned too much?
* Because of #1891 testing this PR can become weird. Please disable the cache in the browser devtools while testing.
Todo:
=> Don't fetch archived needs on page load

webofneeds/won-owner-webapp/README.md, webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-overview.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-header.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer.js
Shows a placeholder for needs that are already in the state, but not registered on the server yet. If the create fails and the need is removed from the state, the placeholder disappears, too. The placeholder only exists client-side and does not reflect server status. 
#1868 is not closed by this, as there is no toast displayed when creating the need fails.
=> Feat  add new need immediately #1868

webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-context-dropdown.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js, webofneeds/won-owner-webapp/src/main/webapp/style/_post-messages.scss
fixes #1905 
moves the show agreement data button from the footer to the connection-context-dropdown (for connections in state connected) in order to use less precious space in the footer
=> move show agreement data button to connection-context.dropdown

webofneeds/won-owner-webapp/src/main/webapp/app/directives/textarea-autogrow.js
Fixes #1908
This is mainly a symptomatic fix, we will eventually need to change the way we layout the page.
Create a few needs with many connections in Firefox and start typing in the chat field of one connection.
Before it was painfully slow with 70-100ms frame timings, now it should be fast with the exception of completely deleting the text and adding a new line.
This change has the side effect that the autogrowing textarea does not shrink anymore except when cleared completely. Shrinking the text area would necessitate setting the input height to `0` which would cause a long layout cycle on each key press
=> Fix slow text input (specifically in Firefox)

webofneeds/won-owner-webapp/README.md, webofneeds/won-owner-webapp/src/main/webapp/app/actions/account-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/about/about.html, webofneeds/won-owner-webapp/src/main/webapp/app/components/about/about.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/topnav.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/user-reducer.js, webofneeds/won-owner-webapp/src/main/webapp/app/service/won.js, webofneeds/won-owner-webapp/src/main/webapp/app/won-localstorage.js, webofneeds/won-owner-webapp/src/main/webapp/skin/blue/config.json, webofneeds/won-owner-webapp/src/main/webapp/skin/blue/privacyPolicy.html, webofneeds/won-owner-webapp/src/main/webapp/skin/current/config.json, webofneeds/won-owner-webapp/src/main/webapp/skin/current/privacyPolicy.html, webofneeds/won-owner-webapp/src/main/webapp/skin/green/config.json, webofneeds/won-owner-webapp/src/main/webapp/skin/green/privacyPolicy.html, webofneeds/won-owner-webapp/src/main/webapp/skin/matchat/config.json, webofneeds/won-owner-webapp/src/main/webapp/skin/matchat/privacyPolicy.html, webofneeds/won-owner-webapp/src/main/webapp/skin/uki/config.json, webofneeds/won-owner-webapp/src/main/webapp/skin/uki/privacyPolicy.html, webofneeds/won-owner-webapp/src/main/webapp/style/_about.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_slidein.scss
- Adds a slide-in if a webapp visitor/user has not accepted the disclaimer yet.
- It shows a message with a link within the text (links to the about page) and a button to accept the disclaimer.
-The Status is currently saved into the localStorage and is retrieved on page load and saved in the redux state (subelement of user), accepting also saves the status to the localstorage and the state.
There are 3 new debug methods to be used for testing (these only change the localstorage state and not the redux state!):
```
won.isDisclaimerAccepted() //to see if the disclaimer has already been accepted
won.clearDisclaimerAccepted() //to clear the disclaimer acceptance within the localstorage (refresh should show the disclaimer again)
won.setDisclaimerAccepted() //to programmatically set the …
```
=> Feat disclaimer slidein #1888

webofneeds/won-owner-webapp/README.md, webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-message.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer.js, webofneeds/won-owner-webapp/src/main/webapp/style/_connection-message.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_connection-selection-item-line.scss
this PR fixes #1913 
however this PR does not handle the complete failure of the server (since the messaging-agent will not push any actions into the state)
also this pr does not allow resending of the messages yet, since we do not have the original message in the redux store (afaik)
BUT:
it is now visible if the message is already successfully pushed to the own server and to the remote server, and will show if the message sending failed (only handle FailureResponse from server though, so it might mean that we only mark messages that are not valid)
This means the PR fixes the first part of the issue, please check this and alter the issue or create a new one for the missing parts
=> Feat message status #1913

webofneeds/won-owner-webapp/src/main/webapp/webpack.config.ts
Fixes #1533
The error was that `jsonld` lists its uncompiled source (containing spread operators) as main entrypoint, and we don't transform our dependencies.
We solve this by instead redirecting every require of `jsonld` to its compiled output at `jsonld/dist/jsonld.js`
Related: https://github.com/digitalbazaar/jsonld.js/issues/251
=> Made app work on Edge and Safari Mobile < 11 again

webofneeds/won-owner-webapp/src/main/webapp/app/components/chat-textfield-simple.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/message-reducers.js
fixes #1926 
this also removes the "race condition" that we have had on a reload of the page -> somehow messages.reconnecting within the state is set to true after a reload, however that was never set back to false, now we set both connLost indicator flags to false after the initialLoad has been finished
=> Fix disable publish #1926

webofneeds/won-owner-webapp/src/main/webapp/.eslintrc.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/need-reducer-main.js, webofneeds/won-owner-webapp/src/main/webapp/app/service/need-builder.js, webofneeds/won-owner-webapp/src/main/webapp/app/service/won.js, webofneeds/won-owner-webapp/src/main/webapp/app/utils.js, webofneeds/won-owner-webapp/src/main/webapp/app/won-message-utils.js, webofneeds/won-owner-webapp/src/main/webapp/app/won-utils.js
`Exception` is a custom class defined by the rdfstore, whereas `Error` is the standard class used by the rest of the javascript world. This PR changes all occurrences of the former outside of the store for the latter, which gives us much better support in devtools (e.g. working error messages and stack traces for one)
Resolves #1983
=> Using standard javascript errors.

webofneeds/won-owner-webapp/src/main/webapp/app/components/send-request.js
fixes #1949 
adds the type to the post-info for hints (because the header is only showing the connection status, whereas the post-header of a normal post-info shows the type as well)
=> show need type for hints within the "post-info"

webofneeds/won-owner-webapp/README.md, webofneeds/won-owner-webapp/src/main/java/won/owner/web/rest/RestNeedController.java, webofneeds/won-owner-webapp/src/main/java/won/owner/web/websocket/WonWebSocketHandler.java, webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-overview.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-header.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/need-reducer-main.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/reduce-needs.js, webofneeds/won-owner-webapp/src/main/webapp/app/won-localstorage.js, webofneeds/won-owner-webapp/src/main/webapp/app/won-message-utils.js, webofneeds/won-owner/src/main/java/won/owner/model/UserNeed.java, webofneeds/won-owner/src/main/java/won/owner/repository/UserNeedRepository.java, webofneeds/won-owner/src/main/resources/db/migration/V5_0__add_userneed_state.sql
fixes #1909:
is fixed by removing the handling from the localStorage, and adding the state of a need to the userneeds, the state changes due to websocket message "sniffing", a login should retrieve two sets of lists -> a activeUri list and a inactiveUri list, theses needuris are saved in the state as isLoading or toLoad, and therefore are subject to update, and the preliminary work for skeletonScreens is done for the needs
=> Fix clear unloaded needs #1909

webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js
another workaround for a n3.js parsing issue, this time it replaces doublequotes
fixes #1860 
should also subsequently fix #1861
=> replace doublequotes with replacement string

webofneeds/won-owner-webapp/src/main/webapp/app/components/create-isseeks.js
fixes #1950 
adds trim to the updateTitle methods titleString to remove the ability to create needs with a sort-of blank title
=> fixes #1950

webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-overview.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js, webofneeds/won-owner-webapp/src/main/webapp/app/selectors.js
fix #1790 -> to remove the "silent conversations"-issue we have after a reload the connections-overview will start crawling messages already even before clicking the connection to see the chat-view:
this was implemented as follows, a crawlableConnection is every connection in the state "Connected" which either has no messages stored at all so far, or has all messages loaded already (connectMessage is present)
each of these connections will dispatch either a showLatestMessages or a showMoreMessages action:
showLatestMessages will be called if there are no messages present so far
showMoreMessages will be called if there are already messages present and at none of the present received messages is unread
fix #2002 -> unread messages should be visible in the chat again
=> Feat silent conversations #1790 fix #2002

webofneeds/won-owner-webapp/src/main/webapp/app/reducers/message-reducers.js
This should have been part of #2029. `connections__close(...)` only dispatches one actions due to that pull-request. The message reducer now needs to react to this action!
```
connections-actions.js:247   export function connectionsClose(connectionUri) {
...
connections-actions.js:275      dispatch({
connections-actions.js:276        type: actionTypes.connections.close,
connections-actions.js:277        payload: {
connections-actions.js:278          connectionUri,
connections-actions.js:279          eventUri,
connections-actions.js:280          message,
connections-actions.js:281        },
connections-actions.js:282      });
```
```
message-reducer.js:50     case actionTypes.connections.close:
```
=> Added missing reducer case statement so removing match works.

webofneeds/won-owner-webapp/src/main/webapp/app/won-label-utils.js
=> Removed "approximately" from timestamp-label. It's too long on mobile.

webofneeds/won-core/src/main/java/won/protocol/rest/RdfDatasetConverter.java, webofneeds/won-core/src/main/java/won/protocol/rest/RdfModelConverter.java, webofneeds/won-node-webapp/src/main/java/won/node/web/LinkedDataWebController.java, webofneeds/won-owner-webapp/src/main/java/won/owner/web/rest/BridgeForLinkedDataController.java
* Reduces caching, increased ETAG validation
* No more duplicate headers in linked data bridge responses
* Adds a content-length header to RDF responses
Fixes #1891 
Fixes #1996
=> Fix http headers

webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/connections/connections.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/reducers.js, webofneeds/won-owner-webapp/src/main/webapp/app/utils.js
This is a hacky workaround that remembers the scroll position of the main view and resets it when the state changes.
=> Fixed #1911

webofneeds/won-owner-webapp/src/main/webapp/app/actions/account-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/load-action.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-overview.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/topnav.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/message-reducers.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/need-reducer-main.js, webofneeds/won-owner-webapp/src/main/webapp/app/selectors.js
test: 
1. create need
2. copy share link and connect from a different browser-session (accept with the original need)
3. go to the network tab and disable the network connection. then run `ws4dbg.close()` in your terminal (note: you might need to reload before doing that as the dev-tools disconnect doesn't usually apply to web-sockets and `ws.close()` is a bit wonky)
4. write some messages from the other need
5. make another connection request from another browser session
6. set your network to "online" again
7. press "reconnect"
8. the new messages and the incoming request should show up
open issue: the new connection isn't found
Resolves #2019
=> Fix  refresh cncts after reconnect  #2019

webofneeds/won-owner-webapp/src/main/webapp/app/components/usecase-picker-content.js
there was a mistake in the template of the usecase-picker-content that made the intended styling not apply to the whatsX buttons -> once you clicked either one of the buttons the view should only display one button (to show that the creation is pending) and this button should span over the whole width of the component, instead of just on the left half
=> Fix CSS-Class mismatch

webofneeds/won-owner-webapp/src/main/webapp/app/components/topnav.js
Some browsers (firefox/Android) do not allow scrolling in the slidein.
With a small screen, it's not possible to click the ok button,
effectively making the app unusable. This is an attempt to fix this for
most devices by shortening the message.
=> Shorten message on slidein

webofneeds/won-owner-webapp/src/main/webapp/app/utils.js
Tags can be separated by either "," or whitespace now. Only affects the tags-detail-picker.
=> Update tag extraction in utils.js

webofneeds/won-owner-webapp/README.md, webofneeds/won-owner-webapp/src/main/webapp/app/components/connections/connections.html, webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/connection-message.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/post-content-message.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content-general.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-info.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post/post.html, webofneeds/won-owner-webapp/src/main/webapp/app/components/send-request.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/parse-message.js, webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js, webofneeds/won-owner-webapp/src/main/webapp/config/detail-definitions.js, webofneeds/won-owner-webapp/src/main/webapp/style/_connection-message.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_post-content.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_post-info.scss
- Refactors the Hint/Suggested Connection view to just use the conversation component we use for all the other connection states
- Implemented a Special Message that represents the post-content of the counterpart post within every conversation as the first message
fixes #2137 (unread messages that never clear)
fixes #2001 (unread counters show incorrect values)
fixes #803 (show human-friendly matcher name -> we use the matcher url to generate a identicon so we kinda see the matcher that produced the hint or distinguish between matchers)
ps: this pull also implements the following:
depending on the presence of a NoHintForCounterPart flag, we prevent the ability to share this post by not rendering the share-component
=> Feat systemmessages

webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post-item.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/usecase-picker.js
fixes #2156 
- changes the label to "Add"
- uses the ico36_close instead of the backarrow (for the usecase-picker)-> so that we avoid > < in the mobile view
=> fixes #2156

webofneeds/won-owner-webapp/src/main/webapp/app/won-localstorage.js
fixes #2129 (by implementing a lazy init cache-object)
how to test:
1) open the won-localstorage.js file in the debugger
2) set a breakpoint within the first if clause of the getReadUris() getClosedConnUris() and isDisclaimerAccepted() functions
3) just create connections close them reload, chat etc....
You should see that the breakpoint will only be stopped on once after each page reload
=> Feat localstoragecache #2129

webofneeds/won-owner-webapp/src/main/webapp/index.html
svg-loading should look like this, and the 404'ing request should be gone (and there shouldn't be any related errors in the console):
=> Fixed url in img-tag used to speed up svg-loading.

webofneeds/won-owner-webapp/README.md, webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-header.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/connection-message.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/post-content-message.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-header.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/visitor-title-bar.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/parse-message.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/parse-need.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/reduce-needs.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/toast-reducer.js, webofneeds/won-owner-webapp/src/main/webapp/style/_connection-header.scss
Because we changed the Post Structure in a way that does not expect a title for a post, i changed the title in the state to humanReadable, and there is a funciton that determines the humanReadable String now, which is called upon need parsing
The current logic is as follows:
- if there is a title in seeks and in the is we use "isTitle - seeksTitle" as the humanReadable
- if there is a title in is or seeks alone we use that title
- if there is no title in is or seeks but a searchString we use "Search: searchString" as the humanReadable
- if none of the above clauses are met we set it to undefined
the method is called "getHumanReadableStringFromNeed(need)" and is located in the parse-need.js, if we want to display additional information in the humanReadable we should implement it here.
A …
=> Feat posttitle latestmessage handling #2037 #1719

webofneeds/won-owner-webapp/src/main/webapp/config/usecase-definitions.js
Adds rough transport offer and demand use cases. 
Both matching and RDF structure could be improved, but require future work on other parts of the application. 
To test: create transport and other use cases. Verify that all details are correctly parsed from/to RDF.
Fixes #2168
=> Transport use case #2168

webofneeds/won-owner-webapp/src/main/webapp/config/usecase-definitions.js
Fixes #2194 
Units are currently hard coded. Once we get to a point where we can combine details, we should probably set the unit via a dropdown picker and remove it from the label.
=> Added unit codes to transport usecase

webofneeds/won-owner-webapp/src/main/webapp/app/components/create-isseeks.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js
Fixes #2195 
This is a bit clunky on iOS since Safari does not implement the new `scrollIntoView` options yet.
=> Scrolling detail picker smoothly into view instead of always scrolling to bottom

webofneeds/won-owner-webapp/src/main/webapp/app/components/create-isseeks.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js, webofneeds/won-owner-webapp/src/main/webapp/config/usecase-definitions.js, webofneeds/won-owner-webapp/src/main/webapp/style/_create-isseeks.scss
Created the possibility to set a detail to be mandatory (just set the mandatory parameter to true)
What has been done:
- styled the mandatory details in the create-isseeks view
- added the check for mandatory details in create-post
- altered the existing isValid method by adding the check for mandatoryDetails
- refactored the ols isOrSeeksPresent to isBranchContentPresent, and removed the "fixed" title check, since this is not needed anymore
So to recap: 
The Post is valid if ->
- all the mandatoryDetails of both is and seeks are set
- at least one Detail is set within is or seeks (this could also be the case if there are default values set within the useCase itself) e.g. a usecase with fixed/non-editable tags in is or seeks would be valid even if all the visible detailpickers are empty …
=> Feat mandatory details

webofneeds/won-owner-webapp/src/main/webapp/app/service/need-builder.js, webofneeds/won-owner-webapp/src/main/webapp/config/usecase-definitions.js
The constraint is not honored anywhere and is not entirely correctly embedded in the rdf (it should be referenced by a `sh:NodeShape`, but it is a valid way to display a range of values for a field that does not have a range as part of its ontology.
As a side effect of `sh:property` possibly appearing multiple times in a need, the need-builder has been updated to merge jsonld branches instead of discarding one of them.
Using jsonld as a working dataset doesn't seem ideal though. Selections on the structure need to be made manually on Immutable.js structures, and prefixed IRIs are not isomorphic to their unprefixed versions.
=> Added shacl-constraint to range slider for number of rooms

webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/date-picker.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/datetime-picker.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/month-picker.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/time-picker.js, webofneeds/won-owner-webapp/src/main/webapp/app/service/need-builder.js, webofneeds/won-owner-webapp/src/main/webapp/config/usecase-definitions.js, webofneeds/won-owner-webapp/src/main/webapp/style/_datepicker.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_datetimepicker.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_monthpicker.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_timepicker.scss
created another rangepicker, and fixed the inclusion of the rangepicker for the number Of Rooms within the real estate offer
however the additon of another picker that produces shackle rdf data seems to fail when there is already one present, e.g one could only add either the number of rooms range or the size range... @peacememories maybe you can see where i am making the mistake
fixes #2233 
fixes #2235 parseToRdf does not use more than one range if defined within a shaclprop... -> see commit 7b191b3 for the solution, the problem was that the array was concatinated but not saved within the original array
fixes #2182 -> the generated sparql query inlcudes the min/max numberOfRooms, min/max Price, min/max floorSize within its filters of a real estate seeks,  it does not include the …
=> Feat morerangepickers

webofneeds/won-owner-webapp/src/main/webapp/package-lock.json, webofneeds/won-owner-webapp/src/main/webapp/package.json, webofneeds/won-owner-webapp/src/main/webapp/webpack.config.ts
The timer showing when the watch task triggers a rebuild can now detect wether there were actually any changes.
There seems to be a problem with our scss loader causing sources to become unavailable to the plugin (see https://github.com/sca-/webpack-watch-time-plugin/issues/5 ) but that does not seem to interfere with the functionality, just print a bunch of warnings when first starting the watch task.
The livereload plugin was removed because no one seems to have been using it and it might be the culprit behind out-of-memory issues.
=> Switched back to stock update-timer and also removed livereload plugin

webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/create-need-action.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/usecase-picker-content.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/reducers.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/toast-reducer.js
Fixes #2202 
Also fixed bug(?) where old WhatsAround needs would not be closed when a new one was created.
Still missing: Disabling the "What's in your Area?" button if location access is already denied. Checking this repeatedly would be costly, and keeping it disabled even if the user reenables the permission might lead to bad UX.
=> Added proper feedback if location access is not given

webofneeds/won-owner-webapp/src/main/webapp/config/usecase-definitions.js
Before you'd get e.g. "1 - undefined Rooms" if e.g. the maximum wasn't defined.
=> Ranges for nr of rooms and m² now have more resilient human-readable.

.gitignore, webofneeds/conf/matcher-solr/matcher-solr.properties, webofneeds/won-matcher-solr/src/main/java/won/matcher/solr/actor/MatcherPubSubActor.java, webofneeds/won-matcher-solr/src/main/java/won/matcher/solr/index/NeedIndexer.java, webofneeds/won-matcher-solr/src/main/java/won/matcher/solr/query/DefaultMatcherQueryExecuter.java, webofneeds/won-matcher-sparql/src/main/java/won/matcher/sparql/actor/MatcherPubSubActor.java, webofneeds/won-node/src/main/java/won/node/camel/route/fixed/WonMessageRoutes.java, webofneeds/won-owner-webapp/src/main/webapp/config/usecase-definitions.js
Fixes a number of problems revealed when testing with a larger number of needs generated by the RealEstateNeedGenerator
* scheduling of too many triggers in matcher
* failures when trying to send FailResponses
* enforces match count restriction
=> Fix higher load behaviour

webofneeds/won-owner-webapp/src/main/webapp/app/components/usecase-picker.js, webofneeds/won-owner-webapp/src/main/webapp/config/usecase-definitions.js, webofneeds/won-owner-webapp/src/main/webapp/style/_usecase-picker.scss
Adds a search function for use cases and changed view behaviour to directly show use cases from groups with only one use case.
Words separated by spaces are treated as separate search requests, i.e. searching for "taxi" and "rent" should show all use cases that match for either "taxi" or "rent". Fixes #2315
=> Usecase search #2315

webofneeds/won-docker/deploy/int_satvm05/docker-compose.yml, webofneeds/won-docker/deploy/live_satvm01/docker-compose.yml, webofneeds/won-docker/image/nginx/nginx-int.conf, webofneeds/won-docker/image/nginx/nginx.conf, webofneeds/won-owner-webapp/src/main/webapp/app/won-utils.js
Fixes #2331 
Uses matchat.org/tile/ for caching -> new nginx.conf needs to be deployed to live to be tested. 
Tiles should then be available from URIs like https://www.matchat.org/tile/5/7/7.png - this can also be tested via the location picker, which should still work.
=> OSM tile caching

webofneeds/won-owner-webapp/src/main/webapp/app/components/chat-textfield-simple.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/file-dropzone.js
implements #2139 (markdown viewer/picker)
How To Test:
1) DescriptionPicker and chat-message are now capable of submitting/creating markdown content
see [cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)
also fixes: #1786 and #1845 by removing the ng-bind-html completely and replacing it with the new marked directive (from angular-marked)
=> remove angular-sanitize

webofneeds/won-owner-webapp/src/main/webapp/app/app_jspm.js
implements the generated markdown links as "open in new tab" again (target _blank) but also add the already exisiting hrefSanitizationWhiteListRegex to remove the ability to include any xss javascript within the href
How To Test:
Using the https://ponyfoo.com/articles/fixing-xss-vulnerability-marked as an example, try adding following links to a description of a costum post:
1. `[Gotcha](javascript:alert(1))` - should not create a link in the preview
2. `[Gotcha](javascript&#58;alert(1&#41;)` - should not create a link in the preview
3. `[Gotcha](javascript&#58this;alert(1&#41;)` - should not create a link in the preview
4. `www.orf.at` - should create a link with the title orf.at in the preview
5. `[matchat](matchat.org)` - should not create a link in the preview as the href is not a …
=> Fix xss linkinnewtab

webofneeds/won-owner-webapp/src/main/webapp/app/app_jspm.js
remove the possibility to generate markdown links with a link text that is different from the href itself
this "prevents" "phishing"....
How To Test:
1.) `[test](https://www.example.com)` -> should result in a preview of `[test](https://www.example.com)` -> where example.com is marked as a link
=> "phishing" "prevention"

webofneeds/conf/node.properties
this change disables the automatic need deactivation check on the node, so we do not close needs after a certain timespan
=> disable automatic need deactivation check on node

webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/person-picker.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/tags-picker.js, webofneeds/won-owner-webapp/src/main/webapp/app/utils.js, webofneeds/won-owner-webapp/src/main/webapp/config/detail-definitions.js, webofneeds/won-owner-webapp/src/main/webapp/config/details/basic.js, webofneeds/won-owner-webapp/src/main/webapp/config/details/jobs.js, webofneeds/won-owner-webapp/src/main/webapp/config/details/location.js, webofneeds/won-owner-webapp/src/main/webapp/config/usecases/professional.js, webofneeds/won-owner-webapp/src/main/webapp/icons-demo.html, webofneeds/won-owner-webapp/src/main/webapp/package-lock.json
You can now enter data in "professional » search job", that's tailored to be matched with the hokify job-offers.
Doesn't include yet:
* icons
* sparql-queries
* manually entered job-offers
test:
1. post job search with all details
2. compare the generated RDF against the following json-ld pseudo-code (taken from our modelling document):
```
```json
{
"won:is" : {
"@type": "s:Person",
}
"won:seeks": {
"@type": "s:JobPosting",
"s:employmentType": "Full-time", // full-time/vollzeit, part-time,... - use a dropdown
"s:industry": ["Computer Software", "Design"], // match by checking for intersection + text-similarity and translations
//"s:baseSalary": {...}, // free-form-text in hokify json; can't match :|
"s:hiringOrganization": { // for ppl who only want offers from a specific organization …
=> Jobsearch Use-Case

webofneeds/won-owner-webapp/src/main/webapp/app/components/post-share-link.js
Fixes #2388 
Fixes #2427 (duplicate of #2388)
Tested on Chrome and Edge, maybe also test on Firefox and other browsers. 
Issues fixed:
* wrong URI generated for svg image
* fixed exception thrown when trying to use the Copy Link button
=> Fixed share link exceptions

webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/needs-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/chat-textfield-simple.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/pickers.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/suggestpost-picker.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/details/viewer/suggestpost-viewer.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/details/viewer/viewers.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-context-dropdown.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/need-reducer-main.js, webofneeds/won-owner-webapp/src/main/webapp/app/selectors.js, webofneeds/won-owner-webapp/src/main/webapp/app/utils.js, webofneeds/won-owner-webapp/src/main/webapp/config/detail-definitions.js, webofneeds/won-owner-webapp/src/main/webapp/config/details/basic.js, webofneeds/won-owner-webapp/src/main/webapp/style/_button.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_suggestpost-viewer.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_suggestpostpicker.scss
Adds the ability to send "Suggestions" of Needs within a chat
Displays the suggested Post (if present) -> if not one can invoke an action to load the post
Detail Picker works as follows:
-Shows a List of all Open and Loaded Needs to select from (except both of the needs in the currently open connection)
- Also includes a input type=url that includes the abilty to load any need into the state (input validation is currently only based on default url-validation) -> there is no way to check if the url was actually a postUri that has been fetched correctly (no error will be displayed) -> however a succesful fetch should add a need in the suggestionlist to select from... unless the need is already loaded, or is a need that is either part of the currently opened chat-connection
=> Feat detail suggestneed

webofneeds/won-owner-webapp/src/main/webapp/app/sparql-builder-utils.js, webofneeds/won-owner-webapp/src/main/webapp/config/details/jobs.js, webofneeds/won-owner-webapp/src/main/webapp/config/usecase-definitions.js, webofneeds/won-owner-webapp/src/main/webapp/config/usecases/mobility.js, webofneeds/won-owner-webapp/src/main/webapp/config/usecases/professional/job-offer.js, webofneeds/won-owner-webapp/src/main/webapp/config/usecases/professional/job-search.js, webofneeds/won-owner-webapp/src/main/webapp/config/usecases/professional/professional.js, webofneeds/won-owner-webapp/src/main/webapp/config/usecases/real-estate.js
1. Generate some job-offers with varying locations, tags, skills, etc
2. with a different account generate job-searches with intersecting tags, skills, etc and/or nearby locations
3. you should get matches.
if something doesn't work (e.g. because the matcher isn't running), copy-paste the SPARQL-query attached to the job-searches into your nodes Blazegraph (for integration-testing it's <http://satvm05.researchstudio.at:9999/blazegraph/#query>) and change the outer select to `select * from`, to see all (sub-)scores)
Also changes the icons for the job-search/offer use-cases and details to placeholders (until we have better designs)
=> Feat  jobsearch sparql

webofneeds/won-owner-webapp/README.md, webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/details/viewer/petrinet-viewer.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/petrinet-state.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/need-reducer-main.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/parse-connection.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/reduce-connections.js, webofneeds/won-owner-webapp/src/main/webapp/config/details/workflow.js, webofneeds/won-owner-webapp/src/main/webapp/style/_petrinet-state.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_petrinet-viewer.scss
First Implementation Iteration of Active PetriNet instances
What has been done?
- Created petrinet-state component to view the currently markedPlaces and enabledTransitions, add the ability to send the transitionmessage from within this component
- Updated the PetriNetViewer: smaller Download Button, inclusion of petriNetData-component (if present)
- Created a method in post-messages.js that retrieves the petriNetData for the connection that is currently viewed (execute: pm4dbg.loadPetriNetUris() to retrieve the data
- Updated the connection in the state and reducers/actions to store the received data in the reduxstate
ToDo:
- Implement inital and recurring fetch of petriNetData
- Implement a View for all petriNet instances (similar to the agreementData-View)
- Error handling for …
=> Feat detail petrinet update

webofneeds/won-owner-webapp/README.md, webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/petrinet-state.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/message-reducers.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/need-reducer-main.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/reduce-connections.js, webofneeds/won-owner-webapp/src/main/webapp/style/_petrinet-state.scss
Implements Better "loading/dirty" styling of petriNetData
We introduce a isDirty state for the petriNetData, which disables all the petriNetData-Transition buttons, until the state has been refreshed and marked "isDirty"=false
Also if there is already data present we do not display the generic loadingPetriNetData spinner, but show a loading spinner underneath the markedplaces and enabledTransition (which are not-clickable during the load because they are marked as isDirty)
This should allow us to fetch the correct petriNetData whenever we send a message containing references
=> Feat petrinetdata refresh

webofneeds/won-owner-webapp/README.md, webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/chat-textfield-simple.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/combined-message-content.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/connection-message-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/connection-message.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/referenced-message-content.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/need-reducer-main.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/parse-connection.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/parse-message.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/reduce-connections.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/reduce-messages.js, webofneeds/won-owner-webapp/src/main/webapp/app/selectors.js, webofneeds/won-owner-webapp/src/main/webapp/package-lock.json, webofneeds/won-owner-webapp/src/main/webapp/style/_combined-message-content.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_connection-message.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_referenced-message-content.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_won-config.scss
In Order To make our chat-views more useful we try to minify/collapse messages or their respective content so that the view is not cluttered with cascading and duplicate entries
This PR changes the following in the chat-view (aka open connection view)
Any message that has been proposed/claimed/rejected/retracted will be minified in the chat view (see screenshot below
)
The referenced-content of a message will be collapsible/expandable now, the references have the following inital collapsed State:
- forwards -> not collapsed by default
- proposes -> not collapsed by default
- claims -> not collapsed by default
- accepts -> collapsed by default
- proposeToCancel -> collapsed by default
- rejects -> collapsed by default
- retracts -> collapsed by default
If a message containing references is …
=> Feat minify messages

webofneeds/won-owner-webapp/src/main/webapp/elm/Settings/Personas.elm, webofneeds/won-owner-webapp/src/main/webapp/style/won.scss
Fixes #2457 
Other parts of the ui seem to be mostly fine already, with an exception being our login menu. I tried making the font size there bigger, but it doesn't seem to change the behaviour on mobile. Maybe this is because the input elements are also too small? I think I will create a separate issue for this
=> Fixed too-small input font size in elm application

webofneeds/won-owner-webapp/src/main/webapp/app/components/create-search.js
We called the needCreation with one parameter less than expected (due to refac. needed for personas) this wouldnt have been an issue if the new param was the last param of the function but since the persona param was in between the pre-existing params we needed to update all method invocations and simply forgot to do so for a search-need -> thus resulting in handling the nodeUri as the persona which could obciously not been found and therefore resulted in an error while trying to create the search need
tl;dr
this PR fixes this error
fixes #2480
=> Fixes #2480: Creation of Search Needs

webofneeds/won-matcher-sparql/src/main/java/won/matcher/sparql/actor/SparqlMatcherActor.java, webofneeds/won-matcher-sparql/src/main/java/won/matcher/sparql/actor/SparqlMatcherUtils.java, webofneeds/won-matcher-sparql/src/test/java/won/matcher/sparql/SparqlQueryTest.java, webofneeds/won-matcher-sparql/src/test/resources/sparqlquerytest/jobquery-orig.rq
The embedded sparql query gets transformed by the matcher before
execution, adding checks for NoHintForCounterpart flags.
The problem is that this change was applied to each subquery instead of
just the toplevel one. When there is a subquery using 'group by' - the
transformation leads to
...
GROUP BY ?result
HAVING NOT EXISTS {
?result ...
Which blazegraph isn't able to execute, in contrast to jena
=> Fix sparql query transform

webofneeds/won-matcher-sparql/src/main/java/won/matcher/sparql/actor/SparqlMatcherActor.java, webofneeds/won-owner-webapp/src/main/webapp/app/sparql-builder-utils.js
Sparql queries used by the sparql matcher can now project a `?score` variable. The matcher will use that for descending ordering and normalize by the maximum score to produce values between 1 and 0
=> Feat sparql score

webofneeds/won-owner-webapp/src/main/webapp/package-lock.json
Our version of cryptiles (dependency path: jsonld -> request -> hawk -> cryptiles) had a [security vulnerability](https://nvd.nist.gov/vuln/detail/CVE-2018-1000620)
The newest version of request does not depend on hawk anymore, dropping cryptiles entirely.
=> Updated request to fix cryptiles vulnerability

webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-context-dropdown.js
Conversation/Connection Context Dropdown has a "remove connection" button regardless of the connection state:
Here are the displayed labels:
connected -> "Close Connection"
suggested -> "Remove Connection"
SentRequest -> "Cancel Request"
ReceivedRequest -> "Deny Request"
Maybe we should not use a different label since every button results in a closeConnection request, if that should be the case i will adapt this PR accordingly
=> Fixes #2516 close conversation button for all connection states

webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/create-need-action.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/persona-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-header.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-header.js, webofneeds/won-owner-webapp/src/main/webapp/app/need-utils.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/need-reducer-main.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/parse-need.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/toast-reducer.js, webofneeds/won-owner-webapp/src/main/webapp/app/service/need-builder.js, webofneeds/won-owner-webapp/src/main/webapp/app/service/won.js, webofneeds/won-owner-webapp/src/main/webapp/app/utils.js, webofneeds/won-owner-webapp/src/main/webapp/config/detail-definitions.js, webofneeds/won-owner-webapp/src/main/webapp/config/details/basic.js
Fixes adhoc need creation and connect with a remoteNeed (with or without persona -> was broken)
fixes #2505 (-> by removing all the Re content and replacing it with another flag won:DirectResponse and a won:responseToUri detail that contains the needUri that the adhoc need is going to connect to)
Also reimplemented the headerTitles for post-header and connection-header for adhoc needs
The need that is set in the responseToUri is (currently) visible via the won-suggest-post-viewer (since it became a new detail) however i am aware that there are some issues (as seen in #2525) they will be handled with a sep. PR as some issues (e.g. #2446 build upon the changes made in this PR)
=> Refac adhocstruct #2505

webofneeds/won-matcher-sparql/src/main/java/won/matcher/sparql/actor/SparqlMatcherActor.java
Fixes #2519 
This also removes any matching from the is branch onto a seeks branch. This is done because matching in this direction would now require an extensive blacklist of not-to-match values, and a new handling for empty needs. It seems preferable to finally implement a rematching scheduler.
=> Removed is branch from sparql matching

webofneeds/pom.xml
Does not bump all the dependecies that are currently seen as vunerable, because i am not sure if there are sideeffects for the others.
Bumps:
-jackson-databind: 2.8.7 -> 2.8.11.2
-spring-data-commons: 1.13.3.RELEASE -> 1.13.16.RELEASE
-spring:  -> 4.3.8.RELEASE -> 4.3.20.RELEASE
-spring-boot: 1.5.3.RELEASE -> 1.5.17.RELEASE
-spring-security: 4.2.3.RELEASE -> 4.2.9.RELEASE
fixes #2492
=> Bumps maven dependencies

webofneeds/won-owner-webapp/src/main/webapp/app/actions/account-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/load-action.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/needs-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/account-menu.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/login-form.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/signup/signup.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/account-reducer.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/message-reducers.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/need-reducer-main.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/process-reducer.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/reducers.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/toast-reducer.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/view-reducer.js, webofneeds/won-owner-webapp/src/main/webapp/app/utils.js, webofneeds/won-owner-webapp/src/main/webapp/app/won-message-utils.js
To make the reducer calls easier to read in the code and in the redux plugin, i refactored them to dispatch reducers named in a way that it is known what is actually stored in the state (instead of having multiple initialPageLoad or account.login dispatches)
This was not 100% necessary, but it makes the handling of reducers way easier and it gives us better insights in what is actually happening.
Due to this refactoring i found out that there is a big part of dead-code in the `load-action.js` as well as multiple duplicate reducer dispatches that could actually result in bugs that are hard to find.
I see this PR as preliminary work for our new privateId handling as well as for a completely different load approach in the future, we also have it easier now to extract view states from …
=> Refac Reducer Dispatch

webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/hokify/receive/CreateNeedFromJobAction.java, webofneeds/won-matcher-sparql/src/main/java/won/matcher/sparql/actor/SparqlMatcherActor.java, webofneeds/won-matcher-sparql/src/main/java/won/matcher/sparql/actor/SparqlMatcherUtils.java, webofneeds/won-matcher-sparql/src/test/java/won/matcher/sparql/SparqlQueryTest.java, webofneeds/won-matcher-sparql/src/test/resources/sparqlquerytest/hint-for-counterpart/expected.rq, webofneeds/won-matcher-sparql/src/test/resources/sparqlquerytest/nhfc-complex-query1/expected.rq, webofneeds/won-matcher-sparql/src/test/resources/sparqlquerytest/nhfc-complex-query1/input.rq, webofneeds/won-matcher-sparql/src/test/resources/sparqlquerytest/no-hint-for-counterpart/expected.rq, webofneeds/won-matcher-sparql/src/test/resources/sparqlquerytest/query-searchstring-hintForCounterpart-expected.rq, webofneeds/won-matcher-sparql/src/test/resources/sparqlquerytest/query-searchstring-noHintForCounterpart-expected.rq, webofneeds/won-matcher-sparql/src/test/resources/sparqlquerytest/searchstring-query/expected.rq, webofneeds/won-node/src/main/java/won/node/service/impl/NeedInformationServiceImpl.java, webofneeds/won-owner-webapp/src/main/webapp/app/service/need-builder.js, webofneeds/won-owner-webapp/src/main/webapp/app/sparql-builder-utils.js, webofneeds/won-owner-webapp/src/main/webapp/config/usecases/complain.js, webofneeds/won-owner-webapp/src/main/webapp/config/usecases/professional/job-offer.js, webofneeds/won-owner-webapp/src/main/webapp/config/usecases/professional/job-search.js
Improvements to embedded queries for whatsX and jobs
whatsX:
* filter out more results earlier
* jobs:
* project the aggregated score so the matcher can sort properly
* adapted vicinity subquery: two consecutive BIND operators trigger a jena bug in op-> query  
* SparqlMatcherActor & Utils: fix op/query manipulation
* need-builder: always project '?score'
=> Feat improve queries

webofneeds/won-docker/image/bigdata/RWStore.properties, webofneeds/won-matcher-sparql/src/main/java/won/matcher/sparql/actor/SparqlMatcherActor.java, webofneeds/won-owner-webapp/src/main/webapp/app/sparql-builder-utils.js, webofneeds/won-owner-webapp/src/main/webapp/config/details/price.js, webofneeds/won-owner-webapp/src/main/webapp/config/usecase-definitions.js, webofneeds/won-owner-webapp/src/main/webapp/config/usecases/classifieds.js
Adds usecases for "classified ads" that allow offering and searching for objects and services. The demand use case has a custom sparql query that matches to offers containing keywords, the offer use cases don't have custom queries yet. Matches should be symmetrical (i.e. hints sent to both needs), but currently aren't, only demands get hints.
This also changes a property in `webofneeds/won-docker/image/bigdata/RWStore.properties#33` that enables text indexing. As this is a potentially expensive operation, this may impact performance.
Closes #2512
=> Feat classifieds usecases

webofneeds/won-owner-webapp/src/main/webapp/app/sparql-builder-utils.js, webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-goods-service-search.js, webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-rehearsal-room-offer.js, webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-rehearsal-room-search.js, webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-rent-real-estate-offer.js, webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-rent-real-estate-search.js
Fixes #2603 
Also refactors `rentRange` to `priceRange` because the chosen representation is not rent specific.
=> Fix #2603 duplicate price range detail

webofneeds/won-core/src/main/java/won/protocol/model/DataWithEtag.java, webofneeds/won-node/src/main/java/won/node/service/impl/LinkedDataServiceImpl.java
Fixes #2590
This just uses the `notFound` flag in the dataset and does not check whether the connection was deleted or never existed in the first place. I'm not sure if we have that information but I would assume so.
=> Return 404 errors on nonexistant connection instead of crashing

webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/reduce-needs.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/process-reducer.js
Is supposed to fix "Race Condition" in the post-visitor-view
How To Reproduce:
- Create a GroupChat Need with a Persona
- Join the GroupChat with another need (which also holds the persona)
- Add x-other groupchat members (might not be necessary)
copy the shareLink and open it somewhere else -> see that it works now.
TL;DR:
The problem was that we flag certain needs as toLoad or InLoading -> depending on the current state of the webapp... we mark every holds needUri of a persona as well as every memberUri of a group Chat as "toLoad" in the process-state, as well as the need-state, the issue was that we did not check whether or not at least the need-stub is in the state already (and thus overwrote the already loaded need with a stub)
Additionally I changed a clause that did not make any …
=> Fixes #2645 (Race Condition in post-visitor-view)

webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/suggestpost-picker.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/details/viewer/suggestpost-viewer.js, webofneeds/won-owner-webapp/src/main/webapp/app/need-utils.js, webofneeds/won-owner-webapp/src/main/webapp/app/selectors/general-selectors.js, webofneeds/won-owner-webapp/src/main/webapp/style/_suggestpost-viewer.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_suggestpostpicker.scss
- Fixes #2444 , Fixes #2443: you should be able to see a correct error message when trying to add a non need uri
- Fixes #2446: we only allow non-whatsx and active needs to be shared as suggestions, we even allow personas to be shared, since that could be beneficial (to view the needs of the persona for example)
- Fixes #2445 
- Fixes #2442: adds an info label to the suggested item
- Fixes #2449: label does not say connected anymore but informs the user that a connection has already been established (disregarding the state of the connection)
=> Feat  suggestedpost updates #2525

webofneeds/won-owner-webapp/src/main/webapp/app/actions/account-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/cstm-router-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-overview.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/connections/connections.html, webofneeds/won-owner-webapp/src/main/webapp/app/components/connections/connections.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post-item.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/suggestpost-picker.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/details/viewer/suggestpost-viewer.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/group-administration-selection-item.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/group-administration.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-context-dropdown.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-info.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post/post.html, webofneeds/won-owner-webapp/src/main/webapp/app/components/post/post.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/slide-in.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/usecase-group.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/usecase-picker.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/visitor-title-bar.js, webofneeds/won-owner-webapp/src/main/webapp/app/configRouting.js, webofneeds/won-owner-webapp/src/main/webapp/app/need-utils.js, webofneeds/won-owner-webapp/src/main/webapp/app/selectors/general-selectors.js, webofneeds/won-owner-webapp/src/main/webapp/style/_need-overlay.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_suggestpost-viewer.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_suggestpostpicker.scss
depends on #2640 
fixes #2441 
Clicking on:
- a suggested Need
- a responseTo Need (seen in the details view of directResponse needs)
- "show persona" seen in the context-dropdown of a post-info
- a held Need -> seen in the post-info of a persona
- a groupParticipant -> seen in the post-info of a groupFacet-need, as well as the group-administration
will result in an overlay displaying the need/persona information
=> Feat  show details #2441

webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/combined-message-content.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content-general.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/parse-need.js, webofneeds/won-owner-webapp/src/main/webapp/app/selectors/general-selectors.js, webofneeds/won-owner-webapp/src/main/webapp/config/detail-definitions.js, webofneeds/won-owner-webapp/src/main/webapp/config/details/basic.js
Fixes #2465
Generates HumanReadable for Persona using the personaName instead of looking into the jsonld like a fool
Adds website and personaName details so we do not have to parse any special things for viewing a persona or displaying a "author" any longer
This also enables us to show ALL the data stored within a Persona-Need (when viewing a persona)
=> Refactor access within component to use extracted Content instead of jsonld parsing

webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-selection-item.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-context-dropdown.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post/post.html, webofneeds/won-owner-webapp/src/main/webapp/app/components/post/post.js, webofneeds/won-owner-webapp/src/main/webapp/style/_need-overlay.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_post-content.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_post-visitor.scss
Show loading indicator while loading, and failedToLoad info if the post was not able to be fetched
fixes #2630 
How to Test:
- open a visitorlink of a deletedNeed -> you should see that the need has been deleted
- open a visitorlink of a need that takes long to load (e.g. a need with images) -> you should see a loading indicator until the need has been loaded
- open a deleted post by adding &viewNeedUri=[deletedNeedUri] into the connections url -> this way you will mock clicking on a suggestedPost and see that the need has been deleted in the overlay
- look at a hint of a deletedNeed (e.g. if a whatsNew match could not be loaded) -> see that the click interaction to open the right side (view connection) was removed -> fixes #2631
=> Fixes post-visitor view and viewNeedUri-modalbox view for deletedNeeds

webofneeds/won-owner-webapp/src/main/webapp/package-lock.json, webofneeds/won-owner-webapp/src/main/webapp/package.json, webofneeds/won-owner-webapp/src/main/webapp/webpack.config.ts
Fibers speeds up our sass builds, but needs a native build, which causes problems with our windows machines.
=> Removed fibers from dependencies

webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-header.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-indicators.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-selection-item.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-overview.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/connections/connections.html, webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/suggestpost-picker.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/details/viewer/suggestpost-viewer.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/extended-connection-indicators.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/group-administration.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/group-image.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/group-post-messages.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/combined-message-content.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/connection-message.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/post-content-message.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-header.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-info.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/square-image.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/visitor-title-bar.js, webofneeds/won-owner-webapp/src/main/webapp/app/need-utils.js, webofneeds/won-owner-webapp/src/main/webapp/app/process-utils.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/parse-need.js
- execute some ng-repeats over uri arrays only
- add "track by [xUri]" to the ng-repeats (might reduce watch and rerender efforts
- Create PersonaIdenticon within the addNeed parsing (and not within the constructor of the square-image)
- fixes isLoading call (to show the topNav-indicator)
- one-way bind all uris we know will only be undefined or one set value but never valueX to valueY
- Remove unused component parameters (to reduce watches)
fixes #2693
=> Update UI-Performance a little

.gitignore, documentation/build-with-eclipse.md, documentation/installation-cryptographic-keys-and-certificates.md, webofneeds/won-cryptography/pom.xml, webofneeds/won-docker/image/owner/Dockerfile, webofneeds/won-docker/image/wonnode/Dockerfile, webofneeds/won-docker/pom.xml
Improved bouncycastle install documentation, limiting it to modifying the local java installation (instead of fiddling with the IDE and Tomcat)
Changed the name of the folder into which the maven build copies the bouncycastle libs from `tomcat-libs` to `required-libs`.
=> Feat fix bouncycastle docs

webofneeds/won-owner-webapp/src/main/webapp/app/components/group-post-messages.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/post-content-message.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js, webofneeds/won-owner-webapp/src/main/webapp/app/message-utils.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/parse-message.js, webofneeds/won-owner-webapp/src/main/webapp/style/_connection-message.scss
- Implements parsing any hintMessage as read (therefore no "unread" message will appear when they are fetched)
- Removes the hintMessages from being displayed as sep. messages in the chat-view (groupChat as well as 1to1 chat)
- Adds a new parameter to the post-content-message component (connectionUri) so we can figure out a way to display the (now) omitted hints and their respective rating in another way (in the future)
fixes #2691 
fixes #2359 
fixes #2600
=> Fix wrongstatus #2691

webofneeds/won-owner-webapp/src/main/webapp/app/actions/account-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/load-action.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-header.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post/post.html, webofneeds/won-owner-webapp/src/main/webapp/app/components/post/post.js, webofneeds/won-owner-webapp/src/main/webapp/app/selectors/view-selectors.js, webofneeds/won-owner-webapp/src/main/webapp/app/view-utils.js, webofneeds/won-owner-webapp/src/main/webapp/app/won-message-utils.js
Fixes #2692 
removed the check for visitorNeedUri fetching from account-actions.js and load-action.js in favor of fetching the need from within the visitor component (if it has not been loaded yet)
- that way we can react to needUri changes in the url and fetch the need if necessary without having to rely on a reload that would invoke the load-action or account-action promise chain
=> Fix  visitorload #2692

webofneeds/won-owner-webapp/src/main/webapp/style/_group-post-messages.scss
how to test:
look at a suggested/connected groupchat you will see that the share icon is not at the same position as it is in a 1to1 chat
=> share icon in chatToGroup connection was not aligned in grid due to mismatch of name

webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-overview.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/group-administration-selection-item.js
Collapse all other open connection-lists when opening a need-connection-list -> so that the view is not tooo cluttered....
However if another connection is currently open in the right side (is visible in the desktop view) the need-connection-list containing the open element will not be collapsed
=> Only open one connection-need connection list

webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-context-dropdown.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/connection-message.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/post-content-message.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-context-dropdown.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-info.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post/post.html, webofneeds/won-owner-webapp/src/main/webapp/style/_need-overlay.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_post-content.scss
Changes the Overlay "back"-button icon from the close image to the back image in mobile -> this prevents confusion as the close did not actually close the overlay (if you went from one overlay to the another for example)
Changes the min and max height of the overlay in desktop view, so that the close button seems to close the "top"-element and show the element underneath (aka the previous element), due to the fixed height we somewhat indicate that the previous view was still underneath the current overlay and thus the interface seems less jumpy and confusing
requires #2746  (due to included changes)
Changes the link for the following clickable Elements:
- Clicking on the NeedIcon within a chat (the one next to the chat-message) opens the need detail view as an overlay (instead of showing …
=> Refac  overlaystyle

webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/connection-message.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js, webofneeds/won-owner-webapp/src/main/webapp/style/_connection-message.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_group-post-messages.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_post-content-message.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_post-messages.scss
Fixes #2761 -> quick-request/remove buttons in the suggestions list of a need, did not mark these connections as read and thus the propagation towards the need did not occur resulting in an always unread need even if nothing was visible unread -> this is fixed now
Fixes #2758 -> having to click every single suggestion to mark it as read was tedious -> this PR fixes this by marking all visible suggestions as read after a timeout (similar to unread connection messages)
Fixes styling issues with the petrinet and agreement-data header
Implements a nicer way to style unread messages (indicator is now the "same" styling as any other unread indicator (left border instead of background)
=> Fix  #2761 and #2759

webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/persona-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/elm.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/reduce-connections.js, webofneeds/won-owner-webapp/src/main/webapp/elm.json, webofneeds/won-owner-webapp/src/main/webapp/elm/Actions.elm, webofneeds/won-owner-webapp/src/main/webapp/elm/Application.elm, webofneeds/won-owner-webapp/src/main/webapp/elm/AssocList/Extra.elm, webofneeds/won-owner-webapp/src/main/webapp/elm/EditNeed.elm, webofneeds/won-owner-webapp/src/main/webapp/elm/Element/Background/Styled.elm, webofneeds/won-owner-webapp/src/main/webapp/elm/Element/Border/Styled.elm, webofneeds/won-owner-webapp/src/main/webapp/elm/Element/Font/Styled.elm, webofneeds/won-owner-webapp/src/main/webapp/elm/Element/Input/Styled.elm, webofneeds/won-owner-webapp/src/main/webapp/elm/Element/Styled.elm, webofneeds/won-owner-webapp/src/main/webapp/elm/Elements.elm, webofneeds/won-owner-webapp/src/main/webapp/elm/Icons.elm, webofneeds/won-owner-webapp/src/main/webapp/elm/Old/Persona.elm, webofneeds/won-owner-webapp/src/main/webapp/elm/Old/Skin.elm, webofneeds/won-owner-webapp/src/main/webapp/elm/Palette.elm, webofneeds/won-owner-webapp/src/main/webapp/elm/PublishButton.elm, webofneeds/won-owner-webapp/src/main/webapp/elm/RatingView.elm, webofneeds/won-owner-webapp/src/main/webapp/elm/Settings.elm, webofneeds/won-owner-webapp/src/main/webapp/elm/Settings/Account.elm, webofneeds/won-owner-webapp/src/main/webapp/elm/Settings/Personas.elm, webofneeds/won-owner-webapp/src/main/webapp/elm/Skin.elm, webofneeds/won-owner-webapp/src/main/webapp/elm/SubmitButton.elm, webofneeds/won-owner-webapp/src/main/webapp/style/_elm-ui-shim.scss
Fixes #2695 
It is now possible, via a button in the need overview, to add or remove a persona.
Caveats:
* Currently the button state does not get updated correctly, because it depends on the `jsonld` content of a need, which is not updated
* This PR contains a large wrapper around `Element` which, after some thought, will be removed and made more specific.
* The current state representation in Elm only supports a very narrow part of our needs
* All of the created backend needs a design pass so it will be generally usable.
* In this PR I ran into #2778
=> Allow attaching and detaching of personas

webofneeds/conf/node.properties, webofneeds/conf/owner.properties
**Config file change** - this needs updating of your local configurations
This change prevents a deadlock that may occur when running a debugbot locally with an hqsl db (as according to the default configuration). The deadlock prevents `CONNECT` from being executed successfully as the bot's write-lock prevents the bot to read to check access rights. 
As this happens only with hsql's default transaction model and not e.g. with postgresql's default of MVCC, this PR changes the hsql config to use MVCC. (see [this thread on Stack Overflow](https://stackoverflow.com/questions/16108643/unit-tests-of-hibernate-based-code-on-top-of-hsqldb-1-8-1-3-no-longer-work-on-hs))
fixes #2598 ( i just assume that this issue is going to be fixed since the problem seems to/could be the same)
=> Changed db lock strategy to avoid debugBot deadlock

webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content-general.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/view-reducer.js, webofneeds/won-owner-webapp/src/main/webapp/app/view-utils.js, webofneeds/won-owner-webapp/src/main/webapp/style/_post-content-general.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_post-content.scss
- Removes Persona & Rating from post-content-general -> is in Persona tab now
- Adds Border to post-content-general to be more suitable for our default style
- Removes the ability to collapse the general-info (since not alot of info is going to clutter the interface anymore anyway)
- Moves the post-content-general to the top of the post-content again
=> Refac  post content general

webofneeds/won-docker/image/bigdata/Dockerfile
=> Don't download blazegraph with every build

webofneeds/won-owner-webapp/src/main/java/won/owner/pojo/RestStatusResponse.java, webofneeds/won-owner-webapp/src/main/java/won/owner/web/rest/RestUserController.java, webofneeds/won-owner-webapp/src/main/webapp/app/components/settings/settings-wrapper.js, webofneeds/won-owner-webapp/src/main/webapp/app/service/won.js, webofneeds/won-owner-webapp/src/main/webapp/elm/Settings.elm, webofneeds/won-owner-webapp/src/main/webapp/elm/Settings/Account.elm, webofneeds/won-owner-webapp/src/main/webapp/elm/Settings/Export.elm
Fixes #2608
Fixes #2607
Progress:
https://github.com/researchstudio-sat/webofneeds/blob/f9dc42cfc75b5ac9bcac4aa70270e4f5d830de60/webofneeds/won-owner-webapp/src/main/webapp/elm/Settings/Account.elm#L234
=> Not displaying export without verification.

webofneeds/pom.xml, webofneeds/won-owner-webapp/pom.xml
Removes apache.commons fileupload, was never used anyway -> and resulted in a visible vulnerability in github
=> Removed dependency that was not used

webofneeds/won-owner-webapp/src/main/webapp/style/won.scss
add :focus outline color to be won-secondary-color by default (should overwrite any browser specific focus behaviour)
=> fix textfield focus color to be browser independent (fixes #1813) 

webofneeds/won-core/src/main/java/won/protocol/repository/ConnectionRepository.java, webofneeds/won-core/src/main/java/won/protocol/repository/NeedRepository.java, webofneeds/won-core/src/main/java/won/protocol/service/LinkedDataService.java, webofneeds/won-core/src/main/java/won/protocol/service/NeedInformationService.java, webofneeds/won-core/src/main/java/won/protocol/vocabulary/WON.java, webofneeds/won-node-webapp/src/main/java/won/node/web/LinkedDataWebController.java, webofneeds/won-node/src/main/java/won/node/service/impl/LinkedDataServiceImpl.java, webofneeds/won-node/src/main/java/won/node/service/impl/NeedInformationServiceImpl.java, webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/reduce-connections.js, webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js, webofneeds/won-owner-webapp/src/main/webapp/app/service/won.js, webofneeds/won-owner-webapp/src/main/webapp/app/won-localstorage.js, webofneeds/won-owner-webapp/src/main/webapp/app/won-message-utils.js
fixes #2778 
Frontend changes:
- removes the closedConnUri check from localStorage (closedConnUris wont be stored in localStorage at all)
- implements a new method that retrieves not only the connectionUri but also the state
- only add active Connections based on their real state from the server and not from localStorage
Backend changes:
- removed unused methods
- connectionContainer updates -> do not only give a list of connUris but also their state and facets and additional info
=> remove saving closed connuris in localstorage and use the correct state from the backend (Feat lds uris by connstate)

webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-overview.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/group-post-messages.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/send-request.js, webofneeds/won-owner-webapp/src/main/webapp/app/need-utils.js, webofneeds/won-owner-webapp/src/main/webapp/app/process-utils.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/need-reducer-main.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/reduce-connections.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/process-reducer.js, webofneeds/won-owner-webapp/src/main/webapp/app/selectors/connection-selectors.js, webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js, webofneeds/won-owner-webapp/src/main/webapp/app/view-utils.js, webofneeds/won-owner-webapp/src/main/webapp/app/won-message-utils.js, webofneeds/won-owner-webapp/src/main/webapp/style/_usecase-picker.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_won-markdown.scss
~~blocked by #2840~~
related to #2828 (same changes just rebased with current master)
this pr stores the connection state and the (own) facet(type) of each connection directly after retrieving the connection container, this makes it easier to reload or prioritize loading by connectionstate and/or facet
fixes #2823
fixes #2840
=> Feat store connection state and (own) facettype in redux-state onload #2823  (rebased)

webofneeds/won-owner-webapp/src/main/webapp/app/account-utils.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/account-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/create-need-action.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/about/about.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/account-menu.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/chat-textfield.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/create-search.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/logged-in-menu.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/login-form.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/modal-dialog.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/publish-button.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/send-request.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/settings/settings-wrapper.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/signup/signup.html, webofneeds/won-owner-webapp/src/main/webapp/app/components/signup/signup.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/slide-in.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/submit-button.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/topnav.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/usecase-picker.js, webofneeds/won-owner-webapp/src/main/webapp/app/configRouting.js, webofneeds/won-owner-webapp/src/main/webapp/app/process-utils.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/view-reducer.js, webofneeds/won-owner-webapp/src/main/webapp/app/selectors/view-selectors.js, webofneeds/won-owner-webapp/src/main/webapp/skin/current/tos.html, webofneeds/won-owner-webapp/src/main/webapp/style/_modal-dialog.scss
Adds a modal-dialog before executing the following actions in the following places (this is also how/where to test) when not logged in:
- publish in create-post
- publish in create-search
- createWhatsNew in usecase-picker
- createWhatsAround in usecase-picker
- createWhatsNew in about page
- createWhatsAround in about page
- Send (AdHoc)-Request from visitor view.
All these actions display a "Attention- if you proceed you accept the tos"-dialog now,
no just closes the dialog
yes continues with corresponding action
fixes #2537 
we could implement a login dialog as another option within this new dialog -> this is a different issue though (see #2833)
If there are issues with the wording of the dialog please change directly within this pr:
see `modal-dialog.js` component
=> Feat  agree tos private #2537

webofneeds/won-owner-webapp/src/main/webapp/app/components/post-info.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/send-request.js, webofneeds/won-owner-webapp/src/main/webapp/app/usecase-utils.js, webofneeds/won-owner-webapp/src/main/webapp/config/detail-definitions.js, webofneeds/won-owner-webapp/src/main/webapp/config/details/basic.js, webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-cycling-interest.js, webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-cycling-plan.js, webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-lunch-interest.js, webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-lunch-plan.js
Refactored the cycling/lunch interest and plan usecases:
- add type s:PlanAction in draft
- refactor sPlanAction detail to eventObject and remove the parsing of the type directly within the detail
- fixed a parseFromRDF bug that prevented us from storing the eventObject within the state
Refactored findUseCaseByNeed to include a check for eventObjects if the need type is also a s:PlanAction -> needs have corresponding useCases now
fixes #2774 
HOW TO TEST:
- Create each of the Lunch/Cycling Plan/Interest  UseCases
- Check the redux state for the corresponding needs in the console and look at the ["matchedUseCase", "identifier"] -> this should include the correct useCase for each of the needs
=> Fix find interests/plans  UseCases #2774

webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/suggestpost-picker.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content-participants.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content.js, webofneeds/won-owner-webapp/src/main/webapp/app/need-utils.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/need-reducer-main.js, webofneeds/won-owner-webapp/src/main/webapp/style/_post-content-participants.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_post-content.scss
fixes #2690 
Adds the ability to invite groupmembers (with the suggestpost-picker) in the Participants tab of owned GroupNeeds -> excludes/disallows any need that doesnt have the Group or ChatFacet, as well as any member need that is already present (including the pending ones, closed connections are allowed to be added again via suggestions)
How to test:
- open a groupchat-need
- go to the participants tab of that groupchat-need
- see the invite option underneath the participants list
- add any need you like (and see it pop up as a "Participant")
The following needs are inviteable:
- any need that is not yet a member or pending member of the groupchat
- any need that has the group or chatfacet
- any need that is not a whatsnew or whatsaround
- any need that isnt the groupchat itself
=> Feat  invite to group #2690

webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-context-dropdown.js, webofneeds/won-owner-webapp/src/main/webapp/app/usecase-utils.js, webofneeds/won-owner-webapp/src/main/webapp/config/details/basic.js
- Fixes the parseToRDF of eventObject to work with strings and also lists of eventObjects
- Fixes findUseCaseByNeed to check for multiple eventObjects (if multiples are defined in the useCase/need)
- Fixes a problem that any useCase that has been edited (or used as a template) will display the edited content within the next empty useCase of that type (see comment in #2859)
- Disables the save button in the editNeed view if the edited need becomes invalid
- Removes the "post" from the "Edit post" label in the post-context-dropdown
fixes #2859
=> Fix editfail #2859

webofneeds/won-owner-webapp/src/main/webapp/config/details/basic.js
Fixed parsing error of parseFromRDF of type, did not ONLY happen when editing "Need A Lift" usecases and error had nothing to do with routeparsing itself -> the problem was in every need where the useCase did not define any seeks: types at all -> these were parsed as a single item list within the need seeks state (one item with value of "null") -> this produced a parseToRDF of the type detail with @type: null, and that is not valid.
Fix was to ensure that type detail is only added to the seeks content (upon need parsing) if there are actual types in the seeks branch
fixes #2863
=> Fixes parseFromRDF mishap in type detail

webofneeds/won-owner-webapp/README.md, webofneeds/won-owner-webapp/src/main/webapp/app/account-utils.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-context-dropdown.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/details/viewer/suggestpost-viewer.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content-participants.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content-persona.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-content.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-context-dropdown.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-info.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-menu.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-messages.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-share-link.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post/post.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/send-request.js, webofneeds/won-owner-webapp/src/main/webapp/app/need-utils.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/account-reducer.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/need-reducer-main.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/parse-need.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/reduce-connections.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/reduce-messages.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/reduce-needs.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/process-reducer.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/reducers.js, webofneeds/won-owner-webapp/src/main/webapp/app/selectors/general-selectors.js
See description in issue #2862 
What has been done?
- removed the isOwned bool parameter from the needState completely
- added ownedNeedUris to the account-redux-state in our app
- all usages of needUtils.isOwned have changed to generealSelectors.isNeedOwned function
- This removes the race condition and also gives us the ability to handle our pageLoad or accountLogin completely different -> refactoring opportunities arise
caveat:
- i removed all isOwned occurences from the codebase, however the ELM state still uses some of the isOwned and does not have any knowledge about the account state yet (afaik) -> however testing persona creation and subsequent viewing of the personas in the elm components still work so i guess this can be handled after this pr (if need be)
fixes #2862
=> Fix  need fetch rc #2862

webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/image-picker.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/pickers.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/details/viewer/image-viewer.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/details/viewer/viewers.js, webofneeds/won-owner-webapp/src/main/webapp/config/details/files.js, webofneeds/won-owner-webapp/src/main/webapp/style/_image-viewer.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_imagepicker.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_sizing-utils.scss
- Implemented sep. image-viewer instead of file-viewer for images detail (in post-infos or as a message)
- Implement sep. image-picker with the ability to set a default image (default image is set per default to the first image that is uploaded or the first image that remains after an image has been removed) -> fixes #2811 
fixes #2821
fixes #2814 -> please check this was not reproducible on my machine
Caveat: currently there is no option in the picker to NOT have a default image -> not sure if this is something that we have to worry about though.
=> Feat  image viewer rework

webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/need-card.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/need-map.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/overview/overview.js, webofneeds/won-owner-webapp/src/main/webapp/app/need-utils.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/message-reducers.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/need-reducer/need-reducer-main.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/process-reducer.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/reducers.js, webofneeds/won-owner-webapp/src/main/webapp/app/won-utils.js, webofneeds/won-owner-webapp/src/main/webapp/config/details/files.js, webofneeds/won-owner-webapp/src/main/webapp/style/_need-card.scss, webofneeds/won-owner-webapp/src/main/webapp/style/won.scss
- Uses actual default Image instead of the first Image of the images detail (checks for "default" in state of the images -> look at `parseFromRDF` in `files.js` images-detail to see the RDF representation
- Shows "nopersona attached"-label if the need has a holdableFacet but no persona attached (in whats new overview need-cards)
- Added attributes to the need-map component
- `disable-controls`: disables zoom, pan, drag etc.
- `default-layer-only`: does not add any other layers (e.g. transit) to the leaflet map
- `add-current-location` : adds a marker with the current geolocation of the user
- The map initialization was enhanced so that you can provide the overrideOptions as a function parameter (used for `disable-controls` in need-map, and need-card component)
- Adds a markerIcon …
=> Feat  enhance need card

webofneeds/won-vocab/src/main/resources/ontology/ext/won-ext-hold.ttl, webofneeds/won-vocab/src/main/resources/ontology/won-core.ttl
To avoid having to either perform inference or annotate each socket with
its type and its configuration, the distinction of type and
configuraiton was removed. A socket's socket type is now its definition;
SocketDefinitions are individuals.
=> Refactor ontologies

webofneeds/won-bot/src/main/java/won/bot/integration/BotOwnerCallback.java
This should stop most to all exceptions caused by echos from bot actions. 
To test, start a bot that does not handle echo messages well, e.g. the Paypal bot and check for exceptions caused by the bot not owning the atom it's communicating with.
Fixes https://github.com/researchstudio-sat/won-payment/issues/4
Known issue: if old paypal bot factory atoms exist on a server instance, there still will be unknown uri exceptions. Those are not caused by any echos sent.
=> Stopped handling echos as new events

webofneeds/conf/node.properties, webofneeds/won-core/src/main/java/won/protocol/jms/ActiveMQServiceImpl.java, webofneeds/won-core/src/main/java/won/protocol/jms/MatcherActiveMQServiceImpl.java, webofneeds/won-core/src/main/java/won/protocol/vocabulary/WON.java, webofneeds/won-matcher-service/src/main/java/won/matcher/service/nodemanager/config/ActiveMqWonNodeConnectionFactory.java, webofneeds/won-node/src/main/java/won/node/service/impl/LinkedDataServiceImpl.java
Renamed the RDF properties used to specify how to connect to the WoN node via activemq.
How to test:
* Check https://satvm05.researchstudio.at/won/resource (on integrationtest). The new properties look like this:
```
won:supportsWonProtocolImpl  [ a                         won:WonOverActiveMq ;
won:atomActivatedTopic    "MatcherProtocol.Out.Atom" ;
won:atomCreatedTopic      "MatcherProtocol.Out.Atom" ;
won:atomDeactivatedTopic  "MatcherProtocol.Out.Atom" ;
won:atomDeletedTopic      "MatcherProtocol.Out.Atom" ;
won:brokerUri             <ssl://satvm05.researchstudio.at:61617> ;
won:matcherQueue          "MatcherProtocol.in" ;
won:nodeQueue             "AtomProtocol.in" ;
won:ownerQueue            "OwnerProtocol.in"
```
If you see these, you're running the PR's code
The change is successful …
=> Feat  deuglify activemq properties

webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/location-picker.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/pickers.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/pokemon-gym-picker.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/pokemon-raidboss-picker.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/details/viewer/pokemon-gym-viewer.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/details/viewer/pokemon-raidboss-viewer.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/details/viewer/viewers.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/atom-reducer/parse-atom.js, webofneeds/won-owner-webapp/src/main/webapp/app/won-label-utils.js, webofneeds/won-owner-webapp/src/main/webapp/app/won-utils.js, webofneeds/won-owner-webapp/src/main/webapp/config/detail-definitions.js, webofneeds/won-owner-webapp/src/main/webapp/config/details/location.js, webofneeds/won-owner-webapp/src/main/webapp/config/details/pokemon.js, webofneeds/won-owner-webapp/src/main/webapp/config/usecase-definitions.js, webofneeds/won-owner-webapp/src/main/webapp/config/usecases/group-interests.js, webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-pokemon.js, webofneeds/won-owner-webapp/src/main/webapp/images/won-icons/ico36_dumbbell.svg, webofneeds/won-owner-webapp/src/main/webapp/images/won-icons/ico36_pokeball.svg, webofneeds/won-owner-webapp/src/main/webapp/images/won-icons/ico36_pokemon-raid.svg, webofneeds/won-owner-webapp/src/main/webapp/style/_datetimepicker.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_locationpicker.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_pokemon-gym-viewer.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_pokemon-raidboss-viewer.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_pokemongympicker.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_pokemonraidbosspicker.scss
- Adds 2 new UseCases:
- Pokemon Go Raid (GroupChat)
- includes location detail (for gym location)
- includes description detail (for gym info)
- includes gyminfo detail (for if gym is an ex gym)
- includes raidboss detail (pick pokemon hatchtime, level etc)
- Pokemon Go Raid Interest
- does not include any special filter detail (yet)
- once created enables users to create pokemon go raids
- Adds 2 new Details:
- pokemon RaidBoss Detail
- pokemon Info Detail
- Fixes #2813 by allowing a user to set an alternative address name after the location has been chosen, that way we can name locations and include their door numbers, or name locations based on a user chosen string (e.g. for pokemongo gym/arena names)
Caveat:
- the 2 new usecases do not yet create any sparql queries for matching (how …
=> Spoco Pokemon Go UseCases and Details

documentation/letsencrypt/README.md, webofneeds/won-docker/deploy/live_satvm01/docker-compose.yml, webofneeds/won-docker/image/letsencrypt/Dockerfile
Instead of having a letsencrypt docker container run permanently with a cronjob being executed within, this moves the cronjob to satvm01. The cronjob inside the docker container is created by installing certbot and cannot be edited. Instead of using this cronjob, cron is no longer installed inside the docker container.
After merging these changes, starting the letsencrypt container(s) should run the certificate renewal script from won-docker before shutting down again. There are now cronjobs that start both letsencrypt containers once daily (at around noon).
=> Create letsencrypt cronjob

webofneeds/won-core/src/main/java/won/protocol/util/DefaultAtomModelWrapper.java, webofneeds/won-owner-webapp/src/main/java/won/owner/pojo/AtomPojo.java, webofneeds/won-owner-webapp/src/main/java/won/owner/web/rest/RestAtomController.java, webofneeds/won-owner-webapp/src/main/webapp/app/atom-utils.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/atom-reducer/parse-atom.js, webofneeds/won-owner-webapp/src/main/webapp/style/_atom-card.scss
- Added the jobLocation of JobPostings to the responseMetaAtoms and include a maxDistance check for this location within the getAllAtoms (rest/atoms/all) endpoints
HowToTest: (Any node that has JobPostings, e.g. integration-test)
- Click What's Around -> atom-cards of jobPostings should show up (atom-card displays the jobLocation directly within the card)
- Click What's New -> see that atom-cards of jobPostings display the jobLocation directly within the card as well
AtomCard/WhatsAround Behaviour:
- measuring and sorting distance between given Location and atomLocation also includes the jobLocation now, if an atom has both a location and a jobLocation the jobLocation is "defined" as the preferred or prioritized location and will be used for calculations -> see `atom-utils.js …
=> Find JobPostings within WhatsAround

webofneeds/won-matcher-service/src/main/java/won/matcher/service/rematch/service/RematchSparqlService.java, webofneeds/won-node/src/main/java/won/node/camel/processor/annotation/DefaultSocketMessageProcessor.java, webofneeds/won-node/src/main/java/won/node/camel/processor/annotation/FixedMessageProcessor.java, webofneeds/won-node/src/main/java/won/node/camel/processor/annotation/FixedMessageReactionProcessor.java, webofneeds/won-node/src/main/java/won/node/camel/processor/annotation/SocketMessageProcessor.java, webofneeds/won-node/src/main/java/won/node/camel/processor/fixed/ConnectionStateChangeReactionProcessor.java, webofneeds/won-node/src/main/java/won/node/camel/processor/general/ConnectionStateChangeBuilder.java, webofneeds/won-node/src/main/java/won/node/camel/processor/general/MessageTypeSlipComputer.java, webofneeds/won-node/src/main/java/won/node/camel/processor/general/SocketDerivationProcessor.java, webofneeds/won-node/src/main/java/won/node/socket/SocketService.java, webofneeds/won-node/src/main/java/won/node/socket/businessactivity/package-info.java, webofneeds/won-node/src/main/java/won/node/socket/impl/package-info.java, webofneeds/won-node/src/main/java/won/node/socket/package-info.java
With this PR, a change to derived data (via establishing a connection or closing one) triggers a rematching for the atom in question. 
This became necessary as we started to require buddy relationships for matching. Behind the scenes, this is the course of events when Persona P1 creates atom A1:
1. A1 is created, 
2. matchers are notified
3. the connection to P1 is established. 
Consequently, matchers saw neither `A1 hold:heldBy P1` nor  `P1 hold:holds A1` and the embedded SPARQL query found nothing.
With the PR
* matchers are notified after a connection is established or closed
* matchers fetch fresh atom data for rematching
* New capabilities for message processors were added to the node:
- allowing to specify a processor for all directions or types
- allowing to specify multiple …
=> Rematch on derived data change

webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/create-atom-action.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/persona-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/atom-utils.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/send-request.js, webofneeds/won-owner-webapp/src/main/webapp/app/owner-api.js, webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-cycling.js
Automatically open connect requests from an enabledUsecase to be accepted (both atoms belong to the current user).
- Creates the ability to "Plan a Ride" and make the interest join the groupchat automatically without having to accept the invite
- removes the ability to request adHocConnections of owned atoms (only enabledUseCases are possible)
- Fixes #2957 -> enabled UseCases did not produce a query, now they do
=> Feat  autoopen group

webofneeds/won-owner-webapp/pom.xml, webofneeds/won-owner-webapp/src/main/java/won/owner/web/WonOwnerMailSender.java, webofneeds/won-owner-webapp/src/main/java/won/owner/web/websocket/WonWebSocketHandler.java, webofneeds/won-owner-webapp/src/main/resources/mail-templates/hint-notification.vm, webofneeds/won-owner-webapp/src/main/resources/mail-templates/multiple-hints-notification.vm, webofneeds/won-utils/pom.xml, webofneeds/won-utils/won-utils-batch/pom.xml, webofneeds/won-utils/won-utils-batch/src/main/java/won/utils/batch/BatchingConsumer.java, webofneeds/won-utils/won-utils-batch/src/test/java/won/utils/batch/BatchingConsumerTests.java
Adds a batching feature for emails and applies it to HINT mails. 
The current settings for hint-mails are (see WonWebSocketHandler.java)
```
BatchingConsumer.Config config = new BatchingConsumer.ConfigBuilder()
.consumeFirst(true) // send the first mail immediately
.maxBatchAge(Duration.ofHours(24)) // empty batch at least once a day
.maxItemInterval(Duration.ofMinutes(10)) // wait 10 minutes after the last hint, then send mail
.minChunkInterval(Duration.ofHours(6)) // send at most 1 mail every 6 hours (not counting the one for the first match)
.maxBatchSize(50) // as soon as we reach 50 hints, send mail
.build();
```
=> Reduce number of hint-emails

webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/pokemon-raidboss-picker.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/details/viewer/pokemon-raidboss-viewer.js, webofneeds/won-owner-webapp/src/main/webapp/config/details/pokemon.js, webofneeds/won-owner-webapp/src/main/webapp/style/_pokemon-raidboss-viewer.scss
Known issues: 
* a few pictures ~~mostly~~ don't work, this is due to the links returned by the listservice
* ~~pokemon viewer currently can't display all pokemon, this is due to the viewer using the fallback list to retrieve information instead of its own fetch call - to fix this, we need to either update the fallback list (necessary anyway) or refactor pokemon viewing to also use the listservice~~ fixed
* ~~pokemon viewer uses placeholder icons until fixed pokemon picture links are available~~ fixed
ADDITION:
* ~~the fetching of pokemon raids has revealed that "level" is not necessarily an attribute that is present -> if a pokemon has already hatched(e.g. the raid Started) there might not be a level present, so please let us change the picker and viewer as well as the detail validation …
=> Feat fetch pokemon from service

webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-content-holds.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/post-info.js, webofneeds/won-owner-webapp/src/main/webapp/app/configRouting.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/atom-reducer/atom-reducer-main.js, webofneeds/won-owner-webapp/src/main/webapp/app/redux/selectors/general-selectors.js, webofneeds/won-owner-webapp/src/main/webapp/elm/PublishButton.elm, webofneeds/won-owner-webapp/src/main/webapp/style/_atom-content-holds.scss
Fixes #2987 -> Reaction UseCasesreactionAtom connections did not show up after creation (reload was necessary)
Fixes #2958 -> Enabled UseCases of an atom with an attached persona preselect that persona as the "publish as"-persona in the creation of the enabled useCase
Adds "+ New" Button within each owned Personas Post Tab, and preselects the owned Persona within the atom creation
=> Feat  publish preset persona #2958

webofneeds/won-owner-webapp/src/main/webapp/app/actions/account-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/atoms-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/connections-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/load-action.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/atom-reducer/atom-reducer-main.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/process-reducer.js, webofneeds/won-owner-webapp/src/main/webapp/app/redux/state-store.js, webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js, webofneeds/won-owner-webapp/src/main/webapp/app/utils.js
Fixes #2867 -> if an atom with an active connection is edited, there was a racecondition breaking the atom in our redux state and showing it as failedToLoad (only happened sometimes), this is now fixed
Fixes #2871 -> loading atoms that have changed or trying to reload them after an edit won't result in atomLoading failed any longer
Fixes #2892 -> showMoreMessages did not work after an edit of the need with the connection that we try to load more Messages of -> this is "fixed" now, due to an edit messing with our rdfstore we lose the eventUris as rdf and can't sort them anymore, so instead of trying to get the next x-messages we simply load all messageUris we know are still to be loaded within this connection (fork applies only after an edit of an atom)
=> Fix  msgloading after edit

webofneeds/won-owner-webapp/src/main/java/won/owner/web/rest/RestAtomController.java, webofneeds/won-owner-webapp/src/main/java/won/owner/web/rest/ServerSideActionController.java, webofneeds/won-owner-webapp/src/main/java/won/owner/web/websocket/WonWebSocketHandler.java, webofneeds/won-owner/src/main/java/won/owner/model/User.java, webofneeds/won-owner/src/main/java/won/owner/model/UserAtom.java
Fixes #2988 
WRT #2988, Changing the data structure from `List` to `Set` as suggested by @quasarchimaere ultimately did the trick.
This PR also contains minor refactoring of the `WonWebsocketHandler`, decoupling websocket/mail/push code from the logic that is responsible for updating the user's atoms.
The bug is hard to reproduce - it seems to depend on the user's data being in a specific configuration; I can reliably get there with one matchat user, but not with any other test user. 
*How to test*:
* check if creating with/without persona works
* go to the detail view of the new posting, check that it is not an external view (eg. the menu would not contain a `Remove` entry)
* Make sure you receive suggestions with that atom.
=> Fix  useratom insert error

webofneeds/won-owner-webapp/src/main/webapp/app/components/create-post.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/create-search.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/usecase-group.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/usecase-picker.js, webofneeds/won-owner-webapp/src/main/webapp/style/_create-post.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_other-card.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_usecase-group.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_usecase-picker.scss
Fixes #2883 -> hover over atom-card-map does not show "grab"-cursor anymore
Fixes #2954 -> removes unnecessary back arrows in createview, usecasepicker, usecasegroups components
=> Fix cursor change on non-interactive atom-map, Remove useless backbutton

webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/hokify/receive/CreateAtomFromJobAction.java, webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/hokify/util/HokifyBotsApi.java
Instead of adding lat=lng=0.0 jobLocations in the jobposting we simply omit adding a location at all (that way we will reduce the parserErrors on the client side
fixes #2941
=> Do not add a joblocation to the jobposting

webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-content-buddies.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-content-participants.js
We display every possible atom that can be used as a buddy/group participant directly in the group members and buddies tab. this resulted in a very overcrowded interface  as well as a performance drop (if many atoms are in the state, e.g. after viewing whats new).
This PR adds collapse/expand indicators on the labelled-hr to omit displaying and instantiating the suggest-post-picker component by default
=> Adds simple collapsible invite participant/request as buddy handler

webofneeds/won-owner-webapp/src/main/webapp/app/components/cards/other-card.jsx
Disable the map in other-card, this lowers the performance of the app dramatically (on mobile), leaflet seems to be too costly to initialize multiple times within the ui
=> Deactivates map rendering in other-cards

webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/impl/debugbot/CreateDebugAtomWithSocketsAction.java
As the AtomHint isn't fully implmented at all layers yet, the debugbot is changed with this PR to send a SocketHint by default instead of an AtomHint
=> Debugbot sends SocketHint, not AtomHint

webofneeds/won-docker/deploy/hackathon_satvm02/docker-compose.yml, webofneeds/won-docker/deploy/int_satvm05/docker-compose.yml, webofneeds/won-docker/deploy/live_satvm01/docker-compose.yml, webofneeds/won-docker/deploy/master_satvm02/docker-compose.yml, webofneeds/won-docker/deploy/uki_satvm06/docker-compose.yml
Includes the debug_bot (from the dockerhub image) directly into our docker compose files
This should enable the debug_bot again for all instances (hackathon, live, integration-test, master, uki...) Be aware that merging this onto live makes it necessary to stop and remove orphan containers.... probably debug_bot hokify_bot mail_bot... in order to run. WARNING, if one does not do this before live deployment starts the build will successfully fail and docker will not start
=> Fix  deployment debug bot

webofneeds/won-owner-webapp/src/main/java/won/owner/web/WonOwnerMailSender.java
Fixes a crash on startup that occurs if the starting user does not have write permissions in the /bin folder of the used tomcat installation, i.e. if tomcat was installed system-wide
=> Write velocity log into tomcat log

webofneeds/won-owner-webapp/src/main/webapp/app/components/connections-overview.jsx, webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-persona.js
Currently it is not possible to chat with persona atoms
AdHoc Chats to persona atoms are possible now
- Personas will not have the noHints flags any longer (affects edited personas, as well as personas that are created)
- Personas will have the chatSocket now
- Adds the ability to open a AdHoc chat with any persona (persona 2 persona chats will follow in sep. pr's
This might fix the issue #3018 since we are adding a new socketdefinition for the chatSocket if it wasn't present, however since we can only test this on the live server and we have to remove all the content after the big message refactoring anyway i will mark this issue to be closed once the pr is merged
fixes #3018
=> Feat  persona chat

webofneeds/won-owner-webapp/src/main/webapp/app/components/add-buddy.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-header-big.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-header.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/redux/selectors/general-selectors.js, webofneeds/won-owner-webapp/src/main/webapp/package-lock.json, webofneeds/won-owner-webapp/src/main/webapp/package.json, webofneeds/won-owner-webapp/src/main/webapp/style/_add-buddy.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_atom-header-big.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_persona-card.scss
- Adding a persona as a Buddy is very tedious (you have to select the buddy tab of an owned buddySocket atom and select the buddyatom out of the list below (or add the atom with the atom-picker if the atom was not loaded yet)
- Adds a buddyAction next to the share action for non-owned atoms which have the BuddySocket
- Adds the ability to send/accept BuddyRequests directly from that page
- Either with a List of all possible owned BuddyAtoms (if more than one buddyAtom is owned)
- Or with an immediate Action (if only one buddy atom is owned)
- The atoms in the dropdown as well as the immediate Action will represent the current buddy Connection state (Buddy pending, Accepted …
=> Feat  atom action add buddy

webofneeds/won-owner-webapp/src/main/webapp/app/components/connection-header.jsx, webofneeds/won-owner-webapp/src/main/webapp/style/_connection-header.scss
Routing to atom page with group members tab
- Fixes: #3009 
- Now the "incoming" icon is show to groupchat owners, if there are unseen requests
- Highlightet for new requests
- clicking on the icon will open post info page with open "Group Members" tab
=> Add incoming requests icon

webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-content-buddies.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-content-participants.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-info.jsx, webofneeds/won-owner-webapp/src/main/webapp/style/_atom-content-buddies.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_atom-content-participants.scss
Trying to contact any targetatom that does not have an reactionUseCase adds the option of creating an adhoc atom that connects to the targetatom, if a persona is selected a persona will be attached to the adhoc atom.
- Instead of creating an adHoc Atom with an attached persona we simply connect the chatSocket of the selected persona with the targetAtom (thus enabling persona2persona chats)
- Changes the styling of the participants(groupmembers) and buddies content info from Atom-Cards to atom-headers
Additional call-to-actions to create or goTo a persona2persona chat will be included in separate pull requests
=> Feat  persona to persona chat

webofneeds/conf/matcher-rescal/application.conf, webofneeds/conf/matcher-service/application.conf, webofneeds/conf/matcher-solr/application.conf, webofneeds/conf/matcher-sparql/application.conf, webofneeds/won-docker/deploy/int_satvm05/docker-compose.yml, webofneeds/won-docker/deploy/live_satvm01/docker-compose.yml, webofneeds/won-docker/deploy/master_satvm02/docker-compose.yml, webofneeds/won-docker/deploy_live.sh, webofneeds/won-matcher-service/src/main/java/won/matcher/service/crawler/actor/MasterCrawlerActor.java, webofneeds/won-matcher-service/src/main/java/won/matcher/service/crawler/actor/WorkerCrawlerActor.java
Currently our matcher_service crawls every AtomUri on the configured node, However it will try and reload atoms if any request difficulties arose (e.g. server currently not available). Since we added the 410(GONE) Status and the deletion of atoms, the matcher_service continuously trys to fetch atoms that have been deleted, and thus flooding the node with many requests, depending on the amount of deleted atoms it might even cause other participants connected to the node to get blocked and even unable to execute the sslhandshake due to the vast amount of traffic caused by the matcher_Service -> and thus making every container on the instance unusable.
- Atoms that have been …
=> Fixes matcher_service crawling

webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-content-buddies.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-content-participants.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-context-swipeable-view.jsx, webofneeds/won-owner-webapp/src/main/webapp/style/_atom-content-buddies.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_atom-content-participants.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_icon.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_slidein.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_topnav.scss
To send/accept/reject buddy requests we have buttons. It was not possible to send a direct chatConnectionRequest/Message, via this view.
- Fixes: #3111
- Icons instead of buttons
- SendMessageIcon opens existing, or sends request for new, chatConnection to message directly from persona to persona
As described in #3111 following features are implemented:
- for owned atoms:
- for non owned atoms:
Group Atoms:
- for owned atoms:
- for non owned atoms:
=> Feat  contextsensitive actions #3111

webofneeds/won-core/src/main/java/won/protocol/service/WonNodeInfo.java, webofneeds/won-core/src/main/java/won/protocol/util/WonRdfUtils.java, webofneeds/won-core/src/test/java/won/protocol/model/util/linkeddata/WonRdfUtilsTest.java, webofneeds/won-core/src/test/resources/wonrdfutils/wonnode.trig
Parsing of won node rdf yielded a WonNodeInfo object with a blank node id for Won node URI. Chaos ensued. 
the WoN node URI is parsed correctly
=> Fix parsing of wonnode rdf

webofneeds/won-core/src/main/java/won/protocol/model/MessageEvent.java, webofneeds/won-node/src/main/java/won/node/camel/processor/fixed/DeleteAtomMessageFromOwnerProcessor.java, webofneeds/won-node/src/main/java/won/node/camel/processor/fixed/DeleteAtomMessageFromOwnerReactionProcessor.java, webofneeds/won-node/src/main/java/won/node/camel/processor/general/DeleteAtomMessageProcessor.java, webofneeds/won-owner-webapp/src/main/java/won/owner/web/rest/RestMessageController.java, webofneeds/won-owner-webapp/src/main/java/won/owner/web/service/UserAtomService.java, webofneeds/won-owner/src/main/java/won/owner/model/User.java, webofneeds/won-owner/src/main/java/won/owner/service/impl/UserService.java, webofneeds/won-owner/src/test/java/won/owner/OwnerPersistenceTest.java, webofneeds/won-owner/src/test/java/won/owner/test/OwnerPersistanceTestHelper.java, webofneeds/won-owner/src/test/resources/won/owner/OwnerPersistenceTest.xml
Deletion of held atoms (probably atoms with active connections on any socket) via the webapp is not possible. The node closes all the atom's connections and encounters an error, which propagates into the webapp via activemq, which in turn sends the webapp into an endless loop sending more delete messages for the same atom
* The delete message is handled without causing an error in the node
- some fixes were applied to the node's message handling logic
* Spurious delete messages are responded to with a FailureResponse
* The webapp does not enter an endless loop
=> Fix  delete

webofneeds/won-core/src/main/java/won/protocol/jms/WonJmsConfiguration.java, webofneeds/won-node/src/main/resources/spring/component/broker/activemq.xml
* use DUPS_OK_ACKNOWLEDGE jms acknowledgment mode
* disable flow control because it seems to cause congestion
* discard messages for slow consumers
Configuration of activemq/jms changed.
Clients (consumers) do not receive messages after some time. For each client, this is a permanent error, client restart does not help. Server restart helps, as does forcing a new client id by deleting the owner's keypair. This situation probably arises due to flow-control, when clients are registered for a topic (such as the topic for receiving AtomCreatedNotifications) and then are stopped. The broker keeps a message queue for such a client and keeps adding the messages. however, when a memory …
=> Improve activemq settings

documentation/building.md
Additional tip for 'PKIX path building failed' problem
The troubleshooting docs did not cover the case that the certs change while the application is running, which is an easy thing to fix, at least crudely.
New tip to restart the docker containers
=> Update troubleshooting in building.md

webofneeds/won-bot/src/main/java/won/bot/framework/eventbot/action/EventBotActionUtils.java
... before registering a response listener for it.
A response listener can be registered for an unprepared message, i.e. its URI is still `wm:/SELF`. Such a listener will never be activated and never removed.
Response listeners cannot be registered for unprepared messages.
-
-
-
There are potentially more locations where an unprepared message might be used assuming the message URI will not change. One may want to look into that.
=> Check if message is prepared

webofneeds/pom.xml, webofneeds/won-core/src/main/java/won/protocol/service/WonNodeInfo.java, webofneeds/won-core/src/main/java/won/protocol/util/WonRdfUtils.java, webofneeds/won-core/src/main/java/won/protocol/util/linkeddata/uriresolver/WonMessageUriResolver.java, webofneeds/won-core/src/main/java/won/protocol/vocabulary/WON.java, webofneeds/won-cryptography/pom.xml, webofneeds/won-cryptography/src/main/java/won/cryptography/rdfsign/WonSigner.java, webofneeds/won-cryptography/src/main/java/won/cryptography/rdfsign/WonVerifier.java, webofneeds/won-node-webapp/src/main/java/won/node/web/LinkedDataWebController.java, webofneeds/won-node/src/main/java/won/node/service/linkeddata/generate/LinkedDataServiceImpl.java, webofneeds/won-node/src/main/java/won/node/service/nodeconfig/URIService.java, webofneeds/won-node/src/main/java/won/node/springsecurity/WonDefaultAccessControlRules.java, webofneeds/won-vocab/src/main/resources/ontology/won-core.ttl, webofneeds/won-vocab/src/main/resources/ontology/won-message.ttl
- Build was executed locally, tests with 2 accounts in webapp, also with debugbot are working.
* The message refactoring missed some changes to the ontologies. 
* The representation of hashes and signatures in the message data used to be inconsistent (base58/base64)
* Changes were made to the ontologies that reflect the refactoring. 
* In addition to that, `won:eventURIPrefix` was replaced with `won:messageURIPrefix`. All related method/property names in java classes have been changed as well
* In the message signatures, all binary data is represented using base58 (except for key exponents, which are still hex strings)
* Clients that do not use this PR will not be able to …
=> Feat  update ontology

webofneeds/won-matcher-service/pom.xml, webofneeds/won-matcher-service/src/main/java/won/matcher/service/common/service/sparql/SparqlService.java
The matcher-service can't update a graph in the rdfstore if the respective graph is too big (or has too many triples with the same subject, as containers do via `rfds:member`). The result is a stack overflow logged in the matcher-service log
Updates to graphs are split in batches of <= 250 triples
=> Fix  matcher sparql updates

webofneeds/won-matcher-service/src/main/java/won/matcher/service/common/service/sparql/SparqlService.java, webofneeds/won-matcher-service/src/main/java/won/matcher/service/crawler/actor/MasterCrawlerActor.java, webofneeds/won-matcher-service/src/main/java/won/matcher/service/rematch/actor/RematchActor.java, webofneeds/won-matcher-service/src/main/java/won/matcher/service/rematch/service/RematchSparqlService.java
Matcher has some problems
* the rematch subsystem generates BulkAtomEvents that become too big, resulting in errors and rematching not performed
* the rematch subsystem also generates SPARQL updates that become too big for the sparql parser and therefore fail
* ResourceCrawlEvents that contain the data we would otherwise have to crawl, ('SAVE' events) are are handled like normal crawl events, but not everywhere, leading to these events remaining in the 'pending' list, which prevents regular re-crawls of a node.
All these problems should be fixed now, resulting in regular recrawling and rematching.
=> Fix  matcher too many updates

webofneeds/won-matcher-service/src/main/java/won/matcher/service/crawler/actor/MasterCrawlerActor.java, webofneeds/won-matcher-service/src/main/java/won/matcher/service/nodemanager/actor/HintProducerProtocolActor.java
Hints are sent in-only, like all other messages in the system.
=> Fix  matcher send hints inonly

webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/topnav.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/redux/state-store.js, webofneeds/won-owner-webapp/src/main/webapp/app/service/jsonld-utils.js, webofneeds/won-owner-webapp/src/main/webapp/app/service/linkeddata-service-won.js, webofneeds/won-owner-webapp/src/main/webapp/app/service/vocab.js, webofneeds/won-owner-webapp/src/main/webapp/app/service/won.js, webofneeds/won-owner-webapp/src/main/webapp/package-lock.json, webofneeds/won-owner-webapp/src/main/webapp/package.json
- Remove the workaround because of the jsonld framing spec error
- Reduce message parsing by one framing roundtrip for each message
- Refactor and declutter `won.js`
- Only load the latest 3 Messages for each open chat/group connection instead of the last 10
=> Feat  update jsonld

webofneeds/won-node-webapp/src/main/java/won/node/web/LinkedDataWebController.java, webofneeds/won-node/src/main/java/won/node/service/linkeddata/generate/LinkedDataServiceImpl.java, webofneeds/won-owner-webapp/src/main/java/won/owner/web/rest/BridgeForLinkedDataController.java
* The linked data bridge now sets multiple values of the same header if they are present in the response.
This change enables the paging-relevant headers (of which only the last one is in the response without this PR):
Note that it is possible that all these values are sent in one link header value, separated by commas. Example:
```
Link: <http://www.w3.org/ns/ldp#Resource>; rel="type", <http://www.w3.org/ns/ldp#Page>; rel="type"
Link: <https://localhost:8443/won/resource/atom/ln4xs7q6s5dh/c/tyzm8hk2a4bhcnqb0mlp/msg?resumeafter=wm:/W1oreJeV7FDKaASzJ3BsQemZuGTdodjw3m9sSTr4kc1riy>; rel="next"
Link: <https://localhost:8443/won/resource/atom/ln4xs7q6s5dh/c/tyzm8hk2a4bhcnqb0mlp/msg>; …
```
=> Fix multi-valued headers in LD bridge

webofneeds/won-owner-webapp/src/main/java/won/owner/web/rest/BridgeForLinkedDataController.java
text/html responses from the node are not passed on properly by the linked data bridge in th owner webapp. They cause a 502 (bad gateway) status, and the headers are not copied, the response body is copied.
- The media type generated by the node when it returns html is parsed correctly, and the headers as well as the body are copied to the response
- If the media type of the response is anything but `text/html` or the RDF media types, neither the headers nor the body are delivered and the status is 502.
=> Fix text/html responses via LD bridge

webofneeds/won-docker/image/nginx/nginx.conf
This changes the forwarding of rsa pages from port 4431 to 443, to allow for the load balancer to handle the requests
=> Updated forwarding of rsa webpages through won

webofneeds/won-owner-webapp/src/main/webapp/app/api/owner-api.js, webofneeds/won-owner-webapp/src/main/webapp/package-lock.json, webofneeds/won-owner-webapp/src/main/webapp/package.json
dedupe requests -> makes whats new / suggestions faster if many visible metaatoms would have the same persona, by limiting a getJsonLd request to only have one single in flight per uri -> bestfetch-caching is still disabled otherwise we would run into issues when editing atoms
=> Dedupes requests

webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/location-picker.jsx
- Fixes #3091 
- When clicking on the map in the location picker, a marker is placed at the selected position and the location bar is updated with the corrdinates of the marker.
Having the coordinates in the location bar is not very elegant, especially since right now they can't be entered that way. An alternative would be to use nominatim to reverse-search an address, but trying that I had very inconsistent results.
A third option would be to use the original lat and lng, but use the location name provided by nominatim. I am not sure how this would affect later matching of the created atoms though.
=> Added handler for clicking on map

webofneeds/won-owner-webapp/src/main/webapp/app/components/details/picker/suggest-atom-picker.jsx
- Fixes: #3033  When typing a url that is already known by the suggest atom picker into the custom url field, it is suddenly deleted
- The suggest atom picker now checks whether it has just finished a load before clearing the input, instead of clearing it whenever the url in the input is already present in the suggestions
The introduced state variable that tracks whether a request is in progress loses its value on the first fetch because the component is recreated. This is a problem in [`create-isseeks.jsx`](https://github.com/researchstudio-sat/webofneeds/webofneeds/won-owner-webapp/src/main/webapp/app/components/create-isseeks.jsx).
=> Fixed input reset in atom picker

webofneeds/won-owner-webapp/src/main/webapp/app/components/messages/connection-message.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/atom-reducer/atom-reducer-main.js, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/atom-reducer/reduce-messages.js
referenced/changed messages are set to unread +
set to read by time if message is visible
- Fixes: #3261 
- Messages are now set to unread if they are visible
- Referenced/changed messages are set to unread as well
- Hidden messages are directly marked as read
=> Mark message read & unread

webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-messages.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/components/cards/pokemon-raid-card.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/components/group-atom-messages.jsx
- [] Affected Tests have been added/altered (for bug fixes / features)
- [] Docs have been reviewed and added/updated if needed (for bug fixes / features)
- Viewing a chat or groupchat that has less than 10 messages stored in the state after the initialFetch will lead to an endless fetch loop
- Pokemon Raid Cards dont have a Clickable/Link Image
- Endless fetch is omitted
- Pokemon Raid Cards have a Link/Click handler on the image now
=> Fix  endless fetch

webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-info.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/components/edit-atom.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/redux/utils/atom-utils.js, webofneeds/won-owner-webapp/src/main/webapp/app/usecase-utils.js
- Atoms that do not have a specific socket that is used as a reaction would show the addToReaction footer anyway
- Edit does not add missing sockets to an atom
- Prevent display of the "add X" reaction buttons if the socket used in the reaction is not present in the atom
- Adds every socket that is defined in the useCase but not yet present in an atom when an atom is edited
- Implements a generic socketKeys reset (reset socketUris from atomUri#socketX back to #socketX) -> used for duplicating atoms, up until now we would have to add a case for each new socket we define/use in a useCase. this is no longer the "case" (pun intended)
=> Add Missing Sockets to an Atom after EDIT

webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-actions.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-content.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-content/atom-content-socket.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-header-big.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-info.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/components/socket-add-atom.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/components/socket-add-button.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/components/socket-items/generic-item.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/pages/react/map.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/pages/react/overview.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/atom-reducer/parse-atom.js, webofneeds/won-owner-webapp/src/main/webapp/app/redux/utils/atom-utils.js, webofneeds/won-owner-webapp/src/main/webapp/app/won-label-utils.js, webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-cycling.js, webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-lunch.js, webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-pokemon.js, webofneeds/won-owner-webapp/src/main/webapp/style/_atom-actions.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_atom-header-big.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_atom-info.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_won-config.scss, webofneeds/won-vocab/src/main/resources/ontology/ext/won-ext-demo.ttl
- Currently when navigating from an atom to another atom by clicking it in the specific socket tab, a browser back will cause the tab of the original atom to be reset to the detail page
- Keep selected tab of previous post selected on Browser back
- Update atom-actions (connection actions) of an atom
- Change Interest UseCase Labels
=> Feat Improve Post (connections-actions, and routing/navigation)

webofneeds/won-core/src/main/java/won/protocol/rest/LinkedDataFetchingException.java, webofneeds/won-core/src/main/java/won/protocol/rest/LinkedDataRestClient.java, webofneeds/won-core/src/main/java/won/protocol/util/linkeddata/LinkedDataSourceBase.java, webofneeds/won-matcher-service/src/main/java/won/matcher/service/rematch/service/RematchSparqlService.java, webofneeds/won-owner-webapp/src/main/java/won/owner/web/websocket/EagerlyCachePopulatingMessageProcessor.java
With this fix, deleted atoms are removed from the rematch index, leading to fewer requests to the node during rematching. The LinkedDataSource now throws the LinkedDataFetchingException on instead of swallowing it, so clients can use the exception in their error handling logic.
The matchers keep fetching deleted atom data.  Over time, many atoms get deleted -> many spurious fetches.
- Fixes: N/A
Deleted atoms are removed from rematch index
The LinkedDataSource throws the LinkedDataFetchingException instead of swallowing it, so clients might break now.
=> Fix rematching for deleted atoms

webofneeds/won-owner-webapp/src/main/java/won/owner/web/WonOwnerMailSender.java, webofneeds/won-owner-webapp/src/main/webapp/app/actions/account-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/load-action.js, webofneeds/won-owner-webapp/src/main/webapp/app/actions/messages-actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/app.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-content.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-header-big.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-header.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-info.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/components/chat-textfield.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/components/create-atom.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/pages/react/connections.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/pages/react/create.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/pages/react/inventory.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/pages/react/post.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/redux/state-store.js, webofneeds/won-owner-webapp/src/main/webapp/app/redux/utils/atom-utils.js, webofneeds/won-owner-webapp/src/main/webapp/style/_atom-content.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_atom-header-big.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_atom-info.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_inventory.scss, webofneeds/won-owner-webapp/src/main/webapp/style/_post.scss, webofneeds/won-owner-webapp/src/main/webapp/style/won.scss, webofneeds/won-owner-webapp/src/main/webapp/sw.js
Currently the initialLoad (on login, or page load) will fetch all owned Atoms incl. their connections, this is rather slow for Users with alot of owned Atoms
Initial Load only fetches MetaData now (all owned atomUris incl. their metaInfo eg. atomType state etc)
- Connection View: Fetches all ownedAtoms incl their connections if there is no postUri in the url -> non deep link)
- Chat-Textfield and Create-atom fetches the owned unloaded Personas (so that the personapicker in the publish/send button is present)
- Atom-info fetches an atom if it is not loaded in the state yet (inventory would have not fetched personas otherwise)
Everything else stays the same since the fetch of …
=> Feat  "smart" fetch

webofneeds/won-auth/src/main/java/won/auth/WonAclEvaluator.java, webofneeds/won-auth/src/main/java/won/auth/WonAclEvaluatorFactory.java, webofneeds/won-auth/src/main/java/won/auth/check/ConnectionTargetCheck.java, webofneeds/won-auth/src/main/java/won/auth/check/ConnectionTargetCheckEvaluator.java, webofneeds/won-auth/src/main/java/won/auth/check/TargetAtomCheckEvaluator.java, webofneeds/won-auth/src/main/java/won/auth/check/impl/AcceptAll.java, webofneeds/won-auth/src/main/java/won/auth/support/ConnectionTargetCheckGenerator.java, webofneeds/won-auth/src/test/java/won/auth/GrantedOperationsTest.java, webofneeds/won-auth/src/test/java/won/auth/ModelBasedConnectionTargetCheckEvaluator.java, webofneeds/won-auth/src/test/java/won/auth/ModelBasedTargetAtomCheckEvaluator.java, webofneeds/won-auth/src/test/java/won/auth/WonAclEvaluatorTest.java, webofneeds/won-auth/src/test/java/won/auth/WonAclEvaluatorTestFactory.java, webofneeds/won-auth/src/test/resources/won/opreq/fail/opreq-010.ttl, webofneeds/won-auth/src/test/resources/won/opreq/fail/opreq-011.ttl, webofneeds/won-auth/src/test/resources/won/opreq/fail/opreq-012.ttl, webofneeds/won-auth/src/test/resources/won/opreq/fail/opreq-013.ttl, webofneeds/won-auth/src/test/resources/won/opreq/spec/opreq-027.ttl, webofneeds/won-core/src/main/java/won/protocol/repository/ConnectionRepository.java, webofneeds/won-core/src/main/java/won/protocol/util/linkeddata/CachingLinkedDataSource.java, webofneeds/won-cryptography/src/main/java/won/cryptography/rdfsign/WonVerifier.java, webofneeds/won-node-webapp/src/main/resources/spring/node-context.xml, webofneeds/won-node/src/main/java/won/node/camel/processor/general/AclChecker.java, webofneeds/won-node/src/main/java/won/node/camel/processor/general/RoutingInfoExtractor.java, webofneeds/won-node/src/main/java/won/node/service/persistence/AtomService.java, webofneeds/won-node/src/main/java/won/node/springsecurity/acl/WonAclAccessDecisionVoter.java, webofneeds/won-node/src/main/java/won/node/springsecurity/acl/WonConnectionTargetCheckEvaluator.java, webofneeds/won-node/src/main/java/won/node/springsecurity/acl/WonTargetAtomCheckEvaluator.java, webofneeds/won-vocab/src/main/resources/ontology/won-auth.ttl
* new auth property: auth:targetWonNode
* change TargetATomCheck to ConnectionTargetCheck, it's either checking the target atom or the won node of the target atom
* add a test case
* add an implicit Authorization: if local atom A has a connection to atom B on a remote node, allow that node to see the key graph of atom A.
WoN messaging across WoN nodes is not possible. The receiving node cannot verify the incoming message as it does not (necessarily) have access to the sending atom's public key. 
In addition to that, the nodes enter a deadlock trying  to verify each other's WebID. 
We add the option to allow ACL grants to won nodes, defined as the `target WoN node` of a …
=> Grant access rights to WoN nodes

webofneeds/won-owner-webapp/src/main/webapp/app/actions/actions.js, webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-card.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-content.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-header-big.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-header.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/components/atom-tag-header.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/components/cards/skeleton-card.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/components/socket-add-atom.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/components/topnav.jsx, webofneeds/won-owner-webapp/src/main/webapp/app/reducers/process-reducer.js, webofneeds/won-owner-webapp/src/main/webapp/app/redux/selectors/general-selectors.js, webofneeds/won-owner-webapp/src/main/webapp/app/redux/selectors/process-selectors.js, webofneeds/won-owner-webapp/src/main/webapp/app/redux/state-store.js, webofneeds/won-owner-webapp/src/main/webapp/app/redux/utils/atom-utils.js, webofneeds/won-owner-webapp/src/main/webapp/app/redux/utils/process-utils.js, webofneeds/won-owner-webapp/src/main/webapp/app/won-label-utils.js, webofneeds/won-owner-webapp/src/main/webapp/config/usecases/uc-role.js
- Currently we run into a loop when fetching Connection Containers
- We also do not fetch connectionContainers again if the initial Amount of possibilities has been reached -> no data reload even if more requestCredentials would be available
- the label generation was using a lot of unnecessary state retrievals
- atom in state loading did not always show the skeleton/loading card
- the fetch loop has been removed
- connContainers are loaded again if new requestCredentials "arise"
- label generation is simplified
- atom loading ui is displayed appropriately for atom-cards
=> Feat datareload2

webofneeds/won-core/src/main/java/won/protocol/rest/LinkedDataRestClientHttps.java, webofneeds/won-docker/deploy/local_build/logback-config/logback.xml, webofneeds/won-owner-webapp/src/main/java/won/owner/web/rest/BridgeForLinkedDataController.java, webofneeds/won-owner-webapp/src/main/java/won/owner/web/rest/RestAtomController.java, webofneeds/won-owner-webapp/src/main/java/won/owner/web/service/UserAtomService.java, webofneeds/won-owner/src/main/resources/spring/component/linkeddatasource/owner-linkeddatasource.xml
If your atoms are not publicly readable, the owner webapp breaks
the owner webapp should handle private atoms just fine
=> Use WebIDs in owner webapp to fetch owned atoms

webofneeds/won-owner-webapp/src/main/java/won/owner/web/websocket/WonWebSocketHandler.java
Before sending a push notification, we used to check if the sending atom and the recipient atom belong to the same user. This check does not seem to work for group chats (in which messages are forwarded by the group atom). We remove this check as the overall experience is better without it.
- Fixes: N/A
-
-
-
=> Remove test for owned atoms

webofneeds/won-auth/src/main/java/won/auth/rest/AuthEnabledLinkedDataRestClient.java, webofneeds/won-core/src/main/java/won/protocol/rest/LDRequestForbiddenWwwAuthenticateException.java, webofneeds/won-core/src/main/java/won/protocol/rest/LinkedDataFetchingException.java, webofneeds/won-core/src/main/java/won/protocol/rest/LinkedDataRestClient.java, webofneeds/won-matcher-service/src/main/java/won/matcher/service/rematch/service/RematchSparqlService.java
The matcher-service removes an atom from the rematching index only if it gets a 410 response. Attempts that fail with other errors are not registered as rematch attempts and are therefore checked for rematching at the next rematch tick (every 60s). This leads to constantly rematching atoms with 401 or 403 responses, flooding the node with requests.
The matcher-service removes an atom from the rematching index if it gets a 410 response and registers a rematch attempt for any other error response (4xx or 5xx), thus the usual back-off strategy is followed. This allows for dealing with temporary unavailability or changing access rights for the matcher.
=> Differentiated error handling while rematching
